-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Mouse.Button

---@class Enums.sf.Mouse.Button
---@field Extra1 sf.Mouse.Button
---@field Extra2 sf.Mouse.Button
---@field Left sf.Mouse.Button
---@field Middle sf.Mouse.Button
---@field Right sf.Mouse.Button
---@type Enums.sf.Mouse.Button
local enum = {}

return enum
