-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Mouse.Wheel

---@class Enums.sf.Mouse.Wheel
---@field Horizontal sf.Mouse.Wheel
---@field Vertical sf.Mouse.Wheel
---@type Enums.sf.Mouse.Wheel
local enum = {}

return enum
