-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.TcpSocket.TlsStatus
local enum = {
    Error = (3 --[[@as sf.TcpSocket.TlsStatus]]),
    HandshakeComplete = (2 --[[@as sf.TcpSocket.TlsStatus]]),
    HandshakeStarted = (1 --[[@as sf.TcpSocket.TlsStatus]]),
    NotConnected = (0 --[[@as sf.TcpSocket.TlsStatus]]),
}

return enum
