-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.TcpSocket.TlsStatus

---@class Enums.sf.TcpSocket.TlsStatus
---@field Error sf.TcpSocket.TlsStatus
---@field HandshakeComplete sf.TcpSocket.TlsStatus
---@field HandshakeStarted sf.TcpSocket.TlsStatus
---@field NotConnected sf.TcpSocket.TlsStatus
---@type Enums.sf.TcpSocket.TlsStatus
local enum = {}

return enum
