-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.BlendMode.Factor

---@class Enums.sf.BlendMode.Factor
---@field DstAlpha sf.BlendMode.Factor
---@field DstColor sf.BlendMode.Factor
---@field One sf.BlendMode.Factor
---@field OneMinusDstAlpha sf.BlendMode.Factor
---@field OneMinusDstColor sf.BlendMode.Factor
---@field OneMinusSrcAlpha sf.BlendMode.Factor
---@field OneMinusSrcColor sf.BlendMode.Factor
---@field SrcAlpha sf.BlendMode.Factor
---@field SrcColor sf.BlendMode.Factor
---@field Zero sf.BlendMode.Factor
---@type Enums.sf.BlendMode.Factor
local enum = {}

return enum
