-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowShop.WindowShopCell

---@class Internal.UIBase.GeneratedControls.Parts.WindowShop.WindowShopCell
---@field Icon      Engine.FunctionalImage
---@field Root      Engine.Canvas
---@field ValueText Engine.PlainText

---@class Internal.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopCell

---@class Internal.UI.Parts.WindowShop.WindowShopCell: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowShop.WindowShopCell
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopCell
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowShop.WindowShopCell
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
