-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowShop.WindowShopDetail

---@class Internal.UIBase.GeneratedControls.Parts.WindowShop.WindowShopDetail
---@field Content         Engine.Canvas
---@field Description     Engine.PlainText
---@field DescriptionArea Engine.Canvas
---@field ItemName        Engine.PlainText
---@field Price           Engine.PlainText
---@field PriceLabel      Engine.PlainText
---@field Root            Engine.Canvas
---@field WindowFrame     Engine.Window

---@class Internal.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopDetail
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.WindowShop.WindowShopDetail: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowShop.WindowShopDetail
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopDetail
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowShop.WindowShopDetail
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
