-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowShop.WindowShopItem

---@class Internal.UIBase.GeneratedControls.Parts.WindowShop.WindowShopItem
---@field Content       Engine.Canvas
---@field ItemList      Engine.ListView
---@field ItemScrollBox Engine.ScrollBox
---@field Root          Engine.Canvas
---@field WindowFrame   Engine.Window

---@class Internal.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopItem
---@field ShopItemPlaceholder1  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder10 Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder11 Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder12 Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder13 Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder14 Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder2  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder3  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder4  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder5  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder6  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder7  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder8  Internal.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder9  Internal.UI.Parts.WindowShop.WindowShopCell
---@field WindowChrome          Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark       Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.WindowShop.WindowShopItem: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowShop.WindowShopItem
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopItem
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowShop.WindowShopItem
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
