-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.Parts.ConfigWindow.ConfigCheckBoxRow
local View = {}

View.assetKey = "Parts/ConfigWindow/ConfigCheckBoxRow"
View.designSize = sf.Vector2f.new(448, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        CheckBox = assert(self.instance:requireControl("CheckBox")),
        Label = assert(self.instance:requireControl("Label")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigCheckBoxRow
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigCheckBoxRow
    self.assets = assets
end

return class(View, UiView)
