-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand

---@class Source.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field CommandList      Engine.ListView
---@field CommandScrollBox Engine.ScrollBox
---@field Content          Engine.Canvas
---@field Root             Engine.Canvas
---@field WindowFrame      Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field MapPlaceholder1 Source.UI.Parts.Shared.CommandRow
---@field MapPlaceholder2 Source.UI.Parts.Shared.CommandRow
---@field MapPlaceholder3 Source.UI.Parts.Shared.CommandRow
---@field MapPlaceholder4 Source.UI.Parts.Shared.CommandRow
---@field MapPlaceholder5 Source.UI.Parts.Shared.CommandRow
---@field MapPlaceholder6 Source.UI.Parts.Shared.CommandRow
---@field MapPlaceholder7 Source.UI.Parts.Shared.CommandRow

---@class Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
