-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.Parts.Shared.WindowPauseMark
local View = {}

View.assetKey = "Parts/Shared/WindowPauseMark"
View.designSize = sf.Vector2f.new(16, 16)

function View:init(instance)
    UiView.init(self, instance)
    local controls = { PauseMark = assert(self.instance:requireControl("PauseMark")) }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.Shared.WindowPauseMark
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.Shared.WindowPauseMark
    self.assets = assets
end

return class(View, UiView)
