-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.WindowMagicDoor
local View = {}

View.assetKey = "WindowMagicDoor"
View.designSize = sf.Vector2f.new(96, 64)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Count = assert(self.instance:requireControl("Count")),
        Icon = assert(self.instance:requireControl("Icon")),
        Multiply = assert(self.instance:requireControl("Multiply")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.WindowMagicDoor
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.WindowMagicDoor
    self.assets = assets
end

return class(View, UiView)
