-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")

---@class Internal.UI.WindowBattle
local View = {}

View.assetKey = "WindowBattle"
View.designSize = sf.Vector2f.new(416, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        AttackSkillButton = assert(self.instance:requireControl("AttackSkillButton")),
        AttackSkillButtonSelected = assert(self.instance:requireControl("AttackSkillButtonSelected")),
        BreathDim = assert(self.instance:requireControl("BreathDim")),
        BreathLit = assert(self.instance:requireControl("BreathLit")),
        Content = assert(self.instance:requireControl("Content")),
        CriticalButton = assert(self.instance:requireControl("CriticalButton")),
        CriticalButtonSelected = assert(self.instance:requireControl("CriticalButtonSelected")),
        DefenseSkillButton = assert(self.instance:requireControl("DefenseSkillButton")),
        DefenseSkillButtonSelected = assert(self.instance:requireControl("DefenseSkillButtonSelected")),
        EnemyATKDelta = assert(self.instance:requireControl("EnemyATKDelta")),
        EnemyATKLabel = assert(self.instance:requireControl("EnemyATKLabel")),
        EnemyATKValue = assert(self.instance:requireControl("EnemyATKValue")),
        EnemyBREATHLabel = assert(self.instance:requireControl("EnemyBREATHLabel")),
        EnemyBreathBar = assert(self.instance:requireControl("EnemyBreathBar")),
        EnemyDEFDelta = assert(self.instance:requireControl("EnemyDEFDelta")),
        EnemyDEFLabel = assert(self.instance:requireControl("EnemyDEFLabel")),
        EnemyDEFValue = assert(self.instance:requireControl("EnemyDEFValue")),
        EnemyFATIGUELabel = assert(self.instance:requireControl("EnemyFATIGUELabel")),
        EnemyFATIGUEValue = assert(self.instance:requireControl("EnemyFATIGUEValue")),
        EnemyHPLabel = assert(self.instance:requireControl("EnemyHPLabel")),
        EnemyHPValue = assert(self.instance:requireControl("EnemyHPValue")),
        EnemyName = assert(self.instance:requireControl("EnemyName")),
        EnemyNameArea = assert(self.instance:requireControl("EnemyNameArea")),
        EnemyPortrait = assert(self.instance:requireControl("EnemyPortrait")),
        PlayerATKDelta = assert(self.instance:requireControl("PlayerATKDelta")),
        PlayerATKLabel = assert(self.instance:requireControl("PlayerATKLabel")),
        PlayerATKValue = assert(self.instance:requireControl("PlayerATKValue")),
        PlayerBREATHLabel = assert(self.instance:requireControl("PlayerBREATHLabel")),
        PlayerBreathBar = assert(self.instance:requireControl("PlayerBreathBar")),
        PlayerDEFDelta = assert(self.instance:requireControl("PlayerDEFDelta")),
        PlayerDEFLabel = assert(self.instance:requireControl("PlayerDEFLabel")),
        PlayerDEFValue = assert(self.instance:requireControl("PlayerDEFValue")),
        PlayerFATIGUELabel = assert(self.instance:requireControl("PlayerFATIGUELabel")),
        PlayerFATIGUEValue = assert(self.instance:requireControl("PlayerFATIGUEValue")),
        PlayerHPLabel = assert(self.instance:requireControl("PlayerHPLabel")),
        PlayerHPValue = assert(self.instance:requireControl("PlayerHPValue")),
        PlayerName = assert(self.instance:requireControl("PlayerName")),
        PlayerNameArea = assert(self.instance:requireControl("PlayerNameArea")),
        PlayerPortrait = assert(self.instance:requireControl("PlayerPortrait")),
        RetreatButton = assert(self.instance:requireControl("RetreatButton")),
        RetreatTouchArea = assert(self.instance:requireControl("RetreatTouchArea")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.WindowBattle
    self.controls = controls
    local assets = {
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.WindowBattle
    self.assets = assets
end

return class(View, UiView)
