-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")
local ChildView3 = require("Internal.UI.Parts.WindowEnemyBook.WindowEnemyBookCell")

---@class Internal.UI.WindowEnemyBook
local View = {}

View.assetKey = "WindowEnemyBook"
View.designSize = sf.Vector2f.new(352, 352)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        EnemyList = assert(self.instance:requireControl("EnemyList")),
        EnemyScrollBox = assert(self.instance:requireControl("EnemyScrollBox")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.WindowEnemyBook
    self.controls = controls
    local assets = {
        EnemyItem1 = self:own(ChildView3.new(assert(self.instance:requireAsset("EnemyItem1")))),
        EnemyItem2 = self:own(ChildView3.new(assert(self.instance:requireAsset("EnemyItem2")))),
        EnemyItem3 = self:own(ChildView3.new(assert(self.instance:requireAsset("EnemyItem3")))),
        EnemyItem4 = self:own(ChildView3.new(assert(self.instance:requireAsset("EnemyItem4")))),
        EnemyItem5 = self:own(ChildView3.new(assert(self.instance:requireAsset("EnemyItem5")))),
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.WindowEnemyBook
    self.assets = assets
end

return class(View, UiView)
