-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")
local ChildView3 = require("Internal.UI.Parts.WindowAttrShop.AttrShopRow")

---@class Internal.UI.WindowAttrShop
local View = {}

View.assetKey = "WindowAttrShop"
View.designSize = sf.Vector2f.new(352, 352)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        AbilityList = assert(self.instance:requireControl("AbilityList")),
        AbilityScrollBox = assert(self.instance:requireControl("AbilityScrollBox")),
        Avatar = assert(self.instance:requireControl("Avatar")),
        Content = assert(self.instance:requireControl("Content")),
        Description = assert(self.instance:requireControl("Description")),
        Price = assert(self.instance:requireControl("Price")),
        Root = assert(self.instance:requireControl("Root")),
        ShopName = assert(self.instance:requireControl("ShopName")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.WindowAttrShop
    self.controls = controls
    local assets = {
        AbilityItem1 = self:own(ChildView3.new(assert(self.instance:requireAsset("AbilityItem1")))),
        AbilityItem2 = self:own(ChildView3.new(assert(self.instance:requireAsset("AbilityItem2")))),
        AbilityItem3 = self:own(ChildView3.new(assert(self.instance:requireAsset("AbilityItem3")))),
        AbilityItem4 = self:own(ChildView3.new(assert(self.instance:requireAsset("AbilityItem4")))),
        AbilityItem5 = self:own(ChildView3.new(assert(self.instance:requireAsset("AbilityItem5")))),
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.WindowAttrShop
    self.assets = assets
end

return class(View, UiView)
