-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")
local ChildView3 = require("Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair")
local ChildView4 = require("Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow")

---@class Internal.UI.WindowEnemyEncyclopedia
local View = {}

View.assetKey = "WindowEnemyEncyclopedia"
View.designSize = sf.Vector2f.new(640, 480)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Description = assert(self.instance:requireControl("Description")),
        DescriptionArea = assert(self.instance:requireControl("DescriptionArea")),
        InfoLayer = assert(self.instance:requireControl("InfoLayer")),
        Name = assert(self.instance:requireControl("Name")),
        NameArea = assert(self.instance:requireControl("NameArea")),
        Portrait = assert(self.instance:requireControl("Portrait")),
        Root = assert(self.instance:requireControl("Root")),
        SpecialList = assert(self.instance:requireControl("SpecialList")),
        SpecialScrollBox = assert(self.instance:requireControl("SpecialScrollBox")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.WindowEnemyEncyclopedia
    self.controls = controls
    local assets = {
        InfoItem1 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem1")))),
        InfoItem2 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem2")))),
        InfoItem3 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem3")))),
        InfoItem4 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem4")))),
        InfoItem5 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem5")))),
        InfoItem6 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem6")))),
        InfoItem7 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem7")))),
        InfoItem8 = self:own(ChildView3.new(assert(self.instance:requireAsset("InfoItem8")))),
        SpecialItem1 = self:own(ChildView4.new(assert(self.instance:requireAsset("SpecialItem1")))),
        SpecialItem2 = self:own(ChildView4.new(assert(self.instance:requireAsset("SpecialItem2")))),
        SpecialItem3 = self:own(ChildView4.new(assert(self.instance:requireAsset("SpecialItem3")))),
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.WindowEnemyEncyclopedia
    self.assets = assets
end

return class(View, UiView)
