-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.BattleFloatingText

---@class Source.UIBase.GeneratedControls.Parts.BattleFloatingText
---@field Damage  Engine.PlainText
---@field Healing Engine.PlainText
---@field Root    Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.BattleFloatingText

---@class Source.UI.Parts.BattleFloatingText: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.BattleFloatingText
---@field assets   Source.UIBase.GeneratedAssets.Parts.BattleFloatingText
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.BattleFloatingText
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
