-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowMessage.MessageOptionRow

---@class Internal.UIBase.GeneratedControls.Parts.WindowMessage.MessageOptionRow
---@field Root Engine.FunctionalPlainText

---@class Internal.UIBase.GeneratedAssets.Parts.WindowMessage.MessageOptionRow

---@class Internal.UI.Parts.WindowMessage.MessageOptionRow: Internal.UIBase.UiView
---@field root     Engine.FunctionalPlainText
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowMessage.MessageOptionRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowMessage.MessageOptionRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowMessage.MessageOptionRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
