-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.HUDPlayerAttr

---
--- Shows the player's avatar, current map name, level, states, HP bar with value, and stat values.
---@class Source.Windows.PlayerAttrHUD: Engine.Canvas, Source.UIBase.Ui.Window
---@field ui Source.UI.PlayerAttrHUD
local Window = {}

--- Construct a player attribute HUD bound to the given player instance.
---
--- - @param player  Target player whose attributes are displayed on this HUD
--- - @param openMenuCallback Callback invoked when the player avatar is clicked
---@param player           Source.Player.Player
---@param openMenuCallback function | nil
---@return Source.Windows.PlayerAttrHUD
function Window.new(player, openMenuCallback) end

--- Construct a player attribute HUD bound to the given player instance.
---
--- - @param player  Target player whose attributes are displayed on this HUD
--- - @param openMenuCallback Callback invoked when the player avatar is clicked
---@param player           Source.Player.Player
---@param openMenuCallback function | nil
---@param ui               Source.UI.PlayerAttrHUD
---@return Source.Windows.PlayerAttrHUD
function Window.FromView(ui, player, openMenuCallback) end

function Window:bind() end

---@return Source.Player.Player
function Window:getPlayer() end

--- Poll lightweight player signatures every frame and refresh only the HUD groups whose displayed values changed.
---
--- - @param deltaTime  Elapsed frame time in seconds
---@param deltaTime number
function Window:onTick(deltaTime) end

function Window:openMenu() end

---@param logicalSize sf.Vector2u | nil
---@return Engine.Canvas
function Window:prepare(logicalSize) end

function Window:refresh() end

---@param language string | nil
---@return boolean
function Window:refreshStates(language) end

--- Rebind the player whose values are displayed by this HUD.
---
--- - @param player Target player.
---@param player Source.Player.Player
function Window:setPlayer(player) end

return Window
