-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowShop

---@brief Integrated shop UI with tabs, item list, and item details.
---@class Source.Windows.WindowShop: Engine.Canvas, Source.UIBase.Ui.Window
---@field ui             Source.UI.WindowShop
---@field SHOP_MODE_BUY  "buy"
---@field SHOP_MODE_SELL "sell"
local Window = {}

---@param player  Source.Player.Player
---@param onClose function | nil
---@return Source.Windows.WindowShop
function Window.new(player, onClose) end

---@param player  Source.Player.Player
---@param onClose function | nil
---@param ui      Source.UI.WindowShop
---@return Source.Windows.WindowShop
function Window.FromView(ui, player, onClose) end

---@param itemID string
---@return integer
function Window.GetItemPrice(itemID) end

---@param itemID string
---@return integer
function Window.GetSellPrice(itemID) end

---@param buyItemIDs table
---@return table
function Window.NormalizeBuyItems(buyItemIDs) end

---@param onHidden function | nil
function Window:close(onHidden) end

function Window:closeByCancel() end

function Window:confirmItem() end

---@return Source.Windows.WindowShopDetail
function Window:getDetailWindow() end

---@return Source.Windows.WindowShopItem
function Window:getItemWindow() end

---@return Source.Windows.WindowShopTabs
function Window:getTabWindow() end

---@return boolean
function Window:getVisible() end

---@return boolean
function Window:handleTabNavigationInput() end

---@return boolean
function Window:isClosed() end

function Window:notifyItemIndexMaybeChanged() end

---@param index integer
function Window:onTabSelected(index) end

---@param buyItemIDs table
---@param canSell    boolean
function Window:open(buyItemIDs, canSell) end

function Window:refreshLocale() end

---@param mode string
function Window:setMode(mode) end

---@param player Source.Player.Player
function Window:setPlayer(player) end

return Window
