-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowBattle

---@class Source.Windows.WindowBattle: Source.Windows.Base.WindowBase, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowBattle
local Window = {}

---@param scene Source.Gameplay.GameplayScene
---@return Source.Windows.WindowBattle
function Window.new(scene) end

---@param scene Source.Gameplay.GameplayScene
---@param ui    Source.UI.WindowBattle
---@return Source.Windows.WindowBattle
function Window.FromView(ui, scene) end

---@param state  Source.Windows.WindowBattle.BattlerState
---@param amount integer
function Window:addBreath(state, amount) end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
function Window:applyAttackStates(attacker, defender) end

---@param playerTurn    boolean
---@param remainingHits integer | nil
function Window:beginTurn(playerTurn, remainingHits) end

function Window:bind() end

---@param attacker     Source.Windows.WindowBattle.BattlerState
---@param defender     Source.Windows.WindowBattle.BattlerState
---@param critical     boolean
---@param attackSkill? boolean
---@return integer damage
---@return integer base
function Window:calculateDamage(attacker, defender, critical, attackSkill) end

---@param state Source.Windows.WindowBattle.BattlerState
---@param cost  integer
---@return boolean
function Window:canAffordSkill(state, cost) end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
---@return boolean
function Window:canAttackSkill(attacker, defender) end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
---@return boolean
function Window:canCritical(attacker, defender) end

---@param state Source.Windows.WindowBattle.BattlerState
---@return boolean
function Window:canDefenseSkill(state) end

function Window:cancel() end

---@param state Source.Windows.WindowBattle.BattlerState
---@param delta integer
---@return integer
function Window:changeHP(state, delta) end

---@param attacker      Source.Windows.WindowBattle.BattlerState
---@param defender      Source.Windows.WindowBattle.BattlerState
---@param remainingHits integer
function Window:criticalAttack(attacker, defender, remainingHits) end

function Window:dispose() end

---@param result Source.Windows.WindowBattle.Result
function Window:finish(result) end

---@param kind "Lit" | "Dim"
---@return Engine.WrapBox
function Window:getBreathBox(kind) end

---@param kind  "Lit" | "Dim"
---@param index integer
---@return Engine.Canvas
function Window:getBreathCanvas(kind, index) end

---@param attacker      Source.Windows.WindowBattle.BattlerState
---@param defender      Source.Windows.WindowBattle.BattlerState
---@param remainingHits integer
function Window:normalAttack(attacker, defender, remainingHits) end

---@param state Source.Windows.WindowBattle.BattlerState
---@param side  "Player" | "Enemy"
function Window:observeState(state, side) end

---@param side  "Player" | "Enemy"
---@param delta integer
function Window:onHPChanged(side, delta) end

---@param kwargs Engine.UiInputEventArguments
function Window:onKeyDown(kwargs) end

---@param player     Source.Player.Player
---@param enemy      Source.Enemy
---@param onFinished Source.Windows.WindowBattle.Finished
function Window:open(player, enemy, onFinished) end

---@param attacker      Source.Windows.WindowBattle.BattlerState
---@param defender      Source.Windows.WindowBattle.BattlerState
---@param critical      boolean
---@param remainingHits integer
---@param attackSkill?  boolean
function Window:performAttack(attacker, defender, critical, remainingHits, attackSkill) end

function Window:playBreathAnimation() end

---@param attacker      Source.Windows.WindowBattle.BattlerState
---@param defender      Source.Windows.WindowBattle.BattlerState
---@param damage        integer
---@param critical      boolean
---@param attackSkill?  boolean
---@param defenseSkill? boolean
function Window:receiveAttack(attacker, defender, damage, critical, attackSkill, defenseSkill) end

function Window:refresh() end

---@param name     string
---@param selected boolean
---@param enabled  boolean | nil
function Window:refreshActionButton(name, selected, enabled) end

---@param side  "Player" | "Enemy"
---@param state Source.Windows.WindowBattle.BattlerState
function Window:refreshBreath(side, state) end

function Window:refreshCritical() end

function Window:refreshLocale() end

function Window:requestAttackSkill() end

function Window:requestCritical() end

function Window:requestDefenseSkill() end

function Window:requestRetreat() end

---@param delay  number
---@param action fun()
function Window:schedule(delay, action) end

---@param name string
---@param text string
function Window:setBattleText(name, text) end

---@param name  string
---@param actor Engine.Actor
function Window:setPortrait(name, actor) end

---@param state  Source.Windows.WindowBattle.BattlerState
---@param units? integer
---@return integer
function Window:skillBreathCost(state, units) end

return Window
