-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowShopItem

---@brief Two-column shop item list.
---@class Source.Windows.WindowShopItem: Source.Windows.Base.WindowSelectable, Source.UIBase.Ui.Window
---@field ui Source.UI.Parts.WindowShop.WindowShopItem
local Window = {}

---@brief Construct the shop item list.
---
--- - @param owner The shop coordinator.
---@param owner Source.Windows.WindowShop
---@return Source.Windows.WindowShopItem
function Window.new(owner) end

---@brief Construct the shop item list.
---
--- - @param owner The shop coordinator.
---@param owner Source.Windows.WindowShop
---@param ui    Source.UI.Parts.WindowShop.WindowShopItem
---@return Source.Windows.WindowShopItem
function Window.FromView(ui, owner) end

function Window:confirmItem() end

function Window:dispose() end

---@return string | nil
function Window:getCurrentItemID() end

---@return boolean
function Window:isCurrentAvailable() end

---@param kwargs Engine.UiInputEventArguments
function Window:onKeyDown(kwargs) end

function Window:onReturn() end

---@param deltaTime number
function Window:onTick(deltaTime) end

---@brief Rebuild the displayed shop item list.
---
--- - @param itemIDs Ordered item IDs to display.
--- - @param availableMap Item availability by ID.
--- - @param valueMap Right-side numeric value by ID.
--- - @param showValues Whether right-side values are visible.
---@param itemIDs      table
---@param availableMap table
---@param valueMap     table
---@param showValues   boolean
function Window:refreshItems(itemIDs, availableMap, valueMap, showValues) end

function Window:resetSelection() end

return Window
