-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowEnemyEncyclopedia

---@class Source.Windows.WindowEnemyEncyclopedia: Source.Windows.Base.WindowBase, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowEnemyEncyclopedia
local Window = {}

---@brief Construct the enemy encyclopedia window.
---
--- - @param onClose Optional callback invoked when the window closes.
---@param onClose function | nil
---@return Source.Windows.WindowEnemyEncyclopedia
function Window.new(onClose) end

---@brief Construct the enemy encyclopedia window.
---
--- - @param onClose Optional callback invoked when the window closes.
---@param onClose function | nil
---@param ui      Source.UI.WindowEnemyEncyclopedia
---@return Source.Windows.WindowEnemyEncyclopedia
function Window.FromView(ui, onClose) end

---@param label string
---@param value string
function Window:addInfoPair(label, value) end

---@param entry Source.Windows.WindowEnemyBook.Entry
function Window:buildInfo(entry) end

---@param entry Source.Windows.WindowEnemyBook.Entry
---@param y     number
function Window:buildSpecials(entry, y) end

function Window:clearEnemyControls() end

---@brief Close the enemy encyclopedia window.
function Window:close() end

---@brief Close on confirm or cancel.
---
--- - @param kwargs Event data.
---@param kwargs Engine.UiInputEventArguments
function Window:onKeyDown(kwargs) end

---@brief Close on right click.
---@param kwargs Engine.UiInputEventArguments
---@return boolean
function Window:onMouseButtonDown(kwargs) end

---@brief Close the enemy detail through its cancel path.
function Window:onReturn() end

---@brief Open the detail window for an enemy-book entry.
---
--- - @param entry Prepared enemy display data.
---@param entry Source.Windows.WindowEnemyBook.Entry
function Window:open(entry) end

function Window:refresh() end

---@brief Refresh localised detail text without resetting the portrait animation or window focus.
function Window:refreshLocale() end

return Window
