-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowCommand

---@class Source.Windows.WindowCommand: Source.Windows.Base.WindowSelectable, Source.UIBase.Ui.Window
---@field ui Source.UI.Parts.Title.CommandWindow
local Window = {}

---@brief Bind the title's authored command rows to their confirmation callbacks.
---@param commands Source.UIBase.CommandRow.Controller.Model[]
---@return Source.Windows.WindowCommand
function Window.new(commands) end

---@brief Bind the title's authored command rows to their confirmation callbacks.
---@param commands Source.UIBase.CommandRow.Controller.Model[]
---@param ui       Source.UI.Parts.Title.CommandWindow
---@return Source.Windows.WindowCommand
function Window.FromView(ui, commands) end

function Window:refresh() end

function Window:refreshRows() end

return Window
