-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowBattle

---@class Source.Windows.WindowBattle: Source.Windows.Base.WindowBase, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowBattle
local Window = {}

---@param scene Source.Gameplay.GameplayScene
---@return Source.Windows.WindowBattle
function Window.new(scene) end

---@param scene Source.Gameplay.GameplayScene
---@param ui    Source.UI.WindowBattle
---@return Source.Windows.WindowBattle
function Window.FromView(ui, scene) end

---@param state  Source.Windows.WindowBattle.BattlerState
---@param amount integer
function Window:addBreath(state, amount) end

---@param playerTurn boolean
function Window:beginTurn(playerTurn) end

function Window:bind() end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
---@param critical boolean
---@return integer damage
---@return integer base
function Window:calculateDamage(attacker, defender, critical) end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
---@return boolean
function Window:canCritical(attacker, defender) end

function Window:cancel() end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
function Window:criticalAttack(attacker, defender) end

function Window:dispose() end

---@param result Source.Windows.WindowBattle.Result
function Window:finish(result) end

---@param kind  "Lit" | "Dim"
---@param index integer
---@return Engine.Canvas
function Window:getBreathCanvas(kind, index) end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
function Window:normalAttack(attacker, defender) end

---@param state Source.Windows.WindowBattle.BattlerState
---@param side  "Player" | "Enemy"
function Window:observeState(state, side) end

---@param kwargs Engine.UiInputEventArguments
function Window:onKeyDown(kwargs) end

---@param player     Source.Player.Player
---@param enemy      Source.Enemy
---@param onFinished Source.Windows.WindowBattle.Finished
function Window:open(player, enemy, onFinished) end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
---@param critical boolean
function Window:performAttack(attacker, defender, critical) end

function Window:playBreathAnimation() end

---@param attacker Source.Windows.WindowBattle.BattlerState
---@param defender Source.Windows.WindowBattle.BattlerState
---@param damage   integer
---@param critical boolean
function Window:receiveAttack(attacker, defender, damage, critical) end

function Window:refresh() end

---@param side  "Player" | "Enemy"
---@param state Source.Windows.WindowBattle.BattlerState
function Window:refreshBreath(side, state) end

function Window:refreshCritical() end

function Window:refreshLocale() end

function Window:requestCritical() end

function Window:requestRetreat() end

---@param delay  number
---@param action fun()
function Window:schedule(delay, action) end

---@param name string
---@param text string
function Window:setBattleText(name, text) end

---@param name  string
---@param actor Engine.Actor
function Window:setPortrait(name, actor) end

return Window
