-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowEquip

---@class Source.Windows.WindowEquip: Engine.Canvas, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowEquip
local Window = {}

---@param player Source.Player.Player
---@return Source.Windows.WindowEquip
function Window.new(player) end

---@param player Source.Player.Player
---@param ui     Source.UI.WindowEquip
---@return Source.Windows.WindowEquip
function Window.FromView(ui, player) end

---@param onHidden function | nil
function Window:close(onHidden) end

function Window:dispose() end

---@return Source.Windows.WindowEquipSlot, Source.Windows.WindowEquipSelect
function Window:getFocusControls() end

---@return Source.Windows.WindowEquipSlot
function Window:getSlotFocusTarget() end

---@return boolean
function Window:getVisible() end

function Window:hideImmediate() end

function Window:open() end

function Window:refreshLocale() end

function Window:requestSlotFocus() end

---@return boolean
function Window:returnSelectToSlot() end

---@param callback function | nil
function Window:setOnCloseCallback(callback) end

---@param player Source.Player.Player
function Window:setPlayer(player) end

return Window
