-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowSaveLoad

---@brief Integrated save/load UI: tabs, slot list, and detail panel.
---
--- Owner-agnostic coordinator. Hosts pass callbacks for close and load events
--- instead of being referenced directly, so the same UI can serve the in-game
--- menu, the title screen, or any other entry point.
---@class Source.Windows.WindowSaveLoad: Engine.Canvas, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowSaveLoad
local Window = {}

---@brief Construct the save/load UI coordinator and child windows.
---
--- - @param loadOnly When True, tabs are omitted and the slot list remains in load mode.
--- - @param getSaveSource Callable returning the GameInstance to persist when saving.
--- - @param onClose Callback invoked after the UI closes, with the close reason.
--- - @param onLoaded Callback invoked with the loaded GameInstance after a successful load.
---@param loadOnly      boolean | nil
---@param getSaveSource function | nil
---@param onClose       function | nil
---@param onLoaded      function | nil
---@return Source.Windows.WindowSaveLoad
function Window.new(loadOnly, getSaveSource, onClose, onLoaded) end

---@brief Construct the save/load UI coordinator and child windows.
---
--- - @param loadOnly When True, tabs are omitted and the slot list remains in load mode.
--- - @param getSaveSource Callable returning the GameInstance to persist when saving.
--- - @param onClose Callback invoked after the UI closes, with the close reason.
--- - @param onLoaded Callback invoked with the loaded GameInstance after a successful load.
---@param loadOnly      boolean | nil
---@param getSaveSource function | nil
---@param onClose       function | nil
---@param onLoaded      function | nil
---@param ui            Source.UI.WindowSaveLoad
---@return Source.Windows.WindowSaveLoad
function Window.FromView(ui, loadOnly, getSaveSource, onClose, onLoaded) end

---@brief Close the save/load UI and deactivate all child windows.
---@param onHidden function | nil
function Window:close(onHidden) end

---@brief Close the save/load UI via cancel and notify the host.
function Window:closeByCancel() end

---@brief Release tab callbacks, UI subscriptions, and host callbacks.
function Window:dispose() end

---@brief Get the save detail panel window.
---
--- - @return The detail panel instance.
---@return Source.Windows.WindowSaveDetail
function Window:getDetailWindow() end

---@brief Get the save slot list window.
---
--- - @return The slot list window instance.
---@return Source.Windows.WindowSaveSlot
function Window:getSlotWindow() end

---@brief Get the load/save tab window.
---
--- - @return The tab window instance, or nil when running in load-only mode.
---@return Source.Windows.WindowSaveTabs | nil
function Window:getTabWindow() end

---@brief Get the visibility of the save/load UI.
---
--- - @return Whether the slot list is visible (treated as the canonical state).
---@return boolean
function Window:getVisible() end

---@brief Delegate Q/E and LB/RB navigation to the tab view when present.
---@return boolean
function Window:handleTabNavigationInput() end

---@brief Notify the coordinator that the slot list cursor index may have changed.
---
--- - @param index The current zero-based slot index, or ``nil`` if no selection.
---@param index integer | nil
function Window:notifySlotIndexMaybeChanged(index) end

---@brief Handle slot confirmation for saving or loading.
---
--- - @param slot Zero-based slot index selected by the player.
---@param slot integer
function Window:onSlotConfirm(slot) end

---@brief Apply a zero-based tab selection without changing slot cursor or scroll state.
---@param index integer
function Window:onTabSelected(index) end

---@brief Open the save/load UI in Load mode with the slot list focused.
---
--- Selects the latest existing save, or the first slot when none exists.
---@param transitionProfile string | nil
function Window:open(transitionProfile) end

---@brief Set the visibility of all save/load child windows.
---
--- - @param visible Whether to show or hide the windows.
---@param visible boolean
function Window:setVisible(visible) end

return Window
