-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowItem

---
--- Shows player inventory items in a grid with icons and counts.
--- Uses WindowSelectable for keyboard/mouse navigation.
---@class Source.Windows.WindowItem: Source.Windows.Base.WindowSelectable, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowItem
local Window = {}

---@brief Construct the item window.
---
--- - @param player The player instance with inventory.
--- - @param onClose Optional callback invoked when the window is closed.
---@param player  Source.Player.Player
---@param onClose function | nil
---@return Source.Windows.WindowItem
function Window.new(player, onClose) end

---@brief Construct the item window.
---
--- - @param player The player instance with inventory.
--- - @param onClose Optional callback invoked when the window is closed.
---@param player  Source.Player.Player
---@param onClose function | nil
---@param ui      Source.UI.WindowItem
---@return Source.Windows.WindowItem
function Window.FromView(ui, player, onClose) end

---@brief Close the item window.
---@param onHidden function | nil
function Window:close(onHidden) end

function Window:closeByCancel() end

---@return Source.Player.Player
function Window:getPlayer() end

function Window:notifyClosed() end

function Window:onItemUsed() end

---@brief Close the item window through its cancel path.
function Window:onReturn() end

---@brief Update item window and render item cells.
---
--- - @param deltaTime Elapsed time in seconds.
---@param deltaTime number
function Window:onTick(deltaTime) end

---@brief Open the item window, refreshing inventory and selecting its first item.
function Window:open() end

function Window:refresh() end

function Window:refreshItems() end

---@brief Refresh the currently selected item's localised name and description.
function Window:refreshLocale() end

---@param callback function | nil
function Window:setOnCloseCallback(callback) end

---@param callback function | nil
function Window:setOnUseCallback(callback) end

---@brief Rebind the player whose inventory is displayed.
---@param player Source.Player.Player
function Window:setPlayer(player) end

function Window:tick() end

function Window:updateDescription() end

function Window:useSelectedItem() end

---@param text string
---@return string
function Window:wrapDescription(text) end

return Window
