-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowEnemyBook

---@class Source.Windows.WindowEnemyBook: Source.Windows.Base.WindowSelectable, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowEnemyBook
local Window = {}

---@brief Construct the enemy handbook window.
---
--- - @param player Player used to calculate displayed damage.
--- - @param onClose Optional callback invoked when the window closes.
--- - @param onConfirm Optional callback invoked when an enemy is confirmed.
---@param player    Source.Player.Player
---@param onClose   function | nil
---@param onConfirm function | nil
---@return Source.Windows.WindowEnemyBook
function Window.new(player, onClose, onConfirm) end

---@brief Construct the enemy handbook window.
---
--- - @param player Player used to calculate displayed damage.
--- - @param onClose Optional callback invoked when the window closes.
--- - @param onConfirm Optional callback invoked when an enemy is confirmed.
---@param player    Source.Player.Player
---@param onClose   function | nil
---@param onConfirm function | nil
---@param ui        Source.UI.WindowEnemyBook
---@return Source.Windows.WindowEnemyBook
function Window.FromView(ui, player, onClose, onConfirm) end

---@param text string | nil
---@return string
function Window.FormatLocaleText(text) end

---@param entry Source.Windows.WindowEnemyBook.Entry
function Window.RefreshEntryLocale(entry) end

---@param enemy  Source.Enemy
---@param visual Global.Utils.Render.ActorVisual | nil
---@return Source.Windows.WindowEnemyBook.Entry
function Window:buildEntry(enemy, visual) end

---@param special table
---@return Source.Windows.WindowEnemyBook.SpecialDetail[]
function Window:buildSpecialDetails(special) end

---@param special table
---@return Source.Windows.WindowEnemyBook.SpecialDisplay[]
function Window:buildSpecialDisplays(special) end

---@brief Close the handbook.
---@param onHidden function | nil
function Window:close(onHidden) end

---@param entry Source.Windows.WindowEnemyBook.Entry
function Window:confirmEnemy(entry) end

---@param name string
---@return string
function Window:formatName(name) end

---@param text string | nil
---@return string
function Window:formatText(text) end

---@return integer
function Window:getItemWidth() end

---@return Source.Player.Player
function Window:getPlayer() end

---@brief Close the handbook through its cancel path.
function Window:onReturn() end

---@brief Open the handbook, rescan current-map enemies, and select the first entry.
---
--- - @param gameMap Current map to scan.
---@param gameMap GameMap | nil
function Window:open(gameMap) end

---@param gameMap GameMap | nil
function Window:refreshEnemies(gameMap) end

---@brief Refresh localised enemy, stat, and special text without rebuilding rows or previews.
function Window:refreshLocale() end

---@brief Rebind the player used for damage preview.
---
--- - @param player The current player instance.
---@param player Source.Player.Player
function Window:setPlayer(player) end

return Window
