-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Sensor.Type
local enum = {
    Accelerometer = (0 --[[@as sf.Sensor.Type]]),
    Gravity = (3 --[[@as sf.Sensor.Type]]),
    Gyroscope = (1 --[[@as sf.Sensor.Type]]),
    Magnetometer = (2 --[[@as sf.Sensor.Type]]),
    Orientation = (5 --[[@as sf.Sensor.Type]]),
    UserAcceleration = (4 --[[@as sf.Sensor.Type]]),
}

return enum
