-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow

---@class Source.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field Description Engine.PlainText
---@field Name        Engine.PlainText
---@field Root        Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow

---@class Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
