-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.HUDPlayerAttr

---
--- Shows the player's avatar, current map name, level, states, HP bar with value, stat values, and breath slots.
---@class Source.Windows.PlayerAttrHUD: Engine.Canvas, Internal.UIBase.Ui.Window
---@field ui Internal.UI.PlayerAttrHUD
local Window = {}

--- Construct the party HUD with menu and player-switch callbacks.
---@param inst                 Source.GameInstance.GameInstance
---@param openMenuCallback     function | nil
---@param switchPlayerCallback fun(right: boolean): boolean | nil
---@return Source.Windows.PlayerAttrHUD
function Window.new(inst, openMenuCallback, switchPlayerCallback) end

--- Construct the party HUD with menu and player-switch callbacks.
---@param inst                 Source.GameInstance.GameInstance
---@param openMenuCallback     function | nil
---@param switchPlayerCallback fun(right: boolean): boolean | nil
---@param ui                   Internal.UI.PlayerAttrHUD
---@return Source.Windows.PlayerAttrHUD
function Window.FromView(ui, inst, openMenuCallback, switchPlayerCallback) end

function Window:bind() end

function Window:dispose() end

---@param kind "Lit" | "Dim"
---@return Engine.WrapBox
function Window:getBreathBox(kind) end

---@param kind  "Lit" | "Dim"
---@param index integer
---@return Engine.Canvas
function Window:getBreathCanvas(kind, index) end

---@return Source.MapActors.Player.Player
function Window:getPlayer() end

--- Advance the breath-slot animation clock and replay the loop when it elapses.
---
--- - @param deltaTime  Elapsed frame time in seconds
---@param deltaTime number
function Window:onTick(deltaTime) end

function Window:openMenu() end

function Window:playBreathAnimation() end

function Window:refresh() end

function Window:refreshAvatars() end

function Window:refreshBreath() end

--- Ignore Ability System and player events from other battlers, then refresh the HUD.
---
--- - @param payload EventBus payload. Locale events have no owner; player and ability events include `owner`.
---@param payload Source.Configs.EventChangePayload | { language: string } | nil
function Window:refreshFromEvent(payload) end

---@param language string | nil
---@return boolean
function Window:refreshStates(language) end

--- Rebind the party and its primary player, including after loading a save.
---@param inst Source.GameInstance.GameInstance
function Window:setInstance(inst) end

return Window
