-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.HUDPlayerAttr

---
--- Shows the player's avatar, current map name, level, states, HP bar with value, stat values, and breath slots.
---@class Source.Windows.PlayerAttrHUD: Engine.Canvas, Internal.UIBase.Ui.Window
---@field ui Internal.UI.PlayerAttrHUD
local Window = {}

--- Construct a player attribute HUD bound to the given player instance.
---
--- - @param player  Target player whose attributes are displayed on this HUD
--- - @param openMenuCallback Callback invoked when the player avatar is clicked
---@param player           Source.MapActors.Player.Player
---@param openMenuCallback function | nil
---@return Source.Windows.PlayerAttrHUD
function Window.new(player, openMenuCallback) end

--- Construct a player attribute HUD bound to the given player instance.
---
--- - @param player  Target player whose attributes are displayed on this HUD
--- - @param openMenuCallback Callback invoked when the player avatar is clicked
---@param player           Source.MapActors.Player.Player
---@param openMenuCallback function | nil
---@param ui               Internal.UI.PlayerAttrHUD
---@return Source.Windows.PlayerAttrHUD
function Window.FromView(ui, player, openMenuCallback) end

function Window:bind() end

function Window:dispose() end

---@param kind "Lit" | "Dim"
---@return Engine.WrapBox
function Window:getBreathBox(kind) end

---@param kind  "Lit" | "Dim"
---@param index integer
---@return Engine.Canvas
function Window:getBreathCanvas(kind, index) end

---@return Source.MapActors.Player.Player
function Window:getPlayer() end

--- Advance the breath-slot animation clock and replay the loop when it elapses.
---
--- - @param deltaTime  Elapsed frame time in seconds
---@param deltaTime number
function Window:onTick(deltaTime) end

function Window:openMenu() end

function Window:playBreathAnimation() end

function Window:refresh() end

function Window:refreshBreath() end

--- Ignore Ability System and player events from other battlers, then refresh the HUD.
---
--- - @param payload EventBus payload. Locale events have no owner; player and ability events include `owner`.
---@param payload Source.Configs.EventKeys.ChangePayload | { language: string } | nil
function Window:refreshFromEvent(payload) end

---@param language string | nil
---@return boolean
function Window:refreshStates(language) end

--- Rebind the player whose values are displayed by this HUD.
---
--- - @param player Target player.
---@param player Source.MapActors.Player.Player
function Window:setPlayer(player) end

return Window
