-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowHotkeys

---@class Source.Windows.WindowHotkeys: Engine.Canvas, Internal.UIBase.Ui.Window
---@field ui      Internal.UI.WindowHotkeys
---@field ENTRIES string[]
local Window = {}

---@param onClose fun()
---@return Source.Windows.WindowHotkeys
function Window.new(onClose) end

---@param onClose fun()
---@param ui      Internal.UI.WindowHotkeys
---@return Source.Windows.WindowHotkeys
function Window.FromView(ui, onClose) end

function Window:close() end

---@param kwargs Engine.UiInputEventArguments
function Window:onKeyDown(kwargs) end

---@param kwargs Engine.UiInputEventArguments
---@return boolean
function Window:onMouseButtonDown(kwargs) end

function Window:onReturn() end

---@param mapRect sf.IntRect
function Window:open(mapRect) end

function Window:refreshLocale() end

return Window
