-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowShopDetail

---@class Source.Windows.WindowShopDetail: Internal.UIBase.WindowBase, Internal.UIBase.Ui.Window
---@field ui Internal.UI.Parts.WindowShop.WindowShopDetail
local Window = {}

---@return Source.Windows.WindowShopDetail
function Window.new() end

---@param ui Internal.UI.Parts.WindowShop.WindowShopDetail
---@return Source.Windows.WindowShopDetail
function Window.FromView(ui) end

function Window:refresh() end

---@param itemInfo Source.Data.GeneralItemData | nil
---@param price    integer | nil
function Window:setItem(itemInfo, price) end

return Window
