-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowShopTabs

---@class Source.Windows.WindowShopTabs: Internal.UIBase.WindowBase, Internal.UIBase.Ui.Window
---@field ui Internal.UI.Parts.WindowShop.WindowShopTabs
local Window = {}

---@param owner Source.Windows.WindowShop
---@return Source.Windows.WindowShopTabs
function Window.new(owner) end

---@param owner Source.Windows.WindowShop
---@param ui    Internal.UI.Parts.WindowShop.WindowShopTabs
---@return Source.Windows.WindowShopTabs
function Window.FromView(ui, owner) end

function Window:bind() end

function Window:dispose() end

---@return boolean
function Window:handleNavigationInput() end

---@param index integer
function Window:onSelectedIndexChanged(index) end

function Window:refresh() end

return Window
