-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowTutorial

---@class Source.Windows.WindowTutorial: Engine.Canvas, Internal.UIBase.Ui.Window
---@field ui              Internal.UI.WindowTutorial
---@field SHRINK_DURATION number
local Window = {}

---@return Source.Windows.WindowTutorial
function Window.new() end

---@param ui Internal.UI.WindowTutorial
---@return Source.Windows.WindowTutorial
function Window.FromView(ui) end

--- Immediately hide the tutorial and release only its own input capture.
function Window:close() end

function Window:dispose() end

---@return boolean
function Window:isFinished() end

---@param deltaTime number
function Window:onTick(deltaTime) end

--- Start a 0.25-second contraction. All input stays captured until confirmation or close.
---@param rect sf.IntRect
---@param text string
function Window:open(rect, text) end

--- Replace already-localised text and reposition it without restarting the tutorial.
---@param text string
function Window:refreshText(text) end

return Window
