-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.Engine.ActionKind
local enum = {
    JoystickAxis = (5 --[[@as Engine.ActionKind]]),
    JoystickButton = (4 --[[@as Engine.ActionKind]]),
    Key = (1 --[[@as Engine.ActionKind]]),
    KeyOrScan = (0 --[[@as Engine.ActionKind]]),
    MouseButton = (3 --[[@as Engine.ActionKind]]),
    Scan = (2 --[[@as Engine.ActionKind]]),
    TouchTap = (6 --[[@as Engine.ActionKind]]),
}

return enum
