-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Text.ClusterGrouping

---@class Enums.sf.Text.ClusterGrouping
---@field Character sf.Text.ClusterGrouping
---@field Grapheme sf.Text.ClusterGrouping
---@field None sf.Text.ClusterGrouping
---@type Enums.sf.Text.ClusterGrouping
local enum = {}

return enum
