-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Text.LineAlignment

---@class Enums.sf.Text.LineAlignment
---@field Center sf.Text.LineAlignment
---@field Default sf.Text.LineAlignment
---@field Left sf.Text.LineAlignment
---@field Right sf.Text.LineAlignment
---@type Enums.sf.Text.LineAlignment
local enum = {}

return enum
