-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.Engine.Direction

---@class Enums.Engine.Direction
---@field DOWN integer
---@field LEFT integer
---@field RIGHT integer
---@field UP integer
---@type Enums.Engine.Direction
local enum = {}

return enum
