-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.Engine.ImageDrawAs

---@class Enums.Engine.ImageDrawAs
---@field Image Engine.ImageDrawAs
---@field Tile Engine.ImageDrawAs
---@type Enums.Engine.ImageDrawAs
local enum = {}

return enum
