---@meta Enums.GeneralData.State
--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

---@enum Enums.GeneralData.State
local State = {
    Poisoned = "Poisoned",
    Weak = "Weak",
}

return State
