-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.PlayerAttrHUD.PlayerStateRow
local View = {}

View.assetKey = "Parts/PlayerAttrHUD/PlayerStateRow"
View.designSize = sf.Vector2f.new(128, 24)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Icon = assert(self.instance:requireControl("Icon")),
        Root = assert(self.instance:requireControl("Root")),
        StateName = assert(self.instance:requireControl("StateName"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.PlayerAttrHUD.PlayerStateRow
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.PlayerAttrHUD.PlayerStateRow
    self.assets = assets
end

return class(View, UiView)
