-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")
local ChildView3 = require("Internal.UI.Parts.WindowSaveLoad.WindowSaveSlotRow")

---@class Internal.UI.Parts.WindowSaveLoad.WindowSaveSlot
local View = {}

View.assetKey = "Parts/WindowSaveLoad/WindowSaveSlot"
View.designSize = sf.Vector2f.new(160, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        SlotList = assert(self.instance:requireControl("SlotList")),
        SlotScrollBox = assert(self.instance:requireControl("SlotScrollBox")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveSlot
    self.controls = controls
    local assets = {
        SaveSlotPlaceholder1 = self:own(ChildView3.new(assert(self.instance:requireAsset("SaveSlotPlaceholder1")))),
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveSlot
    self.assets = assets
end

return class(View, UiView)
