-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")

---@class Internal.UI.Parts.WindowSaveLoad.WindowSaveDetail
local View = {}

View.assetKey = "Parts/WindowSaveLoad/WindowSaveDetail"
View.designSize = sf.Vector2f.new(256, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        Thumbnail = assert(self.instance:requireControl("Thumbnail")),
        ThumbnailArea = assert(self.instance:requireControl("ThumbnailArea")),
        TimestampText = assert(self.instance:requireControl("TimestampText")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveDetail
    self.controls = controls
    local assets = {
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveDetail
    self.assets = assets
end

return class(View, UiView)
