-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Shader.Type

---@class Enums.sf.Shader.Type
---@field Fragment sf.Shader.Type
---@field Geometry sf.Shader.Type
---@field Vertex sf.Shader.Type
---@type Enums.sf.Shader.Type
local enum = {}

return enum
