-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Cursor.Type
local enum = {
    Arrow = (0 --[[@as sf.Cursor.Type]]),
    ArrowWait = (1 --[[@as sf.Cursor.Type]]),
    Cross = (18 --[[@as sf.Cursor.Type]]),
    Hand = (4 --[[@as sf.Cursor.Type]]),
    Help = (19 --[[@as sf.Cursor.Type]]),
    NotAllowed = (20 --[[@as sf.Cursor.Type]]),
    SizeAll = (17 --[[@as sf.Cursor.Type]]),
    SizeBottom = (12 --[[@as sf.Cursor.Type]]),
    SizeBottomLeft = (15 --[[@as sf.Cursor.Type]]),
    SizeBottomLeftTopRight = (8 --[[@as sf.Cursor.Type]]),
    SizeBottomRight = (14 --[[@as sf.Cursor.Type]]),
    SizeHorizontal = (5 --[[@as sf.Cursor.Type]]),
    SizeLeft = (9 --[[@as sf.Cursor.Type]]),
    SizeRight = (10 --[[@as sf.Cursor.Type]]),
    SizeTop = (11 --[[@as sf.Cursor.Type]]),
    SizeTopLeft = (13 --[[@as sf.Cursor.Type]]),
    SizeTopLeftBottomRight = (7 --[[@as sf.Cursor.Type]]),
    SizeTopRight = (16 --[[@as sf.Cursor.Type]]),
    SizeVertical = (6 --[[@as sf.Cursor.Type]]),
    Text = (3 --[[@as sf.Cursor.Type]]),
    Wait = (2 --[[@as sf.Cursor.Type]]),
}

return enum
