-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.IpAddress.Type
local enum = {
    IpV4 = (0 --[[@as sf.IpAddress.Type]]),
    IpV6 = (1 --[[@as sf.IpAddress.Type]]),
}

return enum
