-- AUTO-GENERATED by Ludork Core bindgen. DO NOT EDIT.
---@meta GlobalFunctions

---@class GlobalFunctionsModule
---@field Components table
---@field Manager table
---@field NodeGraph table
---@field UI table
---@type GlobalFunctionsModule
GlobalFunctions = {}

GlobalFunctions.Components = {}
GlobalFunctions.Manager = {}
GlobalFunctions.NodeGraph = {}
GlobalFunctions.UI = {}

---@param value any
---@param valueType? any
---@param declaringModule? any
---@return any
function GlobalFunctions.Components._cloneComponentValue(value, valueType, declaringModule) end

---@param componentType any
---@param fieldName string
---@param value any
---@return any
function GlobalFunctions.Components._cloneComponentFieldValue(componentType, fieldName, value) end

---@param value any
---@return boolean
function GlobalFunctions.Components.isComponentType(value) end

---@param classValue any
---@return table<string, any>
function GlobalFunctions.Components.getComponentTypes(classValue) end

---@param componentType any
---@return table<string, any>
function GlobalFunctions.Components.getComponentFieldDefaults(componentType) end

---@param classValue any
---@return table<string, string>
function GlobalFunctions.Components.getComponentFieldMap(classValue) end

---@param componentType any
---@param data any
---@return any
function GlobalFunctions.Components.componentFromData(componentType, data) end

---@param value any
---@return table<string, any>
function GlobalFunctions.Components.componentToData(value) end

---@param object any
---@param fieldName string
---@return any, string|nil, any
function GlobalFunctions.Components._getComponentFieldTarget(object, fieldName) end

---@param object any
---@param fieldName string
---@param defaultValue? any
---@return any
function GlobalFunctions.Components.getComponentFieldValue(object, fieldName, defaultValue) end

---@param object any
---@param fieldName string
---@param value any
---@return boolean
function GlobalFunctions.Components.setComponentFieldValue(object, fieldName, value) end

---@param value any
---@return boolean
function GlobalFunctions.Components._isBlankValue(value) end

---@param object any
---@return nil
function GlobalFunctions.Components._mergeComponentDefaults(object) end

---@param object any
---@return nil
function GlobalFunctions.Components.normaliseInstanceComponents(object) end

---@param object any
---@return any[]
function GlobalFunctions.Components.attachInstanceComponents(object) end

---@param filePath string
---@return sf.SoundBuffer|nil
function GlobalFunctions.Manager.getSoundBuffer(filePath) end

---@param filename string
---@param filter? Engine.SoundFilter
---@return sf.Sound|nil
function GlobalFunctions.Manager.playSE(filename, filter) end

---@param filename string
---@param filter? Engine.SoundFilter
---@param refActor? sf.Transformable|nil
---@param minDistance? number
---@return sf.Sound|nil
function GlobalFunctions.Manager.playVoice(filename, filter, refActor, minDistance) end

---@param musicType string
---@param filename string
---@param filter? Engine.MusicFilter
---@return sf.Music|nil
function GlobalFunctions.Manager.playMusic(musicType, filename, filter) end

---@return nil
function GlobalFunctions.Manager.stopSound() end

---@return nil
function GlobalFunctions.Manager.stopVoice() end

---@param musicType string
---@return nil
function GlobalFunctions.Manager.stopMusic(musicType) end

---@param filename string
---@return sf.Font|nil
function GlobalFunctions.Manager.loadFont(filename) end

---@param fontName string
---@return sf.Font|nil
function GlobalFunctions.Manager.getFont(fontName) end

---@param fontName string
---@return string
function GlobalFunctions.Manager.getFontFilename(fontName) end

---@return string[]
function GlobalFunctions.Manager.getFontList() end

---@return string[]
function GlobalFunctions.Manager.getFontFilenameList() end

---@param fontName string
---@return boolean
function GlobalFunctions.Manager.hasFont(fontName) end

---@param subFolder string
---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadTexture(subFolder, filename, sRGB, area, smooth) end

---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadBlock(filename, sRGB, area, smooth) end

---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadCharacter(filename, sRGB, area, smooth) end

---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadSystem(filename, sRGB, area, smooth) end

---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadTileset(filename, sRGB, area, smooth) end

---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadAutotile(filename, sRGB, area, smooth) end

---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadFog(filename, sRGB, area, smooth) end

---@param filename string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function GlobalFunctions.Manager.loadTransition(filename, sRGB, area, smooth) end

---@param shaderPath string
---@param shaderType? sf.Shader.Type|nil
---@return sf.Shader|nil
function GlobalFunctions.Manager.loadShader(shaderPath, shaderType) end

---@param vertPath string
---@param geoPath string
---@param fragPath string
---@return sf.Shader|nil
function GlobalFunctions.Manager.loadFullShaderWithGeo(vertPath, geoPath, fragPath) end

---@param vertPath string
---@param geoPath string
---@param fragPath string
---@return sf.Shader|nil
function GlobalFunctions.Manager.loadGeoShader(vertPath, geoPath, fragPath) end

---@return nil
function GlobalFunctions.NodeGraph.initLatent() end

--- @brief Convert a hexadecimal color string to `sf::Color`
---
--- Supported input forms are `#RRGGBB`, `$RRGGBB`, `0xRRGGBB`
--- and `RRGGBBAA`.
---
--- - @param value Hexadecimal color string
--- - @param alpha Alpha value used when the string does not contain alpha
---
--- - @return Parsed color value
---
---@param value string
---@param alpha? integer
---@return sf.Color
function GlobalFunctions.UI.HexColor(value, alpha) end

--- @brief Convert an integer color value to `sf::Color`
---
--- The low 24 bits are interpreted as RGB. The high 8 bits
--- are used as alpha when non-zero, otherwise `alpha` is used.
---
--- - @param value Packed integer color value
--- - @param alpha Fallback alpha value
---
--- - @return Parsed color value
---
---@param value integer
---@param alpha? integer
---@return sf.Color
function GlobalFunctions.UI.HexColor(value, alpha) end

---@return sf.Color
function GlobalFunctions.UI.GetRosyBrown() end

---@return sf.Color
function GlobalFunctions.UI.GetCopper() end

---@return sf.Color
function GlobalFunctions.UI.GetSage() end

---@return sf.Color
function GlobalFunctions.UI.GetTeal() end

---@return sf.Color
function GlobalFunctions.UI.GetMutedPurple() end

---@return sf.Color
function GlobalFunctions.UI.GetTaupe() end

---@return sf.Color
function GlobalFunctions.UI.GetTerraCotta() end

---@return sf.Color
function GlobalFunctions.UI.GetOchre() end

---@return sf.Color
function GlobalFunctions.UI.GetFernGreen() end

---@return sf.Color
function GlobalFunctions.UI.GetSteelBlue() end

---@return sf.Color
function GlobalFunctions.UI.GetDimGrey() end

---@return sf.Color
function GlobalFunctions.UI.GetCharcoal() end

return GlobalFunctions
