-- AUTO-GENERATED by Ludork Core bindgen. DO NOT EDIT.
---@meta GlobalCore

---@alias SceneRuntime GlobalCore.SceneBase

---@class GlobalCore.WeatherType
---@field NONE GlobalCore.WeatherType
---@field RAIN GlobalCore.WeatherType
---@field STORM GlobalCore.WeatherType
---@field SNOW GlobalCore.WeatherType

---@class GlobalCore.WorldRegionState
---@field Unloaded GlobalCore.WorldRegionState
---@field Reading GlobalCore.WorldRegionState
---@field Prepared GlobalCore.WorldRegionState
---@field Active GlobalCore.WorldRegionState
---@field Dormant GlobalCore.WorldRegionState

---@class GlobalCore.WorldRegionDemand
---@field None GlobalCore.WorldRegionDemand
---@field Prepared GlobalCore.WorldRegionDemand
---@field Active GlobalCore.WorldRegionDemand

---@class GlobalCoreModule
---@field Animation GlobalCore.Animation
---@field AnimationPlayingSound GlobalCore.AnimationPlayingSound
---@field Camera GlobalCore.Camera
---@field CommonTipController GlobalCore.CommonTipController
---@field FocusGroup GlobalCore.FocusGroup
---@field FocusManager GlobalCore.FocusManager
---@field FocusNeighbor GlobalCore.FocusNeighbor
---@field FocusTransition GlobalCore.FocusTransition
---@field FogController GlobalCore.FogController
---@field MapFogSettings GlobalCore.MapFogSettings
---@field GameMapBase GlobalCore.GameMapBase
---@field PathResult GlobalCore.PathResult
---@field GameMapRenderer GlobalCore.GameMapRenderer
---@field AbilitySystemComponent GlobalCore.AbilitySystemComponent
---@field ActiveGameplayEffect GlobalCore.ActiveGameplayEffect
---@field AttributeSet GlobalCore.AttributeSet
---@field AttributeSchema GlobalCore.AttributeSchema
---@field GameplayAbility GlobalCore.GameplayAbility
---@field GameplayAbilityResult GlobalCore.GameplayAbilityResult
---@field GameplayAbilitySpec GlobalCore.GameplayAbilitySpec
---@field GameplayEffect GlobalCore.GameplayEffect
---@field GameplayEffectSpec GlobalCore.GameplayEffectSpec
---@field GameplayEventData GlobalCore.GameplayEventData
---@field GameplayModifier GlobalCore.GameplayModifier
---@field Light GlobalCore.Light
---@field LightOcclusionInput GlobalCore.LightOcclusionInput
---@field LightOcclusionResult GlobalCore.LightOcclusionResult
---@field AudioEffectControl GlobalCore.AudioEffectControl
---@field AudioManager GlobalCore.AudioManager
---@field FontManager GlobalCore.FontManager
---@field ShaderManager GlobalCore.ShaderManager
---@field TextureManager GlobalCore.TextureManager
---@field TimeManager GlobalCore.TimeManager
---@field TimerEntry GlobalCore.TimerEntry
---@field MapPanoramaSettings GlobalCore.MapPanoramaSettings
---@field PanoramaController GlobalCore.PanoramaController
---@field SceneBase GlobalCore.SceneBase
---@field System GlobalCore.System
---@field SystemConfigBase GlobalCore.SystemConfigBase
---@field UIManager GlobalCore.UIManager
---@field WeatherController GlobalCore.WeatherController
---@field WorldStreamingState GlobalCore.WorldStreamingState
---@field WorldStreamingStats GlobalCore.WorldStreamingStats
---@field WeatherType GlobalCore.WeatherType
---@field WorldRegionState GlobalCore.WorldRegionState
---@field WorldRegionDemand GlobalCore.WorldRegionDemand
---@field C_ImageUpdateBuffer1D fun(img: sf.Texture, buffer: string): nil
---@field C_ImageUpdateBuffer3D fun(img: sf.Texture, buffer: string): nil
---@type GlobalCoreModule
GlobalCore = {}

GlobalCore.WeatherType = {}
GlobalCore.WorldRegionState = {}
GlobalCore.WorldRegionDemand = {}

--- @brief Update an `sf::Texture` using a flat byte buffer
---
--- - @param img Target texture
--- - @param buffer 1D `uint8` RGBA buffer
---
---@param img sf.Texture
---@param buffer string
---@return nil
function GlobalCore.C_ImageUpdateBuffer1D(img, buffer) end

--- @brief Update an `sf::Texture` using a 3D RGBA buffer
---
--- - @param img Target texture
--- - @param buffer 3D `uint8` buffer with shape `[height, width, 4]`
---
---@param img sf.Texture
---@param buffer string
---@return nil
function GlobalCore.C_ImageUpdateBuffer3D(img, buffer) end

---@class GlobalCore.Animation : Engine.AnimSprite
---@field soundEntries Engine.AnimationSoundEntry[]
---@field soundIndex integer
---@field playingSounds GlobalCore.AnimationPlayingSound[]
local Animation = {}
---@param animationData Engine.AnimationData
---@param isSpatial? boolean
---@return GlobalCore.Animation
function Animation.new(animationData, isSpatial) end
---@param self GlobalCore.Animation
---@param animationData Engine.AnimationData
---@param isSpatial? boolean
function Animation.init(self, animationData, isSpatial) end
---@param animationData Engine.AnimationData
---@return nil
function Animation:setData(animationData) end
---@param deltaTime number
---@return nil
function Animation:update(deltaTime) end
---@param frameIndex integer
---@return nil
function Animation:playSoundsUpToFrame(frameIndex) end
---@param frameIndex integer
---@return nil
function Animation:stopSoundsAtFrame(frameIndex) end
GlobalCore.Animation = Animation

---@class GlobalCore.AnimationPlayingSound
---@field sound sf.Sound|nil
---@field endFrame integer
local AnimationPlayingSound = {}
---@param values table
---@return GlobalCore.AnimationPlayingSound
function AnimationPlayingSound.new(values) end
---@param self GlobalCore.AnimationPlayingSound
---@param values table
function AnimationPlayingSound.init(self, values) end
GlobalCore.AnimationPlayingSound = AnimationPlayingSound

--- @brief Camera with viewport tracking, smooth follow, and off-screen
--- rendering
---
--- Manages a render texture for off-screen drawing, supports viewport
--- transforms, and can follow a parent actor with position clamping.
---
---@class GlobalCore.Camera : sf.Drawable, sf.Transformable
local Camera = {}
---@param viewport? sf.FloatRect|nil
---@return GlobalCore.Camera
function Camera.new(viewport) end
---@param self GlobalCore.Camera
---@param viewport? sf.FloatRect|nil
function Camera.init(self, viewport) end
--- @brief Set the camera viewport rectangle
---
--- - @param inViewport The new viewport rectangle
---
---@param inViewport sf.FloatRect
---@return nil
function Camera:setViewport(inViewport) end
--- @brief Get the current render view
---
--- - @return The current View object
---
---@return sf.View view
function Camera:getView() end
--- @brief Get the current viewport position
---
--- - @return The viewport position, or nil if no viewport is set
---
---@return sf.Vector2f|nil position
function Camera:getViewPosition() end
--- @brief Set the viewport position
---
--- - @param inPosition The new viewport position
---
---@param inPosition sf.Vector2f
---@return nil
function Camera:setViewPosition(inPosition) end
--- @brief Get the current viewport size
---
--- - @return The viewport size, or nil if no viewport is set
---
---@return sf.Vector2f|nil size
function Camera:getViewSize() end
--- @brief Set the viewport size
---
--- - @param inSize The new viewport size
---
---@param inSize sf.Vector2f
---@return nil
function Camera:setViewSize(inSize) end
--- @brief Get the view rotation
---
--- - @return The view rotation
---
---@return sf.Angle rotation
function Camera:getViewRotation() end
--- @brief Set the view rotation
---
--- - @param inRotation The new rotation
---
---@param inRotation sf.Angle
---@return nil
function Camera:setViewRotation(inRotation) end
--- @brief Move the viewport by a delta offset
---
--- - @param delta The offset to move the viewport by
---
---@param delta sf.Vector2f
---@return nil
function Camera:moveView(delta) end
--- @brief Rotate the view by a delta
---
--- - @param delta The rotation delta
---
---@param delta sf.Angle
---@return nil
function Camera:rotateView(delta) end
--- @brief Reset the view to the render texture default view
---
---@return nil
function Camera:resumeViewport() end
--- @brief Get the camera transform position
---
--- - @return The transform position
---
---@return sf.Vector2f position
function Camera:getPosition() end
--- @brief Set the camera transform position
---
--- - @param inPosition The new transform position
---
---@param inPosition sf.Vector2f
---@return nil
function Camera:setPosition(inPosition) end
--- @brief Move the camera transform by a delta
---
--- - @param delta The offset to move by
---
---@param delta sf.Vector2f
---@return nil
function Camera:move(delta) end
--- @brief Get the camera transform rotation
---
--- - @return The transform rotation
---
---@return sf.Angle rotation
function Camera:getRotation() end
--- @brief Set the camera transform rotation
---
--- - @param inRotation The new rotation
---
---@param inRotation sf.Angle
---@return nil
function Camera:setRotation(inRotation) end
--- @brief Rotate the camera transform by a delta
---
--- - @param delta The rotation delta
---
---@param delta sf.Angle
---@return nil
function Camera:rotate(delta) end
--- @brief Get the camera transform scale
---
--- - @return The transform scale
---
---@return sf.Vector2f scale
function Camera:getScale() end
--- @brief Set the camera transform scale
---
--- - @param factors The new scale factors
---
---@param factors sf.Vector2f
---@return nil
function Camera:setScale(factors) end
--- @brief Scale the camera transform by a factor
---
--- - @param delta The scale factor
---
---@param delta sf.Vector2f
---@return nil
function Camera:scale(delta) end
--- @brief Get the parent actor this camera follows
---
--- - @return The parent actor, or nil
---
---@return Engine.Actor|nil parent
function Camera:getParent() end
--- @brief Set the parent actor for the camera to follow
---
--- - @param actor The actor to follow, or nil to stop following
---
---@param actor Engine.Actor|nil
---@return nil
function Camera:setParent(actor) end
--- @brief Set the game map this camera operates on
---
--- - @param map The game map
---
---@param map GlobalCore.GameMapBase|nil
---@return nil
function Camera:setMap(map) end
--- @brief Get the game map this camera operates on
---
--- - @return The game map, or nil
---
---@return GlobalCore.GameMapBase|nil map
function Camera:getMap() end
---@param object sf.Drawable
---@return nil
function Camera:render(object) end
---@return sf.FloatRect|nil
function Camera:getViewport() end
---@return sf.RenderStates
function Camera:getRenderStates() end
---@param inRenderStates sf.RenderStates
---@return nil
function Camera:setRenderStates(inRenderStates) end
--- @brief Convert a logical pixel position to world coordinates
---
--- - @param point The pixel position in logical game units
--- - @return The world coordinate position
---
---@param point sf.Vector2i
---@return sf.Vector2f
function Camera:mapPixelToCoords(point) end
--- @brief Convert world coordinates to a logical pixel position
---
--- - @param point The world coordinate position
--- - @return The pixel position in logical game units
---
---@param point sf.Vector2f
---@return sf.Vector2i
function Camera:mapCoordsToPixel(point) end
---@return sf.Texture
function Camera:getTexture() end
--- @brief Get the off-screen render target used for map drawing
---
--- - @return The camera RenderTexture
---
---@return sf.RenderTexture|nil renderTexture
function Camera:getRenderTexture() end
---@return sf.Image
function Camera:getImage() end
---@param deltaTime number
---@return nil
function Camera:onTick(deltaTime) end
---@param deltaTime number
---@return nil
function Camera:onLateTick(deltaTime) end
---@param fixedDelta number
---@return nil
function Camera:onFixedTick(fixedDelta) end
---@return nil
function Camera:syncFollowTarget() end
---@return nil
function Camera:fixViewPosition() end
---@return nil
function Camera:clear() end
---@return nil
function Camera:display() end
GlobalCore.Camera = Camera

---@class GlobalCore.CommonTipController
local CommonTipController = {}
---@param particleSystem Engine.ParticleSystem|nil
---@return GlobalCore.CommonTipController
function CommonTipController.new(particleSystem) end
---@param self GlobalCore.CommonTipController
---@param particleSystem Engine.ParticleSystem|nil
function CommonTipController.init(self, particleSystem) end
---@param text string
---@return nil
function CommonTipController:addTip(text) end
---@param deltaTime number
---@return nil
function CommonTipController:onTick(deltaTime) end
GlobalCore.CommonTipController = CommonTipController

---@class GlobalCore.FocusGroup : Engine.RuntimeObject
---@field name string
---@field activeOwner Engine.FunctionalBase|nil
local FocusGroup = {}
---@param name string
---@param items? (Engine.FunctionalBase|nil)[]
---@param activeOwner? Engine.FunctionalBase|nil
---@return GlobalCore.FocusGroup
function FocusGroup.new(name, items, activeOwner) end
---@param self GlobalCore.FocusGroup
---@param name string
---@param items? (Engine.FunctionalBase|nil)[]
---@param activeOwner? Engine.FunctionalBase|nil
function FocusGroup.init(self, name, items, activeOwner) end
---@param item Engine.FunctionalBase|nil
---@return nil
function FocusGroup:addItem(item) end
---@param item Engine.FunctionalBase|nil
---@return nil
function FocusGroup:removeItem(item) end
---@return (Engine.FunctionalBase|nil)[]
function FocusGroup:getItems() end
---@param direction string
---@param neighbor GlobalCore.FocusGroup|nil
---@param transition? string
---@return nil
function FocusGroup:setNeighbor(direction, neighbor, transition) end
---@param direction string
---@param neighbor GlobalCore.FocusNeighbor|nil
---@return nil
function FocusGroup:setNeighbor(direction, neighbor) end
---@param direction string
---@return GlobalCore.FocusNeighbor|nil
function FocusGroup:getNeighbor(direction) end
---@return boolean
function FocusGroup:canEnter() end
---@return Engine.FunctionalBase|nil
function FocusGroup:findInitialFocus() end
---@param element Engine.FunctionalBase|nil
---@return nil
function FocusGroup:rememberFocus(element) end
---@param current Engine.FunctionalBase|nil
---@param direction string
---@return Engine.FunctionalBase|nil
function FocusGroup:moveWithin(current, direction) end
GlobalCore.FocusGroup = FocusGroup

---@class GlobalCore.FocusManager
local FocusManager = {}
---@return GlobalCore.FocusManager
function FocusManager.new() end
---@param self GlobalCore.FocusManager
function FocusManager.init(self) end
---@param enabled boolean
---@return nil
function FocusManager:setNavigationEnabled(enabled) end
---@return boolean
function FocusManager:getNavigationEnabled() end
---@return boolean
function FocusManager:isRoutingKeyboard() end
---@param element Engine.FunctionalBase|nil
---@return nil
function FocusManager:registerElement(element) end
---@param element Engine.FunctionalBase|nil
---@return nil
function FocusManager:unregisterElement(element) end
---@param group GlobalCore.FocusGroup|nil
---@return nil
function FocusManager:registerFocusGroup(group) end
---@param group GlobalCore.FocusGroup|nil
---@return nil
function FocusManager:unregisterFocusGroup(group) end
---@return Engine.FunctionalBase|nil
function FocusManager:getFocus() end
---@param element Engine.FunctionalBase|nil
---@return boolean
function FocusManager:setFocus(element) end
---@return nil
function FocusManager:clearFocus() end
---@return nil
function FocusManager:prepareFrame() end
---@param element Engine.FunctionalBase|nil
---@return boolean
function FocusManager:shouldDispatchKeyboardTo(element) end
---@param element Engine.FunctionalBase|nil
---@return boolean
function FocusManager:isFocused(element) end
---@param element Engine.FunctionalBase|nil
---@return boolean
function FocusManager:isCursorFocusOwner(element) end
---@param element Engine.FunctionalBase|nil
---@param direction string
---@return boolean
function FocusManager:requestDirectionalMove(element, direction) end
---@param direction string
---@param source? Engine.FunctionalBase|nil
---@return boolean
function FocusManager:moveFocus(direction, source) end
---@param group GlobalCore.FocusGroup|nil
---@return boolean
function FocusManager:activateGroup(group) end
GlobalCore.FocusManager = FocusManager

---@class GlobalCore.FocusNeighbor
---@field group GlobalCore.FocusGroup|nil
---@field transition string
local FocusNeighbor = {}
---@param group GlobalCore.FocusGroup|nil
---@param transition? string
---@return GlobalCore.FocusNeighbor
function FocusNeighbor.new(group, transition) end
---@param self GlobalCore.FocusNeighbor
---@param group GlobalCore.FocusGroup|nil
---@param transition? string
function FocusNeighbor.init(self, group, transition) end
GlobalCore.FocusNeighbor = FocusNeighbor

---@class GlobalCore.FocusTransition
local FocusTransition = {}
---@type string
FocusTransition.DIRECTIONAL = nil
---@type string
FocusTransition.EXPLICIT = nil
GlobalCore.FocusTransition = FocusTransition

---@class GlobalCore.FogController
local FogController = {}
---@param mapData GlobalCore.MapFogSettings
---@return nil
function FogController.applyFromMapData(mapData) end
---@param mapData GlobalCore.MapFogSettings
---@return nil
function FogController.applyWorldFromMapData(mapData) end
---@param key string
---@param cellRect sf.IntRect
---@param graphic string
---@param power number
---@param scrollX number
---@param scrollY number
---@param distort number
---@return nil
function FogController.setWorldRegionFog(key, cellRect, graphic, power, scrollX, scrollY, distort) end
---@param key string
---@return nil
function FogController.removeWorldRegionFog(key) end
---@param camera GlobalCore.Camera
---@return nil
function FogController.drawWorldOverlay(camera) end
---@return nil
function FogController.clearFog() end
---@param deltaTime number
---@return nil
function FogController.update(deltaTime) end
---@return nil
function FogController.drawOverlay() end
GlobalCore.FogController = FogController

---@class GlobalCore.MapFogSettings
---@field fog string
---@field fogPower number
---@field fogOx number
---@field fogOy number
---@field fogDistort number
local MapFogSettings = {}
---@param values table
---@return GlobalCore.MapFogSettings
function MapFogSettings.new(values) end
---@param self GlobalCore.MapFogSettings
---@param values table
function MapFogSettings.init(self, values) end
GlobalCore.MapFogSettings = MapFogSettings

--- @brief Native game map base for material queries and navigation
---
---@class GlobalCore.GameMapBase : Engine.ActorMapService
local GameMapBase = {}
---@return GlobalCore.GameMapBase
function GameMapBase.new() end
---@param self GlobalCore.GameMapBase
function GameMapBase.init(self) end
--- @brief Build a grayscale texture from a material map
---
--- - @param size Output texture size
--- - @param materialMap Material values in range `[0, 1]`
--- - @param smooth Whether smoothing should be enabled
---
--- - @return Shared texture resource
---
---@param size sf.Vector2u
---@param materialMap (boolean|number)[][]
---@param smooth? boolean
---@return sf.Texture|nil
function GameMapBase:generateDataFromMap(size, materialMap, smooth) end
--- @brief Find path data between two grid positions using A*
---
--- - @param start Start position
--- - @param goal Goal position
--- - @param size Grid dimensions
--- - @param movingActor Actor whose footprint and occupancy are evaluated
--- - @param excludedAnchors Anchor cells that A* must not enter
---
--- - @return Pathfinding result containing offsets, points, and route
---
---@param start sf.Vector2i
---@param goal sf.Vector2i
---@param size sf.Vector2u
---@param movingActor Engine.Actor
---@param excludedAnchors? sf.Vector2i[]
---@return GlobalCore.PathResult
function GameMapBase:findPathExt(start, goal, size, movingActor, excludedAnchors) end
--- @brief Build a 2D map of dynamic material property values
---
--- - @param width Grid width
--- - @param height Grid height
--- - @param propertyName Material property name to evaluate
--- - @param invalidValue Fallback value for invalid positions
---
--- - @return 2D property map
---
---@param width integer
---@param height integer
---@param propertyName string
---@param invalidValue boolean|number
---@return (boolean|number)[][]
function GameMapBase:getMaterialPropertyMapExt(width, height, propertyName, invalidValue) end
--- @brief Recompute tile passability and actor occupancy caches
---
--- - @param size Grid dimensions
---
--- - @return Tile passability grid
---
---@param size sf.Vector2u
---@return boolean[][]
function GameMapBase:rebuildPassabilityCache(size) end
---@return nil
function GameMapBase:invalidatePassabilityCache() end
--- @brief Refresh one actor's occupancy without rebuilding tile passability
---
--- Removes the actor from all cached cells, then registers it at its
--- current occupied cells. Use this after an actor changes map position.
---
--- - @param actor Actor whose occupancy should be refreshed
---
---@param actor Engine.Actor
---@return nil
function GameMapBase:updateActorOccupancy(actor) end
---@return sf.Vector2u
function GameMapBase:getSize() end
--- @brief Get actors cached at one map position
---
--- - @param x Tile X coordinate
--- - @param y Tile Y coordinate
---
--- - @return Actors at the requested position
---
---@param x integer
---@param y integer
---@return Engine.Actor[]
function GameMapBase:getActorsAt(x, y) end
--- @brief Get actors cached inside a square tile range
---
--- - @param x Centre tile X coordinate
--- - @param y Centre tile Y coordinate
--- - @param radius Range radius in tiles
---
--- - @return Actors inside the requested range
---
---@param x integer
---@param y integer
---@param radius integer
---@return Engine.Actor[]
function GameMapBase:getActorsInRange(x, y, radius) end
---@param x integer
---@param y integer
---@param radius integer
---@param excludedActor Engine.Actor
---@return Engine.Actor[]
function GameMapBase:getActorsInRangeExcluding(x, y, radius, excludedActor) end
--- @brief Get colliding actors cached at one map position
---
--- - @param x Tile X coordinate
--- - @param y Tile Y coordinate
--- - @param selfActor Actor excluded from the result
---
--- - @return Colliding actors on the topmost occupied layer, ordered from
--- visually topmost to bottommost
---
---@param x integer
---@param y integer
---@param selfActor Engine.Actor
---@return Engine.Actor[]
function GameMapBase:getCollisionAt(x, y, selfActor) end
--- @brief Get overlapping actors cached at one map position
---
--- - @param x Tile X coordinate
--- - @param y Tile Y coordinate
--- - @param selfActor Actor excluded from the result
---
--- - @return Overlapping actors at the requested position
---
---@param x integer
---@param y integer
---@param selfActor Engine.Actor
---@return Engine.Actor[]
function GameMapBase:getOverlapsAt(x, y, selfActor) end
--- @brief Set the native tilemap used by material and passability queries
---
--- - @param tilemap Tilemap to retain
---
---@param tilemap Engine.Tilemap|nil
---@return nil
function GameMapBase:setTilemap(tilemap) end
---@param size sf.Vector2u
---@param layerOrder string[]
---@param regionRects sf.IntRect[]
---@return nil
function GameMapBase:configureSparseWorld(size, layerOrder, regionRects) end
---@param regionIndex integer
---@param tilemap Engine.Tilemap|nil
---@param actorsReady boolean
---@return nil
function GameMapBase:setSparseWorldRegion(regionIndex, tilemap, actorsReady) end
---@param regionIndex integer
---@return nil
function GameMapBase:setSparseWorldRegionActorsReady(regionIndex) end
---@param regionIndex integer
---@return nil
function GameMapBase:detachSparseWorldRegion(regionIndex) end
---@param rect sf.IntRect|nil
---@return nil
function GameMapBase:setSparseWorldPreparedRect(rect) end
---@param position sf.Vector2i
---@return boolean
function GameMapBase:isSparseWorldCellReady(position) end
---@param position sf.Vector2i
---@return boolean
function GameMapBase:isSparseWorldGameplayPositionReady(position) end
---@param position sf.Vector2i
---@return integer|nil
function GameMapBase:getSparseWorldRegionIndexAt(position) end
---@return nil
function GameMapBase:clearSparseWorld() end
---@return integer
function GameMapBase:getSparseOccupancyPageCount() end
---@param origin sf.Vector2i
---@param size sf.Vector2u
---@param actors (Engine.Actor|nil)[]
---@return sf.Texture|nil
function GameMapBase:rebuildStaticLightOccupancy(origin, size, actors) end
---@param inputs GlobalCore.LightOcclusionInput[]
---@param visibleActors (Engine.Actor|nil)[]
---@return GlobalCore.LightOcclusionResult[]
function GameMapBase:analyseLightOcclusion(inputs, visibleActors) end
--- @brief Synchronise cached actor pointers from typed actor lists
---
--- - @param actors Layer name to actor list mapping
---
---@param actors table<string, (Engine.Actor|nil)[]>
---@return nil
function GameMapBase:syncActorsRef(actors) end
---@param actors table<string, (Engine.Actor|nil)[]>
---@return nil
function GameMapBase:syncMaterialActorsRef(actors) end
---@param updater fun(): nil
---@return nil
function GameMapBase:setActorListUpdater(updater) end
---@param destroyer fun(arg1: Engine.Actor): nil
---@return nil
function GameMapBase:setActorDestroyer(destroyer) end
---@param actor? Engine.Actor|nil
---@return nil
function GameMapBase:setPlayerActor(actor) end
---@param actor Engine.Actor|nil
---@param layer string
---@return boolean
function GameMapBase:_registerLayerActor(actor, layer) end
---@param actor Engine.Actor
---@return string|nil
function GameMapBase:_getRegisteredActorLayer(actor) end
---@return nil
function GameMapBase:beginActorBatch() end
---@return nil
function GameMapBase:endActorBatch() end
---@return nil
function GameMapBase:_flushActorChanges() end
---@param handler fun(): nil
---@return nil
function GameMapBase:_withDeferredActorViewSync(handler) end
---@param createHandler fun(arg1: Engine.Actor): nil
---@param componentHandler fun(arg1: Engine.Actor): nil
---@return nil
function GameMapBase:_drainActorLifecycle(createHandler, componentHandler) end
---@param actors table<string, (Engine.Actor|nil)[]>
---@return nil
function GameMapBase:_syncActorViews(actors) end
---@param actors (Engine.Actor|nil)[]
---@return nil
function GameMapBase:_forgetActors(actors) end
---@param deltaTime number
---@return nil
function GameMapBase:_updateActors(deltaTime) end
---@param deltaTime number
---@return nil
function GameMapBase:_lateUpdateActors(deltaTime) end
---@param fixedDelta number
---@return nil
function GameMapBase:_fixedUpdateActors(fixedDelta) end
GlobalCore.GameMapBase = GameMapBase

--- @brief Pathfinding result in all runtime path formats
---
---@class GlobalCore.PathResult
--- @brief Per-step movement offsets
---
---@field offsets sf.Vector2i[]
--- @brief Absolute path points excluding the start position
---
---@field points sf.Vector2i[]
--- @brief Absolute route including the start position
---
---@field route sf.Vector2i[]
local PathResult = {}
GlobalCore.PathResult = PathResult

---@class GlobalCore.GameMapRenderer
local GameMapRenderer = {}
---@param map GlobalCore.GameMapBase
---@param tilemap Engine.Tilemap|nil
---@param camera GlobalCore.Camera|nil
---@param layerNames string[]
---@param coverAlpha integer
---@param previewOnly boolean
---@return GlobalCore.GameMapRenderer
function GameMapRenderer.new(map, tilemap, camera, layerNames, coverAlpha, previewOnly) end
---@param self GlobalCore.GameMapRenderer
---@param map GlobalCore.GameMapBase
---@param tilemap Engine.Tilemap|nil
---@param camera GlobalCore.Camera|nil
---@param layerNames string[]
---@param coverAlpha integer
---@param previewOnly boolean
function GameMapRenderer.init(self, map, tilemap, camera, layerNames, coverAlpha, previewOnly) end
---@param camera GlobalCore.Camera|nil
---@return nil
function GameMapRenderer:setCamera(camera) end
---@param target sf.RenderTarget
---@param states sf.RenderStates
---@param applyPlayerCover boolean
---@param shaderTime number
---@param materialRevision integer
---@param drawLayerEffects fun(arg1: string): nil
---@return nil
function GameMapRenderer:drawContent(target, states, applyPlayerCover, shaderTime, materialRevision, drawLayerEffects) end
---@param target sf.RenderTarget
---@param states sf.RenderStates
---@param actor Engine.Actor|nil
---@param actorAlpha integer
---@param shaderTime number
---@return nil
function GameMapRenderer:drawActor(target, states, actor, actorAlpha, shaderTime) end
---@param actor Engine.Actor|nil
---@param hidden boolean
---@return nil
function GameMapRenderer:setActorEffectHidden(actor, hidden) end
---@return nil
function GameMapRenderer:resetTransparentTiles() end
---@param mapLights GlobalCore.Light[]
---@param ambientLight sf.Color
---@param materialRevision integer
---@return nil
function GameMapRenderer:renderLighting(mapLights, ambientLight, materialRevision) end
---@param ambientLight sf.Color
---@return nil
function GameMapRenderer:refreshMaterialShader(ambientLight) end
---@return sf.Shader|nil
function GameMapRenderer:getMaterialShader() end
GlobalCore.GameMapRenderer = GameMapRenderer

---@class GlobalCore.AbilitySystemComponent : Engine.RuntimeObject
local AbilitySystemComponent = {}
---@param owner any
---@param attributeSet GlobalCore.AttributeSet
---@return GlobalCore.AbilitySystemComponent
function AbilitySystemComponent.new(owner, attributeSet) end
---@param self GlobalCore.AbilitySystemComponent
---@param owner any
---@param attributeSet GlobalCore.AttributeSet
function AbilitySystemComponent.init(self, owner, attributeSet) end
---@return any
function AbilitySystemComponent:getOwner() end
---@return GlobalCore.AttributeSet|nil
function AbilitySystemComponent:getAttributeSet() end
---@param name string
---@return integer|number
function AbilitySystemComponent:getNumericAttribute(name) end
---@param name string
---@return integer|number
function AbilitySystemComponent:getNumericAttributeBase(name) end
---@param name string
---@param value integer|number
---@return nil
function AbilitySystemComponent:setNumericAttributeBase(name, value) end
---@param values table<string, integer|number>
---@return nil
function AbilitySystemComponent:setNumericAttributeBases(values) end
---@return table<string, integer|number>
function AbilitySystemComponent:getNumericAttributeBases() end
---@param name string
---@param callback function
---@param params? any[]
---@return nil
function AbilitySystemComponent:addAttributeChangeListener(name, callback, params) end
---@param name string
---@param callback? fun(arg1: integer|number, arg2: GlobalCore.AbilitySystemComponent|nil, arg3: table<string, integer|number>): integer|number
---@return nil
function AbilitySystemComponent:setNumericAttributeConstraint(name, callback) end
---@param ability GlobalCore.GameplayAbility
---@param sourceKey? any
---@return GlobalCore.GameplayAbilitySpec|nil
function AbilitySystemComponent:giveAbility(ability, sourceKey) end
---@param sourceKey any
---@return nil
function AbilitySystemComponent:removeAbilitiesBySource(sourceKey) end
---@param abilityID string
---@param eventData? GlobalCore.GameplayEventData|nil
---@return GlobalCore.GameplayAbilityResult|nil
function AbilitySystemComponent:tryActivateAbility(abilityID, eventData) end
---@param eventData GlobalCore.GameplayEventData|nil
---@return (GlobalCore.GameplayAbilityResult|nil)[]
function AbilitySystemComponent:handleGameplayEvent(eventData) end
---@param spec GlobalCore.GameplayEffectSpec|nil
---@return integer|nil
function AbilitySystemComponent:applyGameplayEffectSpec(spec) end
---@param spec GlobalCore.GameplayEffectSpec|nil
---@return boolean
function AbilitySystemComponent:validateGameplayEffectSpec(spec) end
---@param handle integer
---@param stacks? integer|nil
---@return boolean
function AbilitySystemComponent:removeActiveGameplayEffect(handle, stacks) end
---@param effectID string
---@return integer
function AbilitySystemComponent:getActiveEffectStacks(effectID) end
---@return (GlobalCore.ActiveGameplayEffect|nil)[]
function AbilitySystemComponent:getActiveGameplayEffects() end
---@param tag string
---@return boolean
function AbilitySystemComponent:hasMatchingGameplayTag(tag) end
---@return integer
function AbilitySystemComponent:getRevision() end
---@param name string
---@param oldValue any
---@param newValue any
---@return nil
function AbilitySystemComponent:onAttributeWrite(name, oldValue, newValue) end
GlobalCore.AbilitySystemComponent = AbilitySystemComponent

---@class GlobalCore.ActiveGameplayEffect : Engine.RuntimeObject
---@field handle integer
---@field spec GlobalCore.GameplayEffectSpec|nil
---@field stacks integer
---@field applicationOrder integer
---@field grantedAbilitySpecs (GlobalCore.GameplayAbilitySpec|nil)[]
local ActiveGameplayEffect = {}
---@param effectHandle integer
---@param effectSpec GlobalCore.GameplayEffectSpec|nil
---@param order integer
---@return GlobalCore.ActiveGameplayEffect
function ActiveGameplayEffect.new(effectHandle, effectSpec, order) end
---@param self GlobalCore.ActiveGameplayEffect
---@param effectHandle integer
---@param effectSpec GlobalCore.GameplayEffectSpec|nil
---@param order integer
function ActiveGameplayEffect.init(self, effectHandle, effectSpec, order) end
GlobalCore.ActiveGameplayEffect = ActiveGameplayEffect

---@class GlobalCore.AttributeSet : Engine.RuntimeObject
local AttributeSet = {}
---@return GlobalCore.AttributeSet
function AttributeSet.new() end
---@param self GlobalCore.AttributeSet
function AttributeSet.init(self) end
---@param values table<string, any>
---@return nil
function AttributeSet:initialize(values) end
---@param values table<string, any>
---@return nil
function AttributeSet:initializeStored(values) end
---@return string[]
function AttributeSet:getAttributeNames() end
---@param name string
---@return GlobalCore.AttributeSchema|nil
function AttributeSet:getAttributeSchema(name) end
GlobalCore.AttributeSet = AttributeSet

---@class GlobalCore.AttributeSchema
---@field type Engine.RuntimeDataValue
---@field default any
local AttributeSchema = {}
---@param values table
---@return GlobalCore.AttributeSchema
function AttributeSchema.new(values) end
---@param self GlobalCore.AttributeSchema
---@param values table
function AttributeSchema.init(self, values) end
GlobalCore.AttributeSchema = AttributeSchema

---@class GlobalCore.GameplayAbility : Engine.RuntimeObject
---@field id string
---@field priority number
---@field abilityTags string[]
---@field requiredTags string[]
---@field blockedTags string[]
---@field triggerTags string[]
local GameplayAbility = {}
---@param values table
---@return GlobalCore.GameplayAbility
function GameplayAbility.new(values) end
---@param self GlobalCore.GameplayAbility
---@param values table
function GameplayAbility.init(self, values) end
---@param abilitySystem GlobalCore.AbilitySystemComponent
---@param eventData GlobalCore.GameplayEventData
---@return GlobalCore.GameplayAbilityResult|nil
function GameplayAbility:canActivate(abilitySystem, eventData) end
---@param abilitySystem GlobalCore.AbilitySystemComponent
---@param eventData GlobalCore.GameplayEventData
---@return GlobalCore.GameplayAbilityResult|nil
function GameplayAbility:calculate(abilitySystem, eventData) end
---@param abilitySystem GlobalCore.AbilitySystemComponent
---@param eventData GlobalCore.GameplayEventData
---@return GlobalCore.GameplayAbilityResult|nil
function GameplayAbility:activate(abilitySystem, eventData) end
GlobalCore.GameplayAbility = GameplayAbility

---@class GlobalCore.GameplayAbilityResult : Engine.RuntimeObject
---@field ok boolean
---@field code string|integer
---@field data any
local GameplayAbilityResult = {}
---@param succeeded boolean
---@param resultCode? string|integer|nil
---@param resultData? any
---@return GlobalCore.GameplayAbilityResult
function GameplayAbilityResult.new(succeeded, resultCode, resultData) end
---@param self GlobalCore.GameplayAbilityResult
---@param succeeded boolean
---@param resultCode? string|integer|nil
---@param resultData? any
function GameplayAbilityResult.init(self, succeeded, resultCode, resultData) end
---@param code? string|integer|nil
---@param data? any
---@return GlobalCore.GameplayAbilityResult|nil
function GameplayAbilityResult.Success(code, data) end
---@param code string|integer
---@param data? any
---@return GlobalCore.GameplayAbilityResult|nil
function GameplayAbilityResult.Failure(code, data) end
GlobalCore.GameplayAbilityResult = GameplayAbilityResult

---@class GlobalCore.GameplayAbilitySpec : Engine.RuntimeObject
---@field ability GlobalCore.GameplayAbility|nil
---@field sourceKey any
---@field grantOrder integer
local GameplayAbilitySpec = {}
---@param gameplayAbility GlobalCore.GameplayAbility
---@param source? any
---@param order? integer
---@return GlobalCore.GameplayAbilitySpec
function GameplayAbilitySpec.new(gameplayAbility, source, order) end
---@param self GlobalCore.GameplayAbilitySpec
---@param gameplayAbility GlobalCore.GameplayAbility
---@param source? any
---@param order? integer
function GameplayAbilitySpec.init(self, gameplayAbility, source, order) end
GlobalCore.GameplayAbilitySpec = GameplayAbilitySpec

---@class GlobalCore.GameplayEffect : Engine.RuntimeObject
---@field id string
---@field durationPolicy string
---@field stackingPolicy string
---@field modifiers GlobalCore.GameplayModifier[]
---@field grantedTags string[]
---@field grantedAbilities (GlobalCore.GameplayAbility|nil)[]
---@field data any
local GameplayEffect = {}
---@param values table
---@return GlobalCore.GameplayEffect
function GameplayEffect.new(values) end
---@param self GlobalCore.GameplayEffect
---@param values table
function GameplayEffect.init(self, values) end
GlobalCore.GameplayEffect = GameplayEffect

---@class GlobalCore.GameplayEffectSpec : Engine.RuntimeObject
---@field effect GlobalCore.GameplayEffect|nil
---@field eventData GlobalCore.GameplayEventData|nil
---@field stacks integer
---@field sourceKey any
local GameplayEffectSpec = {}
---@param gameplayEffect GlobalCore.GameplayEffect
---@param gameplayEvent? GlobalCore.GameplayEventData
---@param stackCount? integer
---@param source? any
---@return GlobalCore.GameplayEffectSpec
function GameplayEffectSpec.new(gameplayEffect, gameplayEvent, stackCount, source) end
---@param self GlobalCore.GameplayEffectSpec
---@param gameplayEffect GlobalCore.GameplayEffect
---@param gameplayEvent? GlobalCore.GameplayEventData
---@param stackCount? integer
---@param source? any
function GameplayEffectSpec.init(self, gameplayEffect, gameplayEvent, stackCount, source) end
GlobalCore.GameplayEffectSpec = GameplayEffectSpec

---@class GlobalCore.GameplayEventData : Engine.RuntimeObject
---@field instigator any
---@field target any
---@field eventTag string
---@field payload any
local GameplayEventData = {}
---@param eventInstigator? any
---@param eventTarget? any
---@param tag? string
---@param eventPayload? any
---@return GlobalCore.GameplayEventData
function GameplayEventData.new(eventInstigator, eventTarget, tag, eventPayload) end
---@param self GlobalCore.GameplayEventData
---@param eventInstigator? any
---@param eventTarget? any
---@param tag? string
---@param eventPayload? any
function GameplayEventData.init(self, eventInstigator, eventTarget, tag, eventPayload) end
GlobalCore.GameplayEventData = GameplayEventData

---@class GlobalCore.GameplayModifier
---@field attribute string
---@field operation string
---@field magnitude integer|number|(fun(arg1: GlobalCore.GameplayEffectSpec|nil, arg2: integer): integer|number)|nil
---@field minimum integer|number|nil
local GameplayModifier = {}
---@param values table
---@return GlobalCore.GameplayModifier
function GameplayModifier.new(values) end
---@param self GlobalCore.GameplayModifier
---@param values table
function GameplayModifier.init(self, values) end
GlobalCore.GameplayModifier = GameplayModifier

--- @brief Light source with position, colour, radius, and intensity
---
---@class GlobalCore.Light
---@field position sf.Vector2f
---@field colour sf.Color
---@field radius number
---@field intensity number
local Light = {}
---@type integer
Light.MAX_SHADER_LIGHTS = nil
---@param position? sf.Vector2f
---@param colour? sf.Color
---@param radius? number
---@param intensity? number
---@return GlobalCore.Light
function Light.new(position, colour, radius, intensity) end
---@param self GlobalCore.Light
---@param position? sf.Vector2f
---@param colour? sf.Color
---@param radius? number
---@param intensity? number
function Light.init(self, position, colour, radius, intensity) end
--- @brief Serialize the light to a dictionary-compatible map
---
--- - @return Map containing position, color, radius, and intensity
---
---@return table<string, number[]|integer[]|number|integer>
function Light:asDict() end
--- @brief Create a light from a dictionary-compatible map
---
--- - @param data Raw light data
--- - @return Light instance
---
---@param data table<string, number[]|integer[]|number|integer>
---@return GlobalCore.Light
function Light.fromDict(data) end
GlobalCore.Light = Light

---@class GlobalCore.LightOcclusionInput
---@field light GlobalCore.Light
---@field owner Engine.Actor|nil
local LightOcclusionInput = {}
---@param values table
---@return GlobalCore.LightOcclusionInput
function LightOcclusionInput.new(values) end
---@param self GlobalCore.LightOcclusionInput
---@param values table
function LightOcclusionInput.init(self, values) end
GlobalCore.LightOcclusionInput = LightOcclusionInput

---@class GlobalCore.LightOcclusionResult
---@field hasStaticTransmissionLoss boolean
---@field occluders (Engine.Actor|nil)[]
---@field maskRect sf.FloatRect|nil
---@field dynamicOccupancy sf.Texture|nil
---@field dynamicOccupancyOrigin sf.Vector2f
---@field dynamicOccupancySize sf.Vector2f
local LightOcclusionResult = {}
GlobalCore.LightOcclusionResult = LightOcclusionResult

---@class GlobalCore.AudioEffectControl
local AudioEffectControl = {}
---@return boolean
function AudioEffectControl:isCancelled() end
---@return nil
function AudioEffectControl:beginTail() end
---@return nil
function AudioEffectControl:finishTail() end
---@param source sf.SoundSource
---@param name string
---@param sampleRate integer
---@return nil
function AudioEffectControl:attachLuaProcessor(source, name, sampleRate) end
GlobalCore.AudioEffectControl = AudioEffectControl

---@class GlobalCore.AudioManager
local AudioManager = {}
---@param filePath string
---@return sf.SoundBuffer|nil
function AudioManager.loadSound(filePath) end
---@param filePath string
---@param filter? Engine.SoundFilter
---@param parent? sf.Transformable|nil
---@return sf.Sound|nil
function AudioManager.playSound(filePath, filter, parent) end
---@param sound sf.Sound|nil
---@param parent sf.Transformable|nil
---@return nil
function AudioManager.setSoundParent(sound, parent) end
---@param filePath string
---@param filter? Engine.SoundFilter
---@param refActor? sf.Transformable|nil
---@param minDistance? number
---@return sf.Sound|nil
function AudioManager.playVoice(filePath, filter, refActor, minDistance) end
---@param voice sf.Sound|nil
---@param refActor sf.Transformable|nil
---@param minDistance? number
---@return nil
function AudioManager.setVoiceRefActor(voice, refActor, minDistance) end
---@param musicType string
---@param filePath string
---@param filter? Engine.MusicFilter
---@return sf.Music|nil
function AudioManager.playMusic(musicType, filePath, filter) end
---@return nil
function AudioManager.stopSound() end
---@return nil
function AudioManager.stopVoice() end
---@param musicType string
---@return nil
function AudioManager.stopMusic(musicType) end
---@return nil
function AudioManager.applySoundVolumes() end
---@return nil
function AudioManager.applyVoiceVolumes() end
---@return nil
function AudioManager.applyMusicVolumes() end
---@return nil
function AudioManager.updateAllSoundPositions() end
---@return nil
function AudioManager.updateAllVoicePositions() end
---@param sound sf.Sound|nil
---@param filter Engine.SoundFilter
---@return nil
function AudioManager.setSoundFilter(sound, filter) end
---@param voice sf.Sound|nil
---@param filter Engine.SoundFilter
---@return nil
function AudioManager.setVoiceFilter(voice, filter) end
---@param music sf.Music|nil
---@param filter Engine.MusicFilter
---@return nil
function AudioManager.setMusicFilter(music, filter) end
---@param audioType string
---@param effect Source.AudioEffects.Attacher|nil
---@return nil
function AudioManager.setEffect(audioType, effect) end
---@return integer
function AudioManager.getMemory() end
GlobalCore.AudioManager = AudioManager

---@class GlobalCore.FontManager
local FontManager = {}
---@param filePath string
---@return sf.Font|nil
function FontManager.load(filePath) end
---@param fontName string
---@return sf.Font|nil
function FontManager.getFont(fontName) end
---@param fontName string
---@return string
function FontManager.getFontFilename(fontName) end
---@return string[]
function FontManager.getFontList() end
---@return string[]
function FontManager.getFontFilenameList() end
---@param fontName string
---@return boolean
function FontManager.hasFont(fontName) end
---@return integer
function FontManager.getMemory() end
GlobalCore.FontManager = FontManager

---@class GlobalCore.ShaderManager
local ShaderManager = {}
---@param shaderPath string
---@param shaderType? sf.Shader.Type|nil
---@return sf.Shader|nil
function ShaderManager.load(shaderPath, shaderType) end
---@param vertPath string
---@param fragPath string
---@return sf.Shader|nil
function ShaderManager.loadFull(vertPath, fragPath) end
---@param vertPath string
---@param geoPath string
---@param fragPath string
---@return sf.Shader|nil
function ShaderManager.loadFullShaderWithGeo(vertPath, geoPath, fragPath) end
---@return integer
function ShaderManager.getMemory() end
GlobalCore.ShaderManager = ShaderManager

---@class GlobalCore.TextureManager
local TextureManager = {}
---@param filePath string
---@param sRGB? boolean
---@param area? sf.IntRect|nil
---@param smooth? boolean
---@return sf.Texture|nil
function TextureManager.load(filePath, sRGB, area, smooth) end
---@return integer
function TextureManager.getMemory() end
--- Return the resource path associated with a cached texture, or nil for
--- textures created outside this manager.
---@param texture sf.Texture|nil
---@return string|nil
function TextureManager.getPath(texture) end
GlobalCore.TextureManager = TextureManager

---@class GlobalCore.TimeManager
local TimeManager = {}
---@return sf.Time
function TimeManager.getCurrentTime() end
---@return sf.Time
function TimeManager.getDeltaTime() end
---@return number
function TimeManager.getSpeed() end
---@param speed number
---@return nil
function TimeManager.setSpeed(speed) end
GlobalCore.TimeManager = TimeManager

---@class GlobalCore.TimerEntry
---@field time number
---@field task any
---@field params any[]
---@field blocking boolean
local TimerEntry = {}
---@param time number
---@param task? any
---@param params? any[]
---@param blocking? boolean
---@return GlobalCore.TimerEntry
function TimerEntry.new(time, task, params, blocking) end
---@param self GlobalCore.TimerEntry
---@param time number
---@param task? any
---@param params? any[]
---@param blocking? boolean
function TimerEntry.init(self, time, task, params, blocking) end
---@return boolean
function TimerEntry:isReady() end
---@return boolean
function TimerEntry:isCancelled() end
---@return nil
function TimerEntry:cancel() end
GlobalCore.TimerEntry = TimerEntry

---@class GlobalCore.MapPanoramaSettings
---@field panorama string
local MapPanoramaSettings = {}
---@param values table
---@return GlobalCore.MapPanoramaSettings
function MapPanoramaSettings.new(values) end
---@param self GlobalCore.MapPanoramaSettings
---@param values table
function MapPanoramaSettings.init(self, values) end
GlobalCore.MapPanoramaSettings = MapPanoramaSettings

---@class GlobalCore.PanoramaController
local PanoramaController = {}
---@param mapData GlobalCore.MapPanoramaSettings
---@return nil
function PanoramaController.applyFromMapData(mapData) end
---@param mapData GlobalCore.MapPanoramaSettings
---@return nil
function PanoramaController.applyWorldFromMapData(mapData) end
---@return nil
function PanoramaController.clear() end
---@return boolean
function PanoramaController.isActive() end
---@param camera GlobalCore.Camera
---@param ambientLight sf.Color
---@return nil
function PanoramaController.drawUnderlay(camera, ambientLight) end
GlobalCore.PanoramaController = PanoramaController

---@class GlobalCore.SceneBase
local SceneBase = {}
---@return GlobalCore.SceneBase
function SceneBase.new() end
---@param self GlobalCore.SceneBase
function SceneBase.init(self) end
---@return GlobalCore.UIManager|nil
function SceneBase:getUIManager() end
---@param map GlobalCore.GameMapBase|nil
---@return nil
function SceneBase:setEmitterMap(map) end
---@param interval number
---@param task? function
---@param params? any[]
---@param blocking? boolean
---@return fun(): boolean
function SceneBase:addTimer(interval, task, params, blocking) end
---@param interval number
---@param task any
---@param blocking boolean
---@return fun(): boolean
function SceneBase:addTimer(interval, task, blocking) end
---@return boolean blocked
function SceneBase:isInputBlocked() end
---@param anim GlobalCore.Animation|nil
---@return nil
function SceneBase:addAnim(anim) end
---@return (GlobalCore.Animation|nil)[] anims
function SceneBase:getAnims() end
---@param anim GlobalCore.Animation|nil
---@return nil
function SceneBase:removeAnim(anim) end
---@return nil
function SceneBase:clearAnims() end
---@param text string
---@return nil
function SceneBase:addCommonTip(text) end
GlobalCore.SceneBase = SceneBase

---@class GlobalCore.System : GlobalCore.SystemConfigBase
local System = {}
---@param data ConfigParser
---@param dataFilePath string
---@return nil
function System.init(data, dataFilePath) end
---@param title string
---@param gameSize sf.Vector2u
---@param iconPath string
---@param cursorPath string
---@return nil
function System.initializeDisplay(title, gameSize, iconPath, cursorPath) end
---@return string
function System.getScript() end
---@param value string
---@return nil
function System.setScript(value) end
---@param value string
---@return nil
function System.saveScript(value) end
---@return string
function System.getLanguage() end
---@param value string
---@return nil
function System.setLanguage(value) end
---@param value string
---@return nil
function System.saveLanguage(value) end
--- @brief Get the current positive display scale
---
--- - @return The actual scale used by rendering and input mapping
---
---@return number
function System.getScale() end
--- @brief Get the configured display scale
---
--- Zero selects borderless fullscreen on desktop. Non-finite and negative
--- values are normalised to one.
---
--- - @return The configured value, including zero
---
---@return number
function System.getConfiguredScale() end
--- @brief Get the largest configurable display scale
---
--- Desktop uses the current window's display work area when available,
--- otherwise the primary display. A configurable mobile host uses its
--- host-reported maximum windowed dimensions. Embedded and
--- non-configurable mobile displays return no value.
---
--- - @param gameSize Non-zero logical game size
--- - @return Maximum scale, or no value when display size is unavailable
---
---@param gameSize sf.Vector2u
---@return number|nil
function System.getMaximumWindowedScale(gameSize) end
--- @brief Apply and save a display scale
---
--- The display change is applied between complete frames.
---
--- - @param value Scale preference; zero selects desktop fullscreen
---
---@param value number
---@return nil
function System.setScale(value) end
--- @brief Apply a display scale without saving it
---
--- - @param value Scale preference; zero selects desktop fullscreen
---
---@param value number
---@return nil
function System.applyScale(value) end
--- @brief Save a display scale without applying it
---
--- - @param value Scale preference; zero selects desktop fullscreen
---
---@param value number
---@return nil
function System.saveScale(value) end
--- @brief Get the configured maximum render scale
---
--- Zero leaves the internal render scale uncapped. A positive value caps
--- the actual surface-fit scale without changing the window size.
---
--- - @return The configured maximum scale, including zero
---
---@return number
function System.getMaximumRenderScale() end
--- @brief Apply and save a maximum render scale
---
--- The render-target change is applied between complete frames.
---
--- - @param value Maximum scale; zero leaves rendering uncapped
---
---@param value number
---@return nil
function System.setMaximumRenderScale(value) end
--- @brief Save a maximum render scale without applying it
---
--- - @param value Maximum scale; zero leaves rendering uncapped
---
---@param value number
---@return nil
function System.saveMaximumRenderScale(value) end
--- @brief Get the configured lighting render scale
---
--- The supported values are 0.5, 0.75 and 1.0. Other values are
--- normalised to one.
---
--- - @return The configured lighting render scale
---
---@return number
function System.getLightingRenderScale() end
--- @brief Apply and save a lighting render scale
---
--- The lighting targets are rebuilt on the next map render.
---
--- - @param value Lighting render scale
---
---@param value number
---@return nil
function System.setLightingRenderScale(value) end
--- @brief Save a lighting render scale without applying it
---
--- - @param value Lighting render scale
---
---@param value number
---@return nil
function System.saveLightingRenderScale(value) end
--- @brief Check whether the current host can apply display scale changes
---
--- Standalone desktop windows support scale changes. Embedded displays and
--- ordinary mobile hosts do not; a mobile host may register support.
---
--- - @return True when display scale changes can be applied
---
---@return boolean
function System.isDisplayScaleConfigurable() end
---@return integer
function System.getFrameRate() end
---@param value integer
---@return nil
function System.setFrameRate(value) end
---@param value integer
---@return nil
function System.saveFrameRate(value) end
---@return integer
function System.getAntiAliasingLevel() end
---@param value integer
---@return nil
function System.setAntiAliasingLevel(value) end
---@param value integer
---@return nil
function System.saveAntiAliasingLevel(value) end
---@return boolean
function System.getVerticalSync() end
---@param value boolean
---@return nil
function System.setVerticalSync(value) end
---@param value boolean
---@return nil
function System.saveVerticalSync(value) end
---@return boolean
function System.getMusicOn() end
---@param value boolean
---@return nil
function System.setMusicOn(value) end
---@param value boolean
---@return nil
function System.saveMusicOn(value) end
---@return boolean
function System.getSoundOn() end
---@param value boolean
---@return nil
function System.setSoundOn(value) end
---@param value boolean
---@return nil
function System.saveSoundOn(value) end
---@return boolean
function System.getVoiceOn() end
---@param value boolean
---@return nil
function System.setVoiceOn(value) end
---@param value boolean
---@return nil
function System.saveVoiceOn(value) end
---@return number
function System.getMusicVolume() end
---@param value number
---@return nil
function System.setMusicVolume(value) end
---@param value number
---@return nil
function System.saveMusicVolume(value) end
---@return number
function System.getSoundVolume() end
---@param value number
---@return nil
function System.setSoundVolume(value) end
---@param value number
---@return nil
function System.saveSoundVolume(value) end
---@return number
function System.getVoiceVolume() end
---@param value number
---@return nil
function System.setVoiceVolume(value) end
---@param value number
---@return nil
function System.saveVoiceVolume(value) end
---@return boolean
function System.isDebugMode() end
---@return sf.Vector2u
function System.getGameSize() end
---@param disabled boolean
---@return nil
function System.setInputMethodDisabled(disabled) end
---@param rect sf.IntRect
---@return nil
function System.setWindowMapView(rect) end
---@return nil
function System.setWindowDefaultView() end
---@return sf.RenderTexture
function System.getCanvas() end
---@param weatherType GlobalCore.WeatherType
---@param power number
---@param maxCount integer
---@return nil
function System.setWeather(weatherType, power, maxCount) end
---@return nil
function System.clearWeather() end
---@return nil
function System.clearFog() end
---@param mapData GlobalCore.MapFogSettings
---@return nil
function System.applyFogFromMapData(mapData) end
---@return nil
function System.clearPanorama() end
---@param mapData GlobalCore.MapPanoramaSettings
---@return nil
function System.applyPanoramaFromMapData(mapData) end
---@return boolean
function System.isPerformanceProfilerEnabled() end
---@param queueDepth integer
---@param reading integer
---@param prepared integer
---@param active integer
---@param dormant integer
---@param cacheBytes integer
---@param publishMilliseconds number
---@param visibleTileChunks integer
---@param activeActors integer
---@return nil
function System.recordWorldStreamingPerformance(queueDepth, reading, prepared, active, dormant, cacheBytes, publishMilliseconds, visibleTileChunks, activeActors) end
---@param drawable sf.Drawable
---@param shader? sf.Shader
---@return nil
function System.draw(drawable, shader) end
---@param shader sf.Shader|nil
---@param uniforms? table<string, number|integer|boolean|sf.Vector2f|sf.Vector3f|sf.Glsl.Vec4|sf.Vector2i|sf.Vector3i|sf.Glsl.Ivec4|sf.Color|sf.Texture|nil|number[]|sf.Vector2f[]|sf.Vector3f[]|sf.Glsl.Vec4[]>
---@return nil
function System.addGraphicsShader(shader, uniforms) end
---@param shader sf.Shader|nil
---@return nil
function System.removeGraphicsShader(shader) end
---@return nil
function System.removeAllGraphicsShaders() end
---@param index integer
---@return nil
function System.removeGraphicsShaderAt(index) end
---@param color? sf.Color|nil
---@param duration? number
---@return nil
function System.flashScreen(color, duration) end
---@return nil
function System.stopFlash() end
---@return boolean
function System.isFlashing() end
---@param red? number
---@param green? number
---@param blue? number
---@param gray? number
---@param duration? number
---@return nil
function System.changeScreenTone(red, green, blue, gray, duration) end
---@param duration? number
---@return nil
function System.clearScreenTone(duration) end
---@return nil
function System.stopScreenTone() end
---@return boolean
function System.isScreenToneActive() end
---@return boolean
function System.isScreenToneTransitionComplete() end
---@param power? number
---@param speed? number
---@param duration? number
---@return nil
function System.startShake(power, speed, duration) end
---@return nil
function System.stopShake() end
---@return boolean
function System.isShaking() end
---@param transitionResource? sf.Texture|nil
---@param transitionTime? number
---@return nil
function System.setTransition(transitionResource, transitionTime) end
---@return nil
function System.freezeTransitionBackground() end
---@return boolean
function System.isTransitionBackgroundFrozen() end
---@return boolean
function System.isTransitionBackgroundFreezePending() end
---@return nil
function System.cancelTransitionBackgroundFreeze() end
---@param transitionName? string|nil
---@param transitionTime? number
---@return nil
function System.requestTransition(transitionName, transitionTime) end
---@return nil
function System.cancelPendingTransition() end
---@return boolean
function System.isTransitionPending() end
---@return boolean
function System.isInTransition() end
---@return SceneRuntime|nil
function System.getScene() end
---@return SceneRuntime|nil
function System.requireScene() end
---@return (SceneRuntime|nil)[]
function System.getSceneList() end
---@param scene SceneRuntime|nil
---@return nil
function System.setScene(scene) end
---@param scene SceneRuntime|nil
---@return nil
function System.pushScene(scene) end
---@return nil
function System.popScene() end
---@return nil
function System.exit() end
---@return nil
function System.run() end
GlobalCore.System = System

---@class GlobalCore.SystemConfigBase
local SystemConfigBase = {}
---@param data ConfigParser
---@param dataFilePath string
---@return nil
function SystemConfigBase.init(data, dataFilePath) end
---@return string
function SystemConfigBase.getScript() end
---@param value string
---@return nil
function SystemConfigBase.setScript(value) end
---@param value string
---@return nil
function SystemConfigBase.saveScript(value) end
---@return string
function SystemConfigBase.getLanguage() end
---@param value string
---@return nil
function SystemConfigBase.setLanguage(value) end
---@param value string
---@return nil
function SystemConfigBase.saveLanguage(value) end
--- @brief Get the current positive display scale
---
--- - @return The actual scale used by rendering and input mapping
---
---@return number
function SystemConfigBase.getScale() end
--- @brief Get the configured display scale
---
--- Zero selects borderless fullscreen on desktop. Non-finite and negative
--- values are normalised to one.
---
--- - @return The configured value, including zero
---
---@return number
function SystemConfigBase.getConfiguredScale() end
--- @brief Apply and save a display scale
---
--- The display change is applied between complete frames.
---
--- - @param value Scale preference; zero selects desktop fullscreen
---
---@param value number
---@return nil
function SystemConfigBase.setScale(value) end
--- @brief Apply a display scale without saving it
---
--- - @param value Scale preference; zero selects desktop fullscreen
---
---@param value number
---@return nil
function SystemConfigBase.applyScale(value) end
--- @brief Save a display scale without applying it
---
--- - @param value Scale preference; zero selects desktop fullscreen
---
---@param value number
---@return nil
function SystemConfigBase.saveScale(value) end
--- @brief Get the configured maximum render scale
---
--- Zero leaves the internal render scale uncapped. A positive value caps
--- the actual surface-fit scale without changing the window size.
---
--- - @return The configured maximum scale, including zero
---
---@return number
function SystemConfigBase.getMaximumRenderScale() end
--- @brief Apply and save a maximum render scale
---
--- - @param value Maximum scale; zero leaves rendering uncapped
---
---@param value number
---@return nil
function SystemConfigBase.setMaximumRenderScale(value) end
--- @brief Save a maximum render scale without applying it
---
--- - @param value Maximum scale; zero leaves rendering uncapped
---
---@param value number
---@return nil
function SystemConfigBase.saveMaximumRenderScale(value) end
--- @brief Get the configured lighting render scale
---
--- The supported values are 0.5, 0.75 and 1.0. Other values are
--- normalised to one.
---
--- - @return The configured lighting render scale
---
---@return number
function SystemConfigBase.getLightingRenderScale() end
--- @brief Apply and save a lighting render scale
---
--- - @param value Lighting render scale
---
---@param value number
---@return nil
function SystemConfigBase.setLightingRenderScale(value) end
--- @brief Save a lighting render scale without applying it
---
--- - @param value Lighting render scale
---
---@param value number
---@return nil
function SystemConfigBase.saveLightingRenderScale(value) end
---@return integer
function SystemConfigBase.getFrameRate() end
---@param value integer
---@return nil
function SystemConfigBase.setFrameRate(value) end
---@param value integer
---@return nil
function SystemConfigBase.saveFrameRate(value) end
---@return integer
function SystemConfigBase.getAntiAliasingLevel() end
---@param value integer
---@return nil
function SystemConfigBase.setAntiAliasingLevel(value) end
---@param value integer
---@return nil
function SystemConfigBase.saveAntiAliasingLevel(value) end
---@return boolean
function SystemConfigBase.getVerticalSync() end
---@param value boolean
---@return nil
function SystemConfigBase.setVerticalSync(value) end
---@param value boolean
---@return nil
function SystemConfigBase.saveVerticalSync(value) end
---@return boolean
function SystemConfigBase.getMusicOn() end
---@param value boolean
---@return nil
function SystemConfigBase.setMusicOn(value) end
---@param value boolean
---@return nil
function SystemConfigBase.saveMusicOn(value) end
---@return boolean
function SystemConfigBase.getSoundOn() end
---@param value boolean
---@return nil
function SystemConfigBase.setSoundOn(value) end
---@param value boolean
---@return nil
function SystemConfigBase.saveSoundOn(value) end
---@return boolean
function SystemConfigBase.getVoiceOn() end
---@param value boolean
---@return nil
function SystemConfigBase.setVoiceOn(value) end
---@param value boolean
---@return nil
function SystemConfigBase.saveVoiceOn(value) end
---@return number
function SystemConfigBase.getMusicVolume() end
---@param value number
---@return nil
function SystemConfigBase.setMusicVolume(value) end
---@param value number
---@return nil
function SystemConfigBase.saveMusicVolume(value) end
---@return number
function SystemConfigBase.getSoundVolume() end
---@param value number
---@return nil
function SystemConfigBase.setSoundVolume(value) end
---@param value number
---@return nil
function SystemConfigBase.saveSoundVolume(value) end
---@return number
function SystemConfigBase.getVoiceVolume() end
---@param value number
---@return nil
function SystemConfigBase.setVoiceVolume(value) end
---@param value number
---@return nil
function SystemConfigBase.saveVoiceVolume(value) end
GlobalCore.SystemConfigBase = SystemConfigBase

---@class GlobalCore.UIManager
local UIManager = {}
---@return GlobalCore.UIManager
function UIManager.new() end
---@param self GlobalCore.UIManager
function UIManager.init(self) end
---@return GlobalCore.FocusManager|nil
function UIManager:getFocusManager() end
---@param enabled boolean
---@return nil
function UIManager:setFocusNavigationEnabled(enabled) end
---@param group GlobalCore.FocusGroup|nil
---@return nil
function UIManager:registerFocusGroup(group) end
---@param ui Engine.ControlBase|nil
---@return nil
function UIManager:loadUI(ui) end
---@return (Engine.ControlBase|nil)[] uis
function UIManager:getUIs() end
---@param ui Engine.ControlBase|nil
---@return nil
function UIManager:removeUI(ui) end
GlobalCore.UIManager = UIManager

---@class GlobalCore.WeatherController
local WeatherController = {}
---@param weatherType GlobalCore.WeatherType
---@param power number
---@param maxCount integer
---@return nil
function WeatherController.setWeather(weatherType, power, maxCount) end
---@return nil
function WeatherController.clearWeather() end
---@param deltaTime number
---@return nil
function WeatherController.update(deltaTime) end
---@param camera GlobalCore.Camera
---@return nil
function WeatherController.drawShaderOverlay(camera) end
---@return GlobalCore.WeatherType
function WeatherController.getWeatherType() end
GlobalCore.WeatherController = WeatherController

---@class GlobalCore.WorldStreamingState
local WorldStreamingState = {}
---@param regionRects sf.IntRect[]
---@param nonActiveRegionLimit integer
---@param nonActiveByteLimit integer
---@return GlobalCore.WorldStreamingState
function WorldStreamingState.new(regionRects, nonActiveRegionLimit, nonActiveByteLimit) end
---@param self GlobalCore.WorldStreamingState
---@param regionRects sf.IntRect[]
---@param nonActiveRegionLimit integer
---@param nonActiveByteLimit integer
function WorldStreamingState.init(self, regionRects, nonActiveRegionLimit, nonActiveByteLimit) end
---@param cameraCenter sf.Vector2f
---@return sf.Vector2f
function WorldStreamingState:updateCameraCenter(cameraCenter) end
---@param activeRect sf.IntRect
---@param preparedRect sf.IntRect
---@param cameraCenter sf.Vector2f
---@param actorDemandRegions integer[]
---@return nil
function WorldStreamingState:updateDemand(activeRect, preparedRect, cameraCenter, actorDemandRegions) end
---@param regionIndex integer
---@return GlobalCore.WorldRegionState
function WorldStreamingState:getRegionState(regionIndex) end
---@param regionIndex integer
---@return GlobalCore.WorldRegionDemand
function WorldStreamingState:getRegionDemand(regionIndex) end
---@param regionIndex integer
---@return boolean
function WorldStreamingState:isRegionDemanded(regionIndex) end
---@param regionIndex integer
---@return boolean
function WorldStreamingState:isRegionLoaded(regionIndex) end
---@param regionIndex integer
---@return nil
function WorldStreamingState:requestRegion(regionIndex) end
---@param maximumCount integer
---@return integer[]
function WorldStreamingState:takeReadBatch(maximumCount) end
---@param regionIndex integer
---@param requeue boolean
---@return nil
function WorldStreamingState:cancelRead(regionIndex, requeue) end
---@param regionIndex integer
---@param forceActivate boolean
---@return nil
function WorldStreamingState:beginPublish(regionIndex, forceActivate) end
---@return integer|nil
function WorldStreamingState:takePublishItem() end
---@param regionIndex integer
---@return nil
function WorldStreamingState:deferPublish(regionIndex) end
---@param regionIndex integer
---@param requeueRead boolean
---@return nil
function WorldStreamingState:cancelPublish(regionIndex, requeueRead) end
---@param regionIndex integer
---@param payloadBytes integer
---@param activate boolean
---@return nil
function WorldStreamingState:completePublish(regionIndex, payloadBytes, activate) end
---@param regionIndex integer
---@return nil
function WorldStreamingState:markActive(regionIndex) end
---@param regionIndex integer
---@param state GlobalCore.WorldRegionState
---@return nil
function WorldStreamingState:markInactive(regionIndex, state) end
---@param regionIndex integer
---@return nil
function WorldStreamingState:markEvicted(regionIndex) end
---@param regionIndex integer
---@return integer
function WorldStreamingState:getRegionPayloadBytes(regionIndex) end
---@return integer[]
function WorldStreamingState:getEvictionList() end
---@param backgroundQueueDepth integer
---@return GlobalCore.WorldStreamingStats
function WorldStreamingState:getStats(backgroundQueueDepth) end
---@return nil
function WorldStreamingState:reset() end
GlobalCore.WorldStreamingState = WorldStreamingState

---@class GlobalCore.WorldStreamingStats
---@field Unloaded integer
---@field Reading integer
---@field Prepared integer
---@field Active integer
---@field Dormant integer
---@field queued integer
---@field cacheBytes integer
local WorldStreamingStats = {}
GlobalCore.WorldStreamingStats = WorldStreamingStats

return GlobalCore
