-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowHotkeys.HotkeyText

---@class Internal.UIBase.GeneratedControls.Parts.WindowHotkeys.HotkeyText
---@field Text Engine.PlainText

---@class Internal.UIBase.GeneratedAssets.Parts.WindowHotkeys.HotkeyText

---@class Internal.UI.Parts.WindowHotkeys.HotkeyText: Internal.UIBase.UiView
---@field root     Engine.PlainText
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowHotkeys.HotkeyText
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowHotkeys.HotkeyText
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowHotkeys.HotkeyText
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
