-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")

---@class Internal.UI.Parts.WindowShop.WindowShopTabs
local View = {}

View.assetKey = "Parts/WindowShop/WindowShopTabs"
View.designSize = sf.Vector2f.new(352, 64)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        Tabs = assert(self.instance:requireControl("Tabs")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowShop.WindowShopTabs
    self.controls = controls
    local assets = {
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopTabs
    self.assets = assets
end

return class(View, UiView)
