-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

---@enum Enums.Animation
local Animation = {
    attack = "attack",
    watershot = "watershot",
    waterspread = "waterspread"
}

return Animation
