-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

return {
    Class = "Class",
    Enemy = "Enemy",
    Equip = "Equip",
    Item = "Item",
    Player = "Player",
    Special = "Special",
    State = "State",
}
