-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

---@enum Enums.Particle
local Particle = {
    ResidentAura = "ResidentAura",
    Smoke = "Smoke",
    Sparks = "Sparks",
    UiSparkle = "UiSparkle"
}

return Particle
