-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.Parts.WindowHotkeys.HotkeyText
local View = {}

View.assetKey = "Parts/WindowHotkeys/HotkeyText"
View.designSize = sf.Vector2f.new(320, 24)

function View:init(instance)
    UiView.init(self, instance)
    local controls = { Text = assert(self.instance:requireControl("Text")) }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowHotkeys.HotkeyText
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowHotkeys.HotkeyText
    self.assets = assets
end

return class(View, UiView)
