-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowItem.ItemRow

---@class Source.UIBase.GeneratedControls.Parts.WindowItem.ItemRow
---@field Count Engine.PlainText
---@field Icon  Engine.FunctionalImage
---@field Root  Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.WindowItem.ItemRow

---@class Source.UI.Parts.WindowItem.ItemRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowItem.ItemRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowItem.ItemRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowItem.ItemRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
