-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapPreview
local View = {}

View.assetKey = "Parts/WindowFloorTeleporter/WindowFloorMapPreview"
View.designSize = sf.Vector2f.new(416, 240)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        PreviewContent = assert(self.instance:requireControl("PreviewContent")),
        PreviewImage = assert(self.instance:requireControl("PreviewImage")),
        PreviewWindowFrame = assert(self.instance:requireControl("PreviewWindowFrame")),
        Root = assert(self.instance:requireControl("Root")),
        TelepointContent = assert(self.instance:requireControl("TelepointContent")),
        TelepointList = assert(self.instance:requireControl("TelepointList")),
        TelepointScrollBox = assert(self.instance:requireControl("TelepointScrollBox")),
        TelepointWindowFrame = assert(self.instance:requireControl("TelepointWindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapPreview
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapPreview
    self.assets = assets
end

return class(View, UiView)
