-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.Shared.CommandRow")

---@class Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand
local View = {}

View.assetKey = "Parts/WindowFloorTeleporter/WindowFloorMapCommand"
View.designSize = sf.Vector2f.new(176, 240)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        CommandList = assert(self.instance:requireControl("CommandList")),
        CommandScrollBox = assert(self.instance:requireControl("CommandScrollBox")),
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapCommand
    self.controls = controls
    local assets = {
        MapPlaceholder1 = self:own(ChildView1.new(assert(self.instance:requireAsset("MapPlaceholder1")))),
        MapPlaceholder2 = self:own(ChildView1.new(assert(self.instance:requireAsset("MapPlaceholder2")))),
        MapPlaceholder3 = self:own(ChildView1.new(assert(self.instance:requireAsset("MapPlaceholder3")))),
        MapPlaceholder4 = self:own(ChildView1.new(assert(self.instance:requireAsset("MapPlaceholder4")))),
        MapPlaceholder5 = self:own(ChildView1.new(assert(self.instance:requireAsset("MapPlaceholder5")))),
        MapPlaceholder6 = self:own(ChildView1.new(assert(self.instance:requireAsset("MapPlaceholder6")))),
        MapPlaceholder7 = self:own(ChildView1.new(assert(self.instance:requireAsset("MapPlaceholder7"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapCommand
    self.assets = assets
end

return class(View, UiView)
