cmake_minimum_required(VERSION 3.21)

include("${PREVIEW_STAGE_CONFIG}")
include("${CMAKE_CURRENT_LIST_DIR}/RuntimeFiles.cmake")
if(NOT PREVIEW_PLATFORM MATCHES "^(win32|darwin|linux)$")
    message(FATAL_ERROR "Unsupported UiPreviewHost platform: ${PREVIEW_PLATFORM}")
endif()
if(NOT PREVIEW_CONFIGURATION MATCHES "^(Debug|Release)$")
    message(FATAL_ERROR "Unsupported UiPreviewHost configuration: ${PREVIEW_CONFIGURATION}")
endif()
ludork_preview_runtime_filenames(runtime_names "${PREVIEW_RUNTIME_FILES}" "${PREVIEW_RUNTIME_LINKS}")
set(runtime_files_json "[")
set(separator "")
foreach(name IN LISTS runtime_names)
    string(APPEND runtime_files_json "${separator}\"${name}\"")
    set(separator ",")
endforeach()
string(APPEND runtime_files_json "]")
set(header "#pragma once\n\n#include <string_view>\n\nnamespace ludork::preview_host::build_info {\n\ninline constexpr std::string_view platform = \"${PREVIEW_PLATFORM}\";\ninline constexpr std::string_view configuration = \"${PREVIEW_CONFIGURATION}\";\ninline constexpr std::string_view filesJson = R\"json(${runtime_files_json})json\";\n\n}  // namespace ludork::preview_host::build_info\n")
set(existing_header "")
if(EXISTS "${PREVIEW_BUILD_INFO_HEADER}")
    file(READ "${PREVIEW_BUILD_INFO_HEADER}" existing_header)
endif()
if(NOT header STREQUAL existing_header)
    get_filename_component(header_directory "${PREVIEW_BUILD_INFO_HEADER}" DIRECTORY)
    file(MAKE_DIRECTORY "${header_directory}")
    file(WRITE "${PREVIEW_BUILD_INFO_HEADER}" "${header}")
endif()
