include_guard(GLOBAL)

function(ludork_preview_runtime_filenames output runtime_files runtime_links)
    list(FILTER runtime_files EXCLUDE REGEX "^$")
    list(REMOVE_DUPLICATES runtime_files)
    set(runtime_names)
    foreach(source IN LISTS runtime_files)
        get_filename_component(name "${source}" NAME)
        list(APPEND runtime_names "${name}")
    endforeach()
    set(runtime_file_names "${runtime_names}")
    foreach(link IN LISTS runtime_links)
        string(REPLACE "|" ";" pair "${link}")
        list(LENGTH pair pair_length)
        if(NOT pair_length EQUAL 2)
            message(FATAL_ERROR "UiPreviewHost has an invalid runtime link: ${link}")
        endif()
        list(GET pair 0 name)
        list(GET pair 1 target)
        if(NOT target IN_LIST runtime_file_names)
            message(FATAL_ERROR "UiPreviewHost runtime link has an unknown target: ${link}")
        endif()
        if(NOT name STREQUAL target)
            list(APPEND runtime_names "${name}")
        endif()
    endforeach()
    set(runtime_name_keys)
    foreach(name IN LISTS runtime_names)
        if(NOT name MATCHES "^[A-Za-z0-9_.+-]+$" OR name STREQUAL "." OR name STREQUAL "..")
            message(FATAL_ERROR "UiPreviewHost dependency has an unsafe filename: ${name}")
        endif()
        string(TOLOWER "${name}" key)
        if(key IN_LIST runtime_name_keys)
            message(FATAL_ERROR "UiPreviewHost dependencies have duplicate filenames: ${name}")
        endif()
        list(APPEND runtime_name_keys "${key}")
    endforeach()
    list(SORT runtime_names)
    set(${output} "${runtime_names}" PARENT_SCOPE)
endfunction()
