cmake_minimum_required(VERSION 3.21)

include("${PREVIEW_STAGE_CONFIG}")
include("${CMAKE_CURRENT_LIST_DIR}/RuntimeFiles.cmake")
get_filename_component(runtime_directory "${PREVIEW_EXECUTABLE}" DIRECTORY)
file(MAKE_DIRECTORY "${runtime_directory}")
list(FILTER PREVIEW_RUNTIME_FILES EXCLUDE REGEX "^$")
list(REMOVE_DUPLICATES PREVIEW_RUNTIME_FILES)

ludork_preview_runtime_filenames(runtime_names "${PREVIEW_RUNTIME_FILES}" "${PREVIEW_RUNTIME_LINKS}")
foreach(source IN LISTS PREVIEW_RUNTIME_FILES)
    if(NOT EXISTS "${source}" OR IS_DIRECTORY "${source}")
        message(FATAL_ERROR "UiPreviewHost runtime dependency was not found: ${source}")
    endif()
endforeach()
set(copied_files)
foreach(source IN LISTS PREVIEW_RUNTIME_FILES)
    get_filename_component(name "${source}" NAME)
    set(destination "${runtime_directory}/${name}")
    if(NOT source STREQUAL destination)
        file(COPY_FILE "${source}" "${destination}" ONLY_IF_DIFFERENT)
    endif()
    list(APPEND copied_files "${destination}")
endforeach()
foreach(link IN LISTS PREVIEW_RUNTIME_LINKS)
    string(REPLACE "|" ";" pair "${link}")
    list(GET pair 0 name)
    list(GET pair 1 target)
    if(name STREQUAL target)
        continue()
    endif()
    set(destination "${runtime_directory}/${name}")
    if(IS_SYMLINK "${destination}")
        file(READ_SYMLINK "${destination}" existing_target)
        if(existing_target STREQUAL target)
            continue()
        endif()
        file(REMOVE "${destination}")
    elseif(EXISTS "${destination}")
        message(FATAL_ERROR "UiPreviewHost runtime link conflicts with a file: ${destination}")
    endif()
    file(CREATE_LINK "${target}" "${destination}" SYMBOLIC)
endforeach()

if(PREVIEW_MACOS)
    find_program(OTOOL_EXECUTABLE otool REQUIRED)
    find_program(CODESIGN_EXECUTABLE codesign REQUIRED)
    foreach(binary IN LISTS copied_files)
        execute_process(COMMAND "${OTOOL_EXECUTABLE}" -L "${binary}"
            OUTPUT_VARIABLE linked_libraries COMMAND_ERROR_IS_FATAL ANY)
        string(REPLACE "\n" ";" linked_libraries "${linked_libraries}")
        foreach(line IN LISTS linked_libraries)
            string(STRIP "${line}" line)
            if(NOT line MATCHES "^(.+) \\(compatibility version")
                continue()
            endif()
            set(dependency "${CMAKE_MATCH_1}")
            if(dependency MATCHES "^(/System/Library/|/usr/lib/)")
                continue()
            endif()
            if(NOT dependency MATCHES "^@(rpath|loader_path)/([^/]+)$")
                message(FATAL_ERROR "UiPreviewHost dependency is not colocated: ${dependency}")
            endif()
            set(dependency_name "${CMAKE_MATCH_2}")
            if(NOT dependency_name IN_LIST runtime_names)
                message(FATAL_ERROR "UiPreviewHost has an unbundled dependency: ${dependency}")
            endif()
        endforeach()
        execute_process(COMMAND "${CODESIGN_EXECUTABLE}"
            --verify --strict "${binary}"
            COMMAND_ERROR_IS_FATAL ANY)
    endforeach()
endif()
