-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.Parts.PlayerAttrHUD.PlayerStateRow
local View = {}

View.assetKey = "Parts/PlayerAttrHUD/PlayerStateRow"
View.designSize = sf.Vector2f.new(132, 24)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Icon = assert(self.instance:requireControl("Icon")),
        IconArea = assert(self.instance:requireControl("IconArea")),
        Root = assert(self.instance:requireControl("Root")),
        StateContent = assert(self.instance:requireControl("StateContent")),
        StateName = assert(self.instance:requireControl("StateName"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.PlayerAttrHUD.PlayerStateRow
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.PlayerAttrHUD.PlayerStateRow
    self.assets = assets
end

return class(View, UiView)
