-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowItem.ItemRow

---@class Internal.UIBase.GeneratedControls.Parts.WindowItem.ItemRow
---@field Count Engine.PlainText
---@field Icon  Engine.FunctionalImage
---@field Root  Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.WindowItem.ItemRow

---@class Internal.UI.Parts.WindowItem.ItemRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowItem.ItemRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowItem.ItemRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowItem.ItemRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
