-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.VertexBuffer.Usage
local enum = {
    Dynamic = (1 --[[@as sf.VertexBuffer.Usage]]),
    Static = (2 --[[@as sf.VertexBuffer.Usage]]),
    Stream = (0 --[[@as sf.VertexBuffer.Usage]]),
}

return enum
