-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.Parts.WindowBottle.BottleRow
local View = {}

View.assetKey = "Parts/WindowBottle/BottleRow"
View.designSize = sf.Vector2f.new(80, 40)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Count = assert(self.instance:requireControl("Count")),
        Icon = assert(self.instance:requireControl("Icon")),
        Multiply = assert(self.instance:requireControl("Multiply")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowBottle.BottleRow
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowBottle.BottleRow
    self.assets = assets
end

return class(View, UiView)
