-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.GlobalCore.WeatherType
local enum = {
    NONE = (0 --[[@as GlobalCore.WeatherType]]),
    RAIN = (1 --[[@as GlobalCore.WeatherType]]),
    SNOW = (3 --[[@as GlobalCore.WeatherType]]),
    STORM = (2 --[[@as GlobalCore.WeatherType]]),
}

return enum
