-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.GlobalCore.WorldRegionState
local enum = {
    Active = (3 --[[@as GlobalCore.WorldRegionState]]),
    Dormant = (4 --[[@as GlobalCore.WorldRegionState]]),
    Prepared = (2 --[[@as GlobalCore.WorldRegionState]]),
    Reading = (1 --[[@as GlobalCore.WorldRegionState]]),
    Unloaded = (0 --[[@as GlobalCore.WorldRegionState]]),
}

return enum
