-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.GlobalCore.WorldRegionDemand
local enum = {
    Active = (2 --[[@as GlobalCore.WorldRegionDemand]]),
    None = (0 --[[@as GlobalCore.WorldRegionDemand]]),
    Prepared = (1 --[[@as GlobalCore.WorldRegionDemand]]),
}

return enum
