-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.BlendMode.Equation
local enum = {
    Add = (0 --[[@as sf.BlendMode.Equation]]),
    Max = (4 --[[@as sf.BlendMode.Equation]]),
    Min = (3 --[[@as sf.BlendMode.Equation]]),
    ReverseSubtract = (2 --[[@as sf.BlendMode.Equation]]),
    Subtract = (1 --[[@as sf.BlendMode.Equation]]),
}

return enum
