-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.BlendMode.Factor
local enum = {
    DstAlpha = (8 --[[@as sf.BlendMode.Factor]]),
    DstColor = (4 --[[@as sf.BlendMode.Factor]]),
    One = (1 --[[@as sf.BlendMode.Factor]]),
    OneMinusDstAlpha = (9 --[[@as sf.BlendMode.Factor]]),
    OneMinusDstColor = (5 --[[@as sf.BlendMode.Factor]]),
    OneMinusSrcAlpha = (7 --[[@as sf.BlendMode.Factor]]),
    OneMinusSrcColor = (3 --[[@as sf.BlendMode.Factor]]),
    SrcAlpha = (6 --[[@as sf.BlendMode.Factor]]),
    SrcColor = (2 --[[@as sf.BlendMode.Factor]]),
    Zero = (0 --[[@as sf.BlendMode.Factor]]),
}

return enum
