-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowSaveLoad.WindowSaveTabs

---@class Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveTabs
---@field Content     Engine.Canvas
---@field Root        Engine.Canvas
---@field Tabs        Engine.TabView
---@field WindowFrame Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveTabs

---@class Source.UI.Parts.WindowSaveLoad.WindowSaveTabs: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveTabs
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveTabs
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowSaveLoad.WindowSaveTabs
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
