-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowSaveLoad.WindowSaveSlotRow

---@class Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveSlotRow
---@field Label Engine.PlainText
---@field Root  Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveSlotRow

---@class Source.UI.Parts.WindowSaveLoad.WindowSaveSlotRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveSlotRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveSlotRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowSaveLoad.WindowSaveSlotRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
