-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowSaveLoad.WindowSaveDetail

---@class Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveDetail
---@field Content       Engine.Canvas
---@field Root          Engine.Canvas
---@field Thumbnail     Engine.Image
---@field TimestampText Engine.FunctionalPlainText
---@field WindowFrame   Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveDetail

---@class Source.UI.Parts.WindowSaveLoad.WindowSaveDetail: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveDetail
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveDetail
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowSaveLoad.WindowSaveDetail
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
