-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.SoundSource.Status
local enum = {
    Paused = (1 --[[@as sf.SoundSource.Status]]),
    Playing = (2 --[[@as sf.SoundSource.Status]]),
    Stopped = (0 --[[@as sf.SoundSource.Status]]),
}

return enum
