-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Joystick.Axis

---@class Enums.sf.Joystick.Axis
---@field PovX sf.Joystick.Axis
---@field PovY sf.Joystick.Axis
---@field R sf.Joystick.Axis
---@field U sf.Joystick.Axis
---@field V sf.Joystick.Axis
---@field X sf.Joystick.Axis
---@field Y sf.Joystick.Axis
---@field Z sf.Joystick.Axis
---@type Enums.sf.Joystick.Axis
local enum = {}

return enum
