-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowEquip.EquipItemRow

---@class Source.UIBase.GeneratedControls.Parts.WindowEquip.EquipItemRow
---@field Count Engine.PlainText
---@field Icon  Engine.FunctionalImage
---@field Root  Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.WindowEquip.EquipItemRow

---@class Source.UI.Parts.WindowEquip.EquipItemRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowEquip.EquipItemRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowEquip.EquipItemRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowEquip.EquipItemRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
