-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowEquip.EquipSlotRow

---@class Source.UIBase.GeneratedControls.Parts.WindowEquip.EquipSlotRow
---@field Icon  Engine.FunctionalImage
---@field Label Engine.PlainText
---@field Root  Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.WindowEquip.EquipSlotRow

---@class Source.UI.Parts.WindowEquip.EquipSlotRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowEquip.EquipSlotRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowEquip.EquipSlotRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowEquip.EquipSlotRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
