-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowEquip.EquipStatusRow

---@class Source.UIBase.GeneratedControls.Parts.WindowEquip.EquipStatusRow
---@field Delta Engine.PlainText
---@field Label Engine.PlainText
---@field Root  Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.WindowEquip.EquipStatusRow

---@class Source.UI.Parts.WindowEquip.EquipStatusRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowEquip.EquipStatusRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowEquip.EquipStatusRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowEquip.EquipStatusRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
