-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowEquip.WindowEquipSlot

---@class Source.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSlot
---@field Content       Engine.Canvas
---@field Root          Engine.Canvas
---@field SlotList      Engine.ListView
---@field SlotScrollBox Engine.ScrollBox
---@field WindowFrame   Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSlot
---@field SlotPlaceholder1 Source.UI.Parts.WindowEquip.EquipSlotRow
---@field SlotPlaceholder2 Source.UI.Parts.WindowEquip.EquipSlotRow
---@field SlotPlaceholder3 Source.UI.Parts.WindowEquip.EquipSlotRow
---@field SlotPlaceholder4 Source.UI.Parts.WindowEquip.EquipSlotRow

---@class Source.UI.Parts.WindowEquip.WindowEquipSlot: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSlot
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSlot
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowEquip.WindowEquipSlot
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
