-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowEquip.WindowEquipStatusPane

---@class Source.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipStatusPane
---@field Content     Engine.Canvas
---@field Root        Engine.Canvas
---@field WindowFrame Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipStatusPane
---@field StatusAsset Source.UI.Parts.WindowEquip.WindowEquipStatus

---@class Source.UI.Parts.WindowEquip.WindowEquipStatusPane: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipStatusPane
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipStatusPane
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowEquip.WindowEquipStatusPane
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
