-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Text.ClusterGrouping
local enum = {
    Character = (1 --[[@as sf.Text.ClusterGrouping]]),
    Grapheme = (0 --[[@as sf.Text.ClusterGrouping]]),
    None = (2 --[[@as sf.Text.ClusterGrouping]]),
}

return enum
