-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Text.TextOrientation
local enum = {
    BottomToTop = (2 --[[@as sf.Text.TextOrientation]]),
    Default = (0 --[[@as sf.Text.TextOrientation]]),
    TopToBottom = (1 --[[@as sf.Text.TextOrientation]]),
}

return enum
