-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Text.TextDirection
local enum = {
    BottomToTop = (4 --[[@as sf.Text.TextDirection]]),
    LeftToRight = (1 --[[@as sf.Text.TextDirection]]),
    RightToLeft = (2 --[[@as sf.Text.TextDirection]]),
    TopToBottom = (3 --[[@as sf.Text.TextDirection]]),
    Unspecified = (0 --[[@as sf.Text.TextDirection]]),
}

return enum
