-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

return {
    Bat = "Bat",
    BigWizard = "BigWizard",
    GhostSoldier = "GhostSoldier",
    GreatIron = "GreatIron",
    Knight = "Knight",
    Mage = "Mage",
    Rock = "Rock",
    Skeleton = "Skeleton",
    Slime = "Slime",
    WhiteKing = "WhiteKing",
    Wizard = "Wizard",
}
