-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

---@enum Enums.GeneralData.Equip
local Equip = {
    HuiMu = "HuiMu",
    HuiRen = "HuiRen",
    JingMu = "JingMu",
    YuRen = "YuRen",
}

return Equip
