-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.ConfigWindow.ConfigSliderRow

---@class Source.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSliderRow
---@field Label     Engine.PlainText
---@field Root      Engine.Canvas
---@field Slider    Engine.Slider
---@field ValueText Engine.PlainText

---@class Source.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSliderRow

---@class Source.UI.Parts.ConfigWindow.ConfigSliderRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSliderRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSliderRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.ConfigWindow.ConfigSliderRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
