-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.ConfigWindow.ConfigSettingRow

---@class Source.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSettingRow
---@field DropBox Engine.DropBox
---@field Label   Engine.PlainText
---@field Root    Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSettingRow

---@class Source.UI.Parts.ConfigWindow.ConfigSettingRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSettingRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSettingRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.ConfigWindow.ConfigSettingRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
