-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.ConfigWindow.ConfigSliderRow

---@class Internal.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSliderRow
---@field Label     Engine.PlainText
---@field Root      Engine.Canvas
---@field Slider    Engine.Slider
---@field ValueText Engine.PlainText

---@class Internal.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSliderRow

---@class Internal.UI.Parts.ConfigWindow.ConfigSliderRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSliderRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSliderRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.ConfigWindow.ConfigSliderRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
