-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.ConfigWindow.ConfigSettingRow

---@class Internal.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSettingRow
---@field DropBox Engine.DropBox
---@field Label   Engine.PlainText
---@field Root    Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSettingRow

---@class Internal.UI.Parts.ConfigWindow.ConfigSettingRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSettingRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSettingRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.ConfigWindow.ConfigSettingRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
