-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.ConfigWindow.ConfigCheckBoxRow

---@class Internal.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigCheckBoxRow
---@field CheckBox Engine.CheckBox
---@field Label    Engine.PlainText
---@field Root     Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigCheckBoxRow

---@class Internal.UI.Parts.ConfigWindow.ConfigCheckBoxRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigCheckBoxRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigCheckBoxRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.ConfigWindow.ConfigCheckBoxRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
