-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Http.Request.Method
local enum = {
    Delete = (4 --[[@as sf.Http.Request.Method]]),
    Get = (0 --[[@as sf.Http.Request.Method]]),
    Head = (2 --[[@as sf.Http.Request.Method]]),
    Post = (1 --[[@as sf.Http.Request.Method]]),
    Put = (3 --[[@as sf.Http.Request.Method]]),
}

return enum
