-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowEnemyBook.SpecialDisplay

---@class Source.UIBase.GeneratedControls.Parts.WindowEnemyBook.SpecialDisplay
---@field Content  Engine.Canvas
---@field Icon     Engine.FunctionalImage
---@field IconArea Engine.Canvas
---@field Root     Engine.Canvas
---@field Text     Engine.PlainText

---@class Source.UIBase.GeneratedAssets.Parts.WindowEnemyBook.SpecialDisplay

---@class Source.UI.Parts.WindowEnemyBook.SpecialDisplay: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowEnemyBook.SpecialDisplay
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowEnemyBook.SpecialDisplay
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowEnemyBook.SpecialDisplay
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
