-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowItem.ItemRow
local View = {}

View.assetKey = "Parts/WindowItem/ItemRow"
View.designSize = sf.Vector2f.new(32, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Count = assert(self.instance:requireControl("Count")),
        Icon = assert(self.instance:requireControl("Icon")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowItem.ItemRow
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowItem.ItemRow
    self.assets = assets
end

return class(View, UiView)
