-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.Title.CommandWindow

---@class Internal.UIBase.GeneratedControls.Parts.Title.CommandWindow
---@field CommandContent     Engine.Canvas
---@field CommandList        Engine.ListView
---@field CommandScrollBox   Engine.ScrollBox
---@field CommandWindowFrame Engine.Window
---@field Root               Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.Title.CommandWindow
---@field TitleCommand1   Internal.UI.Parts.Shared.CommandRow
---@field TitleCommand2   Internal.UI.Parts.Shared.CommandRow
---@field TitleCommand3   Internal.UI.Parts.Shared.CommandRow
---@field TitleCommand4   Internal.UI.Parts.Shared.CommandRow
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.Title.CommandWindow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.Title.CommandWindow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.Title.CommandWindow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.Title.CommandWindow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
