-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowFloorTeleporter.Command

---@brief Command list displaying visited maps in the current region.
---@class Source.Windows.WindowFloorMapCommand: Source.Windows.Base.WindowSelectable, Source.UIBase.Ui.Window
---@field ui Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand
local Window = {}

---@brief Construct the floor map command list.
---
--- - @param owner The parent floor teleporter coordinator.
---@param owner Source.Windows.WindowFloorTeleporter
---@return Source.Windows.WindowFloorMapCommand
function Window.new(owner) end

---@brief Construct the floor map command list.
---
--- - @param owner The parent floor teleporter coordinator.
---@param owner Source.Windows.WindowFloorTeleporter
---@param ui    Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@return Source.Windows.WindowFloorMapCommand
function Window.FromView(ui, owner) end

function Window:activateTelepointSelector() end

function Window:afterTick() end

---@brief Get the selected region map key.
---
--- - @return The selected map key, or nil when no map is selected.
---@return string | nil
function Window:getCurrentMapKey() end

---@param index integer | nil
function Window:notifyMapIndexMaybeChanged(index) end

function Window:onReturn() end

---@param deltaTime number
function Window:onTick(deltaTime) end

---@brief Rebuild the list from map key/name pairs.
---
--- - @param entries Region map entries to display.
---@param entries table
function Window:refreshMaps(entries) end

function Window:refreshRows() end

return Window
