-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowSaveLoad.WindowSaveTabs
local View = {}

View.assetKey = "Parts/WindowSaveLoad/WindowSaveTabs"
View.designSize = sf.Vector2f.new(416, 64)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        Tabs = assert(self.instance:requireControl("Tabs")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveTabs
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveTabs
    self.assets = assets
end

return class(View, UiView)
