-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowSaveLoad.WindowSaveDetail
local View = {}

View.assetKey = "Parts/WindowSaveLoad/WindowSaveDetail"
View.designSize = sf.Vector2f.new(256, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        Thumbnail = assert(self.instance:requireControl("Thumbnail")),
        TimestampText = assert(self.instance:requireControl("TimestampText")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveDetail
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveDetail
    self.assets = assets
end

return class(View, UiView)
