-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowSaveLoad.Detail

---@brief Save-file detail panel showing the current slot's screenshot and timestamp.
---
--- Renders the snapshot horizontally filling the content area at a 4:3 ratio
--- and displays the file's last-modified timestamp underneath. Loading, empty
--- and failed slots display a status message. Native previews are read in the background.
---@class Source.Windows.WindowSaveDetail: Source.Windows.Base.WindowBase, Source.UIBase.Ui.Window
---@field ui Source.UI.Parts.WindowSaveLoad.WindowSaveDetail
local Window = {}

---@brief Construct the detail panel.
---
---@return Source.Windows.WindowSaveDetail
function Window.new() end

---@brief Construct the detail panel.
---
---@param ui Source.UI.Parts.WindowSaveLoad.WindowSaveDetail
---@return Source.Windows.WindowSaveDetail
function Window.FromView(ui) end

function Window:dispose() end

---@param deltaTime number
function Window:onTick(deltaTime) end

---@brief Force-refresh the panel against the current slot's save file.
function Window:refresh() end

---@param modificationTime number
function Window:setModificationTime(modificationTime) end

---@param enabled boolean
function Window:setPreviewEnabled(enabled) end

---@brief Set the slot index to display, or ``nil`` to clear the panel.
---
--- - @param slot Zero-based slot index or ``nil``.
---@param slot integer | nil
function Window:setSlot(slot) end

---@param text string
function Window:setTimestamp(text) end

return Window
