-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowSaveLoad.Tabs

---@brief Non-focusable load/save tab window.
---@class Source.Windows.WindowSaveTabs: Source.Windows.Base.WindowBase, Source.UIBase.Ui.Window
---@field ui Source.UI.Parts.WindowSaveLoad.WindowSaveTabs
local Window = {}

---@param owner Source.Windows.WindowSaveLoad
---@return Source.Windows.WindowSaveTabs
function Window.new(owner) end

---@param owner Source.Windows.WindowSaveLoad
---@param ui    Source.UI.Parts.WindowSaveLoad.WindowSaveTabs
---@return Source.Windows.WindowSaveTabs
function Window.FromView(ui, owner) end

function Window:bind() end

function Window:dispose() end

---@return boolean
function Window:handleNavigationInput() end

---@param index integer
function Window:onSelectedIndexChanged(index) end

function Window:refresh() end

return Window
