-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.GameOver

---@class Internal.UIBase.GeneratedControls.GameOver
---@field Background Engine.SolidRect
---@field Message    Engine.PlainText
---@field Root       Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.GameOver

---@class Internal.UI.GameOver: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.GameOver
---@field assets   Internal.UIBase.GeneratedAssets.GameOver
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.GameOver
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
