-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Init

---@class Internal.UIBase.GeneratedControls.Init
---@field Background  Engine.Image
---@field ProgressBar Engine.ProgressBar
---@field Root        Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Init

---@class Internal.UI.Init: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Init
---@field assets   Internal.UIBase.GeneratedAssets.Init
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Init
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
