-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Title

---@class Internal.UIBase.GeneratedControls.Title
---@field Background Engine.Image
---@field Root       Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Title
---@field CommandPanel Internal.UI.Parts.Title.CommandWindow

---@class Internal.UI.Title: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Title
---@field assets   Internal.UIBase.GeneratedAssets.Title
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Title
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
