-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowItem

---@class Internal.UIBase.GeneratedControls.WindowItem
---@field Content         Engine.Canvas
---@field Description     Engine.PlainText
---@field DescriptionArea Engine.Canvas
---@field ItemList        Engine.ListView
---@field ItemName        Engine.PlainText
---@field ItemScrollBox   Engine.ScrollBox
---@field Root            Engine.Canvas
---@field WindowFrame     Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowItem
---@field ItemPlaceholder1  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder10 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder11 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder12 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder13 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder14 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder15 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder16 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder17 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder18 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder19 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder2  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder20 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder21 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder22 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder23 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder24 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder25 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder26 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder27 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder28 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder29 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder3  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder30 Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder4  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder5  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder6  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder7  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder8  Internal.UI.Parts.WindowItem.ItemRow
---@field ItemPlaceholder9  Internal.UI.Parts.WindowItem.ItemRow
---@field WindowChrome      Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark   Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.WindowItem: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowItem
---@field assets   Internal.UIBase.GeneratedAssets.WindowItem
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowItem
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
