-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowMagicDoor

---@class Internal.UIBase.GeneratedControls.WindowMagicDoor
---@field Count       Engine.PlainText
---@field Icon        Engine.Image
---@field Multiply    Engine.PlainText
---@field Root        Engine.Canvas
---@field WindowFrame Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowMagicDoor

---@class Internal.UI.WindowMagicDoor: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowMagicDoor
---@field assets   Internal.UIBase.GeneratedAssets.WindowMagicDoor
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowMagicDoor
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
