-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowHotkeys

---@class Internal.UIBase.GeneratedControls.WindowHotkeys
---@field Root        Engine.Canvas
---@field Rows        Engine.WrapBox
---@field Scroll      Engine.ScrollBox
---@field WindowFrame Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowHotkeys

---@class Internal.UI.WindowHotkeys: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowHotkeys
---@field assets   Internal.UIBase.GeneratedAssets.WindowHotkeys
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowHotkeys
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
