-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowAttrShop

---@class Internal.UIBase.GeneratedControls.WindowAttrShop
---@field AbilityList      Engine.ListView
---@field AbilityScrollBox Engine.ScrollBox
---@field Avatar           Engine.FunctionalImage
---@field Content          Engine.Canvas
---@field Description      Engine.FunctionalPlainText
---@field Price            Engine.FunctionalPlainText
---@field Root             Engine.Canvas
---@field ShopName         Engine.FunctionalPlainText
---@field WindowFrame      Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowAttrShop
---@field AbilityItem1    Internal.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem2    Internal.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem3    Internal.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem4    Internal.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem5    Internal.UI.Parts.WindowAttrShop.AttrShopRow
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.WindowAttrShop: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowAttrShop
---@field assets   Internal.UIBase.GeneratedAssets.WindowAttrShop
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowAttrShop
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
