-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowEnemyEncyclopedia

---@class Internal.UIBase.GeneratedControls.WindowEnemyEncyclopedia
---@field Content          Engine.Canvas
---@field Description      Engine.PlainText
---@field DescriptionArea  Engine.Canvas
---@field InfoLayer        Engine.ListView
---@field Name             Engine.FunctionalPlainText
---@field NameArea         Engine.Canvas
---@field Portrait         Engine.CharacterView
---@field Root             Engine.Canvas
---@field SpecialList      Engine.ListView
---@field SpecialScrollBox Engine.ScrollBox
---@field WindowFrame      Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowEnemyEncyclopedia
---@field InfoItem1       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem2       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem3       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem4       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem5       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem6       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem7       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem8       Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field SpecialItem1    Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field SpecialItem2    Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field SpecialItem3    Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.WindowEnemyEncyclopedia: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowEnemyEncyclopedia
---@field assets   Internal.UIBase.GeneratedAssets.WindowEnemyEncyclopedia
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowEnemyEncyclopedia
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
