-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowEnemyBook

---@class Internal.UIBase.GeneratedControls.WindowEnemyBook
---@field Content        Engine.Canvas
---@field EnemyList      Engine.ListView
---@field EnemyScrollBox Engine.ScrollBox
---@field Root           Engine.Canvas
---@field WindowFrame    Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowEnemyBook
---@field EnemyItem1      Internal.UI.Parts.WindowEnemyBook.WindowEnemyBookCell
---@field EnemyItem2      Internal.UI.Parts.WindowEnemyBook.WindowEnemyBookCell
---@field EnemyItem3      Internal.UI.Parts.WindowEnemyBook.WindowEnemyBookCell
---@field EnemyItem4      Internal.UI.Parts.WindowEnemyBook.WindowEnemyBookCell
---@field EnemyItem5      Internal.UI.Parts.WindowEnemyBook.WindowEnemyBookCell
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.WindowEnemyBook: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowEnemyBook
---@field assets   Internal.UIBase.GeneratedAssets.WindowEnemyBook
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowEnemyBook
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
