-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowFloorTeleporter

---@class Internal.UIBase.GeneratedControls.WindowFloorTeleporter
---@field Root Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.WindowFloorTeleporter
---@field CommandAsset Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field PreviewAsset Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapPreview

---@class Internal.UI.WindowFloorTeleporter: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowFloorTeleporter
---@field assets   Internal.UIBase.GeneratedAssets.WindowFloorTeleporter
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowFloorTeleporter
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
