-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowShop

---@class Internal.UIBase.GeneratedControls.WindowShop
---@field Root Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.WindowShop
---@field DetailAsset Internal.UI.Parts.WindowShop.WindowShopDetail
---@field ItemAsset   Internal.UI.Parts.WindowShop.WindowShopItem
---@field TabsAsset   Internal.UI.Parts.WindowShop.WindowShopTabs

---@class Internal.UI.WindowShop: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowShop
---@field assets   Internal.UIBase.GeneratedAssets.WindowShop
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowShop
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
