-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowPlayerName

---@class Internal.UIBase.GeneratedControls.WindowPlayerName
---@field ConfirmButton Engine.Button
---@field ConfirmLabel  Engine.PlainText
---@field Content       Engine.Canvas
---@field Error         Engine.PlainText
---@field NameInput     Engine.TextBox
---@field Prompt        Engine.PlainText
---@field Root          Engine.Canvas
---@field WindowFrame   Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowPlayerName
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.WindowPlayerName: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowPlayerName
---@field assets   Internal.UIBase.GeneratedAssets.WindowPlayerName
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowPlayerName
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
