-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowMessage

---@class Internal.UIBase.GeneratedControls.WindowMessage
---@field ConfirmLayer  Engine.FunctionalImage
---@field Content       Engine.Canvas
---@field DialogBounds  Engine.Canvas
---@field MessageBody   Engine.Canvas
---@field MessageList   Engine.ListView
---@field MessageText   Engine.RichText
---@field NameArea      Engine.Canvas
---@field NameText      Engine.PlainText
---@field Panel         Engine.Canvas
---@field Root          Engine.Canvas
---@field SelectionList Engine.ListView
---@field WindowFrame   Engine.Window

---@class Internal.UIBase.GeneratedAssets.WindowMessage
---@field SelectionItem1  Internal.UI.Parts.WindowMessage.MessageOptionRow
---@field SelectionItem2  Internal.UI.Parts.WindowMessage.MessageOptionRow
---@field SelectionItem3  Internal.UI.Parts.WindowMessage.MessageOptionRow
---@field SelectionItem4  Internal.UI.Parts.WindowMessage.MessageOptionRow
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.WindowMessage: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowMessage
---@field assets   Internal.UIBase.GeneratedAssets.WindowMessage
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowMessage
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
