-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowSaveLoad

---@class Internal.UIBase.GeneratedControls.WindowSaveLoad
---@field Root Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.WindowSaveLoad
---@field DetailAsset Internal.UI.Parts.WindowSaveLoad.WindowSaveDetail
---@field SlotAsset   Internal.UI.Parts.WindowSaveLoad.WindowSaveSlot
---@field TabsAsset   Internal.UI.Parts.WindowSaveLoad.WindowSaveTabs

---@class Internal.UI.WindowSaveLoad: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowSaveLoad
---@field assets   Internal.UIBase.GeneratedAssets.WindowSaveLoad
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowSaveLoad
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
