-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.WindowTutorial

---@class Internal.UIBase.GeneratedControls.WindowTutorial
---@field Border        Engine.SolidRect
---@field BottomCurtain Engine.SolidRect
---@field Explanation   Engine.PlainText
---@field LeftCurtain   Engine.SolidRect
---@field RightCurtain  Engine.SolidRect
---@field Root          Engine.Canvas
---@field TopCurtain    Engine.SolidRect

---@class Internal.UIBase.GeneratedAssets.WindowTutorial

---@class Internal.UI.WindowTutorial: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.WindowTutorial
---@field assets   Internal.UIBase.GeneratedAssets.WindowTutorial
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.WindowTutorial
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
