-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
local View = {}

View.assetKey = "Parts/WindowEnemyEncyclopedia/EnemyEncyclopediaInfoPair"
View.designSize = sf.Vector2f.new(200, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Label = assert(self.instance:requireControl("Label")),
        Root = assert(self.instance:requireControl("Root")),
        Value = assert(self.instance:requireControl("Value"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
    self.assets = assets
end

return class(View, UiView)
