-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowEquip.EquipSlotRow

---@class Internal.UIBase.GeneratedControls.Parts.WindowEquip.EquipSlotRow
---@field Icon  Engine.FunctionalImage
---@field Label Engine.PlainText
---@field Root  Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.WindowEquip.EquipSlotRow

---@class Internal.UI.Parts.WindowEquip.EquipSlotRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowEquip.EquipSlotRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowEquip.EquipSlotRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowEquip.EquipSlotRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
