-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowEquip.WindowEquipSelect

---@class Internal.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSelect
---@field Content         Engine.Canvas
---@field Root            Engine.Canvas
---@field SelectList      Engine.ListView
---@field SelectScrollBox Engine.ScrollBox
---@field WindowFrame     Engine.Window

---@class Internal.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSelect
---@field EquipPlaceholder1  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder10 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder11 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder12 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder13 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder14 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder15 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder16 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder17 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder18 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder19 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder2  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder20 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder21 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder22 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder23 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder24 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder25 Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder3  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder4  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder5  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder6  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder7  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder8  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field EquipPlaceholder9  Internal.UI.Parts.WindowEquip.EquipItemRow
---@field WindowChrome       Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark    Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.WindowEquip.WindowEquipSelect: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSelect
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSelect
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowEquip.WindowEquipSelect
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
