-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowEquip.WindowEquipSlot

---@class Internal.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSlot
---@field Content       Engine.Canvas
---@field Root          Engine.Canvas
---@field SlotList      Engine.ListView
---@field SlotScrollBox Engine.ScrollBox
---@field WindowFrame   Engine.Window

---@class Internal.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSlot
---@field SlotPlaceholder1 Internal.UI.Parts.WindowEquip.EquipSlotRow
---@field SlotPlaceholder2 Internal.UI.Parts.WindowEquip.EquipSlotRow
---@field SlotPlaceholder3 Internal.UI.Parts.WindowEquip.EquipSlotRow
---@field SlotPlaceholder4 Internal.UI.Parts.WindowEquip.EquipSlotRow
---@field WindowChrome     Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark  Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.WindowEquip.WindowEquipSlot: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSlot
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSlot
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowEquip.WindowEquipSlot
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
