-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowEquip.WindowEquipStatus

---@class Internal.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipStatus
---@field BreathMinus     Engine.PlainText
---@field ChangeList      Engine.ListView
---@field Description     Engine.PlainText
---@field DescriptionArea Engine.Canvas
---@field FatiguePlus     Engine.PlainText
---@field ItemName        Engine.PlainText
---@field Root            Engine.Canvas
---@field SkillStatsArea  Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipStatus
---@field StatusPlaceholder1 Internal.UI.Parts.WindowEquip.EquipStatusRow
---@field StatusPlaceholder2 Internal.UI.Parts.WindowEquip.EquipStatusRow
---@field StatusPlaceholder3 Internal.UI.Parts.WindowEquip.EquipStatusRow

---@class Internal.UI.Parts.WindowEquip.WindowEquipStatus: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipStatus
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipStatus
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowEquip.WindowEquipStatus
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
