---@meta Source.Configs.GeneralDataTypes
--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

---@class Source.Configs.GeneralDataTypes.ClassAttributeSet: GlobalCore.AttributeSet
---@field ID              string
---@field ATTRIBUTE_NAMES string[]
---@field SCHEMA          table<string, { type: string|table, default: any }>
---@field name            string
---@field desc            string
---@field slot            table<string, string>
---@type Source.Configs.GeneralDataTypes.ClassAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.ClassAttributeSet>
local ClassAttributeSet = {}

---@class Source.Configs.GeneralDataTypes.EnemyAttributeSet: GlobalCore.AttributeSet
---@field ID              string
---@field ATTRIBUTE_NAMES string[]
---@field SCHEMA          table<string, { type: string|table, default: any }>
---@field name            string
---@field desc            string
---@field MAXHP           integer
---@field ATK             integer
---@field DEF             integer
---@field EXP             integer
---@field GOLD            integer
---@field drops           table<string, sf.Vector2i>
---@field special         table<string, any>
---@field ANIMATION_KEY   string
---@type Source.Configs.GeneralDataTypes.EnemyAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.EnemyAttributeSet>
local EnemyAttributeSet = {}

---@class Source.Configs.GeneralDataTypes.EquipAttributeSet: GlobalCore.AttributeSet
---@field ID              string
---@field ATTRIBUTE_NAMES string[]
---@field SCHEMA          table<string, { type: string|table, default: any }>
---@field name            string
---@field desc            string
---@field icon            string
---@field slot            string
---@field attrPlus        table<string, integer>
---@type Source.Configs.GeneralDataTypes.EquipAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.EquipAttributeSet>
local EquipAttributeSet = {}

---@class Source.Configs.GeneralDataTypes.ItemAttributeSet: GlobalCore.AttributeSet
---@field ID              string
---@field ATTRIBUTE_NAMES string[]
---@field SCHEMA          table<string, { type: string|table, default: any }>
---@field name            string
---@field desc            string
---@field usable          boolean
---@field price           integer
---@field icon            string
---@field cost            boolean
---@type Source.Configs.GeneralDataTypes.ItemAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.ItemAttributeSet>
local ItemAttributeSet = {}

---@class Source.Configs.GeneralDataTypes.PlayerAttributeSet: GlobalCore.AttributeSet
---@field ID              string
---@field ATTRIBUTE_NAMES string[]
---@field SCHEMA          table<string, { type: string|table, default: any }>
---@field name            string
---@field desc            string
---@field CLASS           string
---@field MAXHP           integer
---@field HP              integer
---@field ATK             integer
---@field DEF             integer
---@field EXP             integer
---@field GOLD            integer
---@field LEVEL           integer
---@field ANIMATION_KEY   string
---@type Source.Configs.GeneralDataTypes.PlayerAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.PlayerAttributeSet>
local PlayerAttributeSet = {}

---@class Source.Configs.GeneralDataTypes.SpecialAttributeSet: GlobalCore.AttributeSet
---@field ID              string
---@field ATTRIBUTE_NAMES string[]
---@field SCHEMA          table<string, { type: string|table, default: any }>
---@field name            string
---@field desc            string
---@field icon            string
---@type Source.Configs.GeneralDataTypes.SpecialAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.SpecialAttributeSet>
local SpecialAttributeSet = {}

---@class Source.Configs.GeneralDataTypes.StateAttributeSet: GlobalCore.AttributeSet
---@field ID              string
---@field ATTRIBUTE_NAMES string[]
---@field SCHEMA          table<string, { type: string|table, default: any }>
---@field name            string
---@field desc            string
---@field icon            string
---@field stackable       boolean
---@type Source.Configs.GeneralDataTypes.StateAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.StateAttributeSet>
local StateAttributeSet = {}

---@class Source.Configs.GeneralDataTypes.Module
---@field Types               table<string, Class.ClassType<GlobalCore.AttributeSet>>
---@field ClassAttributeSet   Source.Configs.GeneralDataTypes.ClassAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.ClassAttributeSet>
---@field EnemyAttributeSet   Source.Configs.GeneralDataTypes.EnemyAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.EnemyAttributeSet>
---@field EquipAttributeSet   Source.Configs.GeneralDataTypes.EquipAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.EquipAttributeSet>
---@field ItemAttributeSet    Source.Configs.GeneralDataTypes.ItemAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.ItemAttributeSet>
---@field PlayerAttributeSet  Source.Configs.GeneralDataTypes.PlayerAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.PlayerAttributeSet>
---@field SpecialAttributeSet Source.Configs.GeneralDataTypes.SpecialAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.SpecialAttributeSet>
---@field StateAttributeSet   Source.Configs.GeneralDataTypes.StateAttributeSet & Class.ClassType<Source.Configs.GeneralDataTypes.StateAttributeSet>
local GeneralDataTypes = {}

---@param typeName   string
---@param memberId   string
---@param memberData table<string, any>
---@return GlobalCore.AttributeSet
function GeneralDataTypes.Create(typeName, memberId, memberData) end

return GeneralDataTypes
