---@meta Source.Configs.GeneralEnum
--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.
--- @brief General Data key constants.

--- @brief General Data table keys.
---@class Source.Configs.GeneralEnum.GeneralDataKey
---@field Class string
---@field Enemy string
---@field Equip string
---@field Item string
---@field Player string
---@field Special string
---@field State string
---@type Source.Configs.GeneralEnum.GeneralDataKey
local GeneralDataKey = {}

--- @brief Class member keys.
---@class Source.Configs.GeneralEnum.Class
---@field Princess string
---@field Warrior string
---@type Source.Configs.GeneralEnum.Class
local Class = {}

--- @brief Enemy member keys.
---@class Source.Configs.GeneralEnum.Enemy
---@field E00_shilaimu string
---@field E01_hongseshilaimu string
---@field E02_bianfu string
---@field E03_shuishushi string
---@field E04_shouwei string
---@field E05_leishushi string
---@field E06_kulou string
---@field E07_heiseshilaimu string
---@field E08_shilaimuren string
---@field E09_sangshi string
---@field E10_dabianfu string
---@field E11_shitouguai string
---@field E12_qishi string
---@field E13_shuangshoujianshi string
---@field E14_kuloushibing string
---@field E15_kuloujiazhoushi string
---@field E16_zhongjishouwei string
---@field E17_tieqishi string
---@field E18_hongbianfu string
---@field E19_zhangyuzai string
---@field E20_shilaimukuangren string
---@field E21_shilaimuwang string
---@field E22_yanshushi string
---@field E23_sangshijianshi string
---@field E24_gongbing string
---@field E25_moyushilaimu string
---@field E26_shixuebianfu string
---@field E27_kulouxiaoduizhang string
---@field E28_fengwushi string
---@field E29_xieyanshilaimu string
---@field E30_baiyiwei string
---@field E31_huiqishi string
---@field E32_youmingfashi string
---@field E33_shilaimu string
---@field E34_dashilaimu string
---@field E35_bianfu string
---@field E36_fashi string
---@field E37_dusangshi string
---@field E38_dubianfu string
---@field E39_kuloutoumu string
---@field E40_kulou string
---@field E41_jiantouguai string
---@field E42_shouren string
---@field E43_xieshilaimu string
---@field E44_gaojigongbing string
---@field E45_shuairuojinweibing string
---@field E46_kuangbaojinweibing string
---@field E47_kuairen string
---@field E48_qingyiwei string
---@field E49_mowangshiwei string
---@field E50_xunjiequan string
---@field E51_gangtieguai string
---@field E52_gaojishouwei string
---@field E53_tieguai string
---@field E54_shuiyinren string
---@field E55_zhongjiefashi string
---@field E56_buwendingjixie string
---@field E57_zhuangjiakulou string
---@field E58_zhongxingbianfu string
---@field E59_hanbingshilaimu string
---@field E60_duzhangyu string
---@field E61_lieyansangshi string
---@field E62_dongsigu string
---@field E63_zhengguijinweibing string
---@field E64_tiejiajinweibing string
---@field E65_jinweiqishi string
---@field E66_guihuo string
---@field E67_shourenshibing string
---@field E68_yanwushi string
---@field E69_hongyimowang string
---@field E70_xixueguibojue string
---@field E71_zhongchuikulou string
---@field E72_fengsugou string
---@field E73_daxingbianfu string
---@field E74_shuairuozhangyu string
---@field E75_jihanwushi string
---@field E76_chushouzhiwu string
---@field E77_gaojiefashi string
---@field E78_kuloujianshi string
---@field E79_judabazhaoyu string
---@field E80_molong string
---@field E81_silingqishi string
---@field E82_xuefashi string
---@field E83_shilaimuxiuluo string
---@field E84_fengkuangchushou string
---@field E85_huangjiaqiangbing string
---@field E86_longfu string
---@field E87_jianshenfabi string
---@field E88_doushengaoba string
---@field E89_jianwang string
---@field E90_jianshenshashi string
---@field E91_moshenxieduo string
---@field E92_yonghengzhiyao string
---@type Source.Configs.GeneralEnum.Enemy
local Enemy = {}

--- @brief Equip member keys.
---@class Source.Configs.GeneralEnum.Equip
---@field HuiMu string
---@field HuiRen string
---@type Source.Configs.GeneralEnum.Equip
local Equip = {}

--- @brief Item member keys.
---@class Source.Configs.GeneralEnum.Item
---@field Bottle150 string
---@field Bottle400 string
---@field BreakIce string
---@field BreakLava string
---@field BreakWall string
---@field CentreFly string
---@field ClearWall string
---@field DivineShield string
---@field DownFly string
---@field EnemyBook string
---@field EternalIce string
---@field ItemBag string
---@field KEY_B string
---@field KEY_R string
---@field KEY_Y string
---@field PoisonedEase string
---@field PoisonedRelease string
---@field ReflectionNet string
---@field SDoor string
---@field Teleport string
---@field UpFly string
---@field WeakEase string
---@field WeakRelease string
---@type Source.Configs.GeneralEnum.Item
local Item = {}

--- @brief Player member keys.
---@class Source.Configs.GeneralEnum.Player
---@field Bravor string
---@field Princess string
---@type Source.Configs.GeneralEnum.Player
local Player = {}

--- @brief Special member keys.
---@class Source.Configs.GeneralEnum.Special
---@field Ambush string
---@field ArmorBreak string
---@field AuraField string
---@field Berserk string
---@field Blockade string
---@field Burn string
---@field BurstFlame string
---@field Compete string
---@field DeathCurse string
---@field Domain string
---@field Ember string
---@field EvilEye string
---@field First string
---@field FixDmg string
---@field Flank string
---@field Frost string
---@field Glacial string
---@field Hard string
---@field Magic string
---@field Mucus string
---@field MultiHit string
---@field Poisoning string
---@field Reborn string
---@field Snowland string
---@field SureKill string
---@field Thunder string
---@field Vampire string
---@field Weaken string
---@type Source.Configs.GeneralEnum.Special
local Special = {}

--- @brief State member keys.
---@class Source.Configs.GeneralEnum.State
---@field Poisoned string
---@field Weak string
---@type Source.Configs.GeneralEnum.State
local State = {}

return {
    GeneralDataKey = GeneralDataKey,
    Class = Class,
    Enemy = Enemy,
    Equip = Equip,
    Item = Item,
    Player = Player,
    Special = Special,
    State = State,
}
