-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.PlayerAttrHUD.Avatar

---@class Internal.UIBase.GeneratedControls.Parts.PlayerAttrHUD.Avatar
---@field AvatarButton Engine.Button

---@class Internal.UIBase.GeneratedAssets.Parts.PlayerAttrHUD.Avatar

---@class Internal.UI.Parts.PlayerAttrHUD.Avatar: Internal.UIBase.UiView
---@field root     Engine.Button
---@field controls Internal.UIBase.GeneratedControls.Parts.PlayerAttrHUD.Avatar
---@field assets   Internal.UIBase.GeneratedAssets.Parts.PlayerAttrHUD.Avatar
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.PlayerAttrHUD.Avatar
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
