-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowEquip.Slot

---@class Source.Windows.WindowEquipSlot: Source.Windows.Base.WindowSelectable, Source.UIBase.Ui.Window
---@field ui         Source.UI.Parts.WindowEquip.WindowEquipSlot
---@field ROW_HEIGHT integer
local Window = {}

---@brief Construct the equipped-slot window.
---
--- - @param player The player instance.
--- - @param windowEquipSelect The available-equip window to refresh on slot change.
--- - @param windowEquipStatus The detail window to refresh on slot change.
--- - @param onClose Optional callback invoked when the window is closed.
---@param player            Source.Player.Player
---@param windowEquipSelect Source.Windows.WindowEquipSelect | nil
---@param windowEquipStatus Source.Windows.WindowEquipStatus | nil
---@param onClose           function | nil
---@return Source.Windows.WindowEquipSlot
function Window.new(player, windowEquipSelect, windowEquipStatus, onClose) end

---@brief Construct the equipped-slot window.
---
--- - @param player The player instance.
--- - @param windowEquipSelect The available-equip window to refresh on slot change.
--- - @param windowEquipStatus The detail window to refresh on slot change.
--- - @param onClose Optional callback invoked when the window is closed.
---@param player            Source.Player.Player
---@param windowEquipSelect Source.Windows.WindowEquipSelect | nil
---@param windowEquipStatus Source.Windows.WindowEquipStatus | nil
---@param onClose           function | nil
---@param ui                Source.UI.Parts.WindowEquip.WindowEquipSlot
---@return Source.Windows.WindowEquipSlot
function Window.FromView(ui, player, windowEquipSelect, windowEquipStatus, onClose) end

---@brief Close the slot window.
function Window:close() end

function Window:closeChildWindows() end

function Window:focusSelectWindow() end

---@return string | nil
function Window:getCurrentSlotKey() end

---@param slotKey string
---@return sf.Texture | nil, string
function Window:getSlotCellData(slotKey) end

function Window:notifySlotChanged() end

function Window:onReturn() end

---@brief Update slot window and notify slot change on index change.
---
--- - @param deltaTime Elapsed time in seconds.
---@param deltaTime number
function Window:onTick(deltaTime) end

---@brief Open the slot window with the first slot and its first equipment candidate selected.
function Window:open() end

function Window:redrawIfVisible() end

function Window:refreshListLayout() end

---@brief Refresh localised slot and status text without changing the selected slot or equipment candidate.
function Window:refreshLocale() end

---@brief Rebuild the slot list from the player's class slot order.
function Window:refreshSlots() end

---@brief Set the available-equip window reference.
---
--- - @param windowEquipSelect The available-equip window.
---@param windowEquipSelect Source.Windows.WindowEquipSelect
function Window:setEquipSelectWindow(windowEquipSelect) end

---@brief Set the equipment detail window reference.
---
--- - @param windowEquipStatus The equipment detail window.
---@param windowEquipStatus Source.Windows.WindowEquipStatus
function Window:setEquipStatusWindow(windowEquipStatus) end

---@param callback function | nil
function Window:setOnCloseCallback(callback) end

---@brief Rebind the player whose equipment slots are displayed.
---@param player Source.Player.Player
function Window:setPlayer(player) end

return Window
