-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.PrimitiveType

---@class Enums.sf.PrimitiveType
---@field LineStrip sf.PrimitiveType
---@field Lines sf.PrimitiveType
---@field Points sf.PrimitiveType
---@field TriangleFan sf.PrimitiveType
---@field TriangleStrip sf.PrimitiveType
---@field Triangles sf.PrimitiveType
---@type Enums.sf.PrimitiveType
local enum = {}

return enum
