-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.State

---@class Enums.sf.State
---@field Fullscreen sf.State
---@field Windowed sf.State
---@type Enums.sf.State
local enum = {}

return enum
