-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.StencilUpdateOperation

---@class Enums.sf.StencilUpdateOperation
---@field Decrement sf.StencilUpdateOperation
---@field Increment sf.StencilUpdateOperation
---@field Invert sf.StencilUpdateOperation
---@field Keep sf.StencilUpdateOperation
---@field Replace sf.StencilUpdateOperation
---@field Zero sf.StencilUpdateOperation
---@type Enums.sf.StencilUpdateOperation
local enum = {}

return enum
