-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Sftp.SessionInfo.HostKey.Type

---@class Enums.sf.Sftp.SessionInfo.HostKey.Type
---@field Dsa sf.Sftp.SessionInfo.HostKey.Type
---@field Ecdsa256 sf.Sftp.SessionInfo.HostKey.Type
---@field Ecdsa384 sf.Sftp.SessionInfo.HostKey.Type
---@field Ecdsa521 sf.Sftp.SessionInfo.HostKey.Type
---@field Ed25519 sf.Sftp.SessionInfo.HostKey.Type
---@field Rsa sf.Sftp.SessionInfo.HostKey.Type
---@field Unknown sf.Sftp.SessionInfo.HostKey.Type
---@type Enums.sf.Sftp.SessionInfo.HostKey.Type
local enum = {}

return enum
