-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.ConfigWindow.ConfigSettingRow
local View = {}

View.assetKey = "Parts/ConfigWindow/ConfigSettingRow"
View.designSize = sf.Vector2f.new(448, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        DropBox = assert(self.instance:requireControl("DropBox")),
        Label = assert(self.instance:requireControl("Label")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSettingRow
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSettingRow
    self.assets = assets
end

return class(View, UiView)
