-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.ConfigWindow.ConfigSliderRow
local View = {}

View.assetKey = "Parts/ConfigWindow/ConfigSliderRow"
View.designSize = sf.Vector2f.new(448, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Label = assert(self.instance:requireControl("Label")),
        Root = assert(self.instance:requireControl("Root")),
        Slider = assert(self.instance:requireControl("Slider")),
        ValueText = assert(self.instance:requireControl("ValueText"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.ConfigWindow.ConfigSliderRow
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.ConfigWindow.ConfigSliderRow
    self.assets = assets
end

return class(View, UiView)
