-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
return {
    DeviceInterruptionBegan = 3,
    DeviceInterruptionEnded = 4,
    DeviceRerouted = 2,
    DeviceStarted = 0,
    DeviceStopped = 1,
    DeviceUnlocked = 5,
}
