-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.PlaybackDevice.Notification
local enum = {
    DeviceInterruptionBegan = (3 --[[@as sf.PlaybackDevice.Notification]]),
    DeviceInterruptionEnded = (4 --[[@as sf.PlaybackDevice.Notification]]),
    DeviceRerouted = (2 --[[@as sf.PlaybackDevice.Notification]]),
    DeviceStarted = (0 --[[@as sf.PlaybackDevice.Notification]]),
    DeviceStopped = (1 --[[@as sf.PlaybackDevice.Notification]]),
    DeviceUnlocked = (5 --[[@as sf.PlaybackDevice.Notification]]),
}

return enum
