-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.Socket.Status

---@class Enums.sf.Socket.Status
---@field Disconnected sf.Socket.Status
---@field Done sf.Socket.Status
---@field Error sf.Socket.Status
---@field NotReady sf.Socket.Status
---@field Partial sf.Socket.Status
---@type Enums.sf.Socket.Status
local enum = {}

return enum
