-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.Shared.WindowBase
local View = {}

View.assetKey = "Parts/Shared/WindowBase"
View.designSize = sf.Vector2f.new(160, 96)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        HintBar = assert(self.instance:requireControl("HintBar")),
        PauseMark = assert(self.instance:requireControl("PauseMark")),
        ReturnButton = assert(self.instance:requireControl("ReturnButton")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.Shared.WindowBase
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.Shared.WindowBase
    self.assets = assets
end

return class(View, UiView)
