-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.sf.PlaybackDevice.Notification

---@class Enums.sf.PlaybackDevice.Notification
---@field DeviceInterruptionBegan sf.PlaybackDevice.Notification
---@field DeviceInterruptionEnded sf.PlaybackDevice.Notification
---@field DeviceRerouted sf.PlaybackDevice.Notification
---@field DeviceStarted sf.PlaybackDevice.Notification
---@field DeviceStopped sf.PlaybackDevice.Notification
---@field DeviceUnlocked sf.PlaybackDevice.Notification
---@type Enums.sf.PlaybackDevice.Notification
local enum = {}

return enum
