-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.Parts.WindowEquip.EquipSlotRow
local View = {}

View.assetKey = "Parts/WindowEquip/EquipSlotRow"
View.designSize = sf.Vector2f.new(128, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Icon = assert(self.instance:requireControl("Icon")),
        Label = assert(self.instance:requireControl("Label")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowEquip.EquipSlotRow
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowEquip.EquipSlotRow
    self.assets = assets
end

return class(View, UiView)
