-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")
local ChildView1 = require("Internal.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Internal.UI.Parts.Shared.WindowPauseMark")
local ChildView3 = require("Internal.UI.Parts.WindowEquip.EquipItemRow")

---@class Internal.UI.Parts.WindowEquip.WindowEquipSelect
local View = {}

View.assetKey = "Parts/WindowEquip/WindowEquipSelect"
View.designSize = sf.Vector2f.new(192, 192)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        SelectList = assert(self.instance:requireControl("SelectList")),
        SelectScrollBox = assert(self.instance:requireControl("SelectScrollBox")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSelect
    self.controls = controls
    local assets = {
        EquipPlaceholder1 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder1")))),
        EquipPlaceholder10 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder10")))),
        EquipPlaceholder11 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder11")))),
        EquipPlaceholder12 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder12")))),
        EquipPlaceholder13 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder13")))),
        EquipPlaceholder14 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder14")))),
        EquipPlaceholder15 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder15")))),
        EquipPlaceholder16 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder16")))),
        EquipPlaceholder17 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder17")))),
        EquipPlaceholder18 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder18")))),
        EquipPlaceholder19 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder19")))),
        EquipPlaceholder2 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder2")))),
        EquipPlaceholder20 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder20")))),
        EquipPlaceholder21 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder21")))),
        EquipPlaceholder22 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder22")))),
        EquipPlaceholder23 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder23")))),
        EquipPlaceholder24 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder24")))),
        EquipPlaceholder25 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder25")))),
        EquipPlaceholder3 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder3")))),
        EquipPlaceholder4 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder4")))),
        EquipPlaceholder5 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder5")))),
        EquipPlaceholder6 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder6")))),
        EquipPlaceholder7 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder7")))),
        EquipPlaceholder8 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder8")))),
        EquipPlaceholder9 = self:own(ChildView3.new(assert(self.instance:requireAsset("EquipPlaceholder9")))),
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSelect
    self.assets = assets
end

return class(View, UiView)
