-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowAttrShop.AttrShopRow

---@class Source.UIBase.GeneratedControls.Parts.WindowAttrShop.AttrShopRow
---@field Label Engine.PlainText
---@field Root  Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.WindowAttrShop.AttrShopRow

---@class Source.UI.Parts.WindowAttrShop.AttrShopRow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowAttrShop.AttrShopRow
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowAttrShop.AttrShopRow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowAttrShop.AttrShopRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
