-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.Shared.WindowChrome

---@class Source.UIBase.GeneratedControls.Parts.Shared.WindowChrome
---@field HintBar      Engine.GamepadHintBar
---@field ReturnButton Engine.Button
---@field Root         Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Parts.Shared.WindowChrome

---@class Source.UI.Parts.Shared.WindowChrome: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.Shared.WindowChrome
---@field assets   Source.UIBase.GeneratedAssets.Parts.Shared.WindowChrome
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.Shared.WindowChrome
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
