-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.Shared.WindowBase

---@class Source.UIBase.GeneratedControls.Parts.Shared.WindowBase
---@field Content      Engine.Canvas
---@field HintBar      Engine.GamepadHintBar
---@field PauseMark    Engine.Image
---@field ReturnButton Engine.Button
---@field Root         Engine.Canvas
---@field WindowFrame  Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.Shared.WindowBase

---@class Source.UI.Parts.Shared.WindowBase: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.Shared.WindowBase
---@field assets   Source.UIBase.GeneratedAssets.Parts.Shared.WindowBase
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.Shared.WindowBase
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
