-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.GameOver
local View = {}

View.assetKey = "GameOver"
View.designSize = sf.Vector2f.new(640, 480)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Background = assert(self.instance:requireControl("Background")),
        Message = assert(self.instance:requireControl("Message")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.GameOver
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.GameOver
    self.assets = assets
end

return class(View, UiView)
