-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Init
local View = {}

View.assetKey = "Init"
View.designSize = sf.Vector2f.new(640, 480)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Background = assert(self.instance:requireControl("Background")),
        ProgressBar = assert(self.instance:requireControl("ProgressBar")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Init
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Init
    self.assets = assets
end

return class(View, UiView)
