-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.PlayerAttrHUD.PlayerStateRow")

---@class Source.UI.PlayerAttrHUD
local View = {}

View.assetKey = "PlayerAttrHUD"
View.designSize = sf.Vector2f.new(144, 388)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        AtkDebuff = assert(self.instance:requireControl("AtkDebuff")),
        AtkLabel = assert(self.instance:requireControl("AtkLabel")),
        AtkValue = assert(self.instance:requireControl("AtkValue")),
        Avatar = assert(self.instance:requireControl("Avatar")),
        DefDebuff = assert(self.instance:requireControl("DefDebuff")),
        DefLabel = assert(self.instance:requireControl("DefLabel")),
        DefValue = assert(self.instance:requireControl("DefValue")),
        ExpLabel = assert(self.instance:requireControl("ExpLabel")),
        ExpValue = assert(self.instance:requireControl("ExpValue")),
        GoldLabel = assert(self.instance:requireControl("GoldLabel")),
        GoldValue = assert(self.instance:requireControl("GoldValue")),
        HpBack = assert(self.instance:requireControl("HpBack")),
        HpFill = assert(self.instance:requireControl("HpFill")),
        HpLabel = assert(self.instance:requireControl("HpLabel")),
        HpPoison = assert(self.instance:requireControl("HpPoison")),
        HpValue = assert(self.instance:requireControl("HpValue")),
        ItemCounts = assert(self.instance:requireControl("ItemCounts")),
        KeyIcon = assert(self.instance:requireControl("KeyIcon")),
        Level = assert(self.instance:requireControl("Level")),
        MapName = assert(self.instance:requireControl("MapName")),
        PlayerName = assert(self.instance:requireControl("PlayerName")),
        Root = assert(self.instance:requireControl("Root")),
        StateHost = assert(self.instance:requireControl("StateHost"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.PlayerAttrHUD
    self.controls = controls
    local assets = { StateItem1 = self:own(ChildView1.new(assert(self.instance:requireAsset("StateItem1")))) }
    ---@cast assets Source.UIBase.GeneratedAssets.PlayerAttrHUD
    self.assets = assets
end

return class(View, UiView)
