-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.PlayerAttrHUD.PlayerStateRow")

---@class Source.UI.PlayerAttrHUD
local View = {}

View.assetKey = "PlayerAttrHUD"
View.designSize = sf.Vector2f.new(640, 480)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        AtkDebuff = assert(self.instance:requireControl("AtkDebuff")),
        AtkLabel = assert(self.instance:requireControl("AtkLabel")),
        AtkValue = assert(self.instance:requireControl("AtkValue")),
        Avatar = assert(self.instance:requireControl("Avatar")),
        Background = assert(self.instance:requireControl("Background")),
        Background2 = assert(self.instance:requireControl("Background2")),
        Background3 = assert(self.instance:requireControl("Background3")),
        Background4 = assert(self.instance:requireControl("Background4")),
        BackgroundFloor1 = assert(self.instance:requireControl("BackgroundFloor1")),
        BackgroundFloorBtm = assert(self.instance:requireControl("BackgroundFloorBtm")),
        BackgroundFloorHUD1 = assert(self.instance:requireControl("BackgroundFloorHUD1")),
        BackgroundFloorHUD2 = assert(self.instance:requireControl("BackgroundFloorHUD2")),
        BackgroundFloorHUD3 = assert(self.instance:requireControl("BackgroundFloorHUD3")),
        BackgroundFloorHUD4 = assert(self.instance:requireControl("BackgroundFloorHUD4")),
        BreathBar = assert(self.instance:requireControl("BreathBar")),
        BreathDim = assert(self.instance:requireControl("BreathDim")),
        BreathLabel = assert(self.instance:requireControl("BreathLabel")),
        BreathLit = assert(self.instance:requireControl("BreathLit")),
        Canvas = assert(self.instance:requireControl("Canvas")),
        Canvas2 = assert(self.instance:requireControl("Canvas2")),
        DefDebuff = assert(self.instance:requireControl("DefDebuff")),
        DefLabel = assert(self.instance:requireControl("DefLabel")),
        DefValue = assert(self.instance:requireControl("DefValue")),
        ExpLabel = assert(self.instance:requireControl("ExpLabel")),
        ExpValue = assert(self.instance:requireControl("ExpValue")),
        GoldLabel = assert(self.instance:requireControl("GoldLabel")),
        GoldValue = assert(self.instance:requireControl("GoldValue")),
        HpBar = assert(self.instance:requireControl("HpBar")),
        HpLabel = assert(self.instance:requireControl("HpLabel")),
        HpPoison = assert(self.instance:requireControl("HpPoison")),
        HpValue = assert(self.instance:requireControl("HpValue")),
        ItemCounts = assert(self.instance:requireControl("ItemCounts")),
        KeyIcon = assert(self.instance:requireControl("KeyIcon")),
        Level = assert(self.instance:requireControl("Level")),
        MapName = assert(self.instance:requireControl("MapName")),
        PlainText = assert(self.instance:requireControl("PlainText")),
        PlayerName = assert(self.instance:requireControl("PlayerName")),
        Root = assert(self.instance:requireControl("Root")),
        StateHost = assert(self.instance:requireControl("StateHost"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.PlayerAttrHUD
    self.controls = controls
    local assets = { StateItem1 = self:own(ChildView1.new(assert(self.instance:requireAsset("StateItem1")))) }
    ---@cast assets Source.UIBase.GeneratedAssets.PlayerAttrHUD
    self.assets = assets
end

return class(View, UiView)
