-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.RegionTitle
local View = {}

View.assetKey = "RegionTitle"
View.designSize = sf.Vector2f.new(640, 480)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        RegionTitle = assert(self.instance:requireControl("RegionTitle")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.RegionTitle
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.RegionTitle
    self.assets = assets
end

return class(View, UiView)
