-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.Shared.CommandRow")

---@class Source.UI.Title
local View = {}

View.assetKey = "Title"
View.designSize = sf.Vector2f.new(640, 480)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Background = assert(self.instance:requireControl("Background")),
        CommandContent = assert(self.instance:requireControl("CommandContent")),
        CommandList = assert(self.instance:requireControl("CommandList")),
        CommandPanel = assert(self.instance:requireControl("CommandPanel")),
        CommandScrollBox = assert(self.instance:requireControl("CommandScrollBox")),
        CommandWindowFrame = assert(self.instance:requireControl("CommandWindowFrame")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Title
    self.controls = controls
    local assets = {
        TitleCommand1 = self:own(ChildView1.new(assert(self.instance:requireAsset("TitleCommand1")))),
        TitleCommand2 = self:own(ChildView1.new(assert(self.instance:requireAsset("TitleCommand2")))),
        TitleCommand3 = self:own(ChildView1.new(assert(self.instance:requireAsset("TitleCommand3")))),
        TitleCommand4 = self:own(ChildView1.new(assert(self.instance:requireAsset("TitleCommand4"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.Title
    self.assets = assets
end

return class(View, UiView)
