-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand")
local ChildView2 = require("Source.UI.Parts.WindowFloorTeleporter.WindowFloorMapPreview")

---@class Source.UI.WindowFloorTeleporter
local View = {}

View.assetKey = "WindowFloorTeleporter"
View.designSize = sf.Vector2f.new(416, 240)

function View:init(instance)
    UiView.init(self, instance)
    local controls = { Root = assert(self.instance:requireControl("Root")) }
    ---@cast controls Source.UIBase.GeneratedControls.WindowFloorTeleporter
    self.controls = controls
    local assets = {
        CommandAsset = self:own(ChildView1.new(assert(self.instance:requireAsset("CommandAsset")))),
        PreviewAsset = self:own(ChildView2.new(assert(self.instance:requireAsset("PreviewAsset"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.WindowFloorTeleporter
    self.assets = assets
end

return class(View, UiView)
