-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.WindowBattle
local View = {}

View.assetKey = "WindowBattle"
View.designSize = sf.Vector2f.new(416, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        BreathDim1 = assert(self.instance:requireControl("BreathDim1")),
        BreathDim1Preview = assert(self.instance:requireControl("BreathDim1Preview")),
        BreathDim2 = assert(self.instance:requireControl("BreathDim2")),
        BreathDim2Preview = assert(self.instance:requireControl("BreathDim2Preview")),
        BreathDim3 = assert(self.instance:requireControl("BreathDim3")),
        BreathDim3Preview = assert(self.instance:requireControl("BreathDim3Preview")),
        BreathDim4 = assert(self.instance:requireControl("BreathDim4")),
        BreathDim4Preview = assert(self.instance:requireControl("BreathDim4Preview")),
        BreathDim5 = assert(self.instance:requireControl("BreathDim5")),
        BreathDim5Preview = assert(self.instance:requireControl("BreathDim5Preview")),
        BreathDim6 = assert(self.instance:requireControl("BreathDim6")),
        BreathDim6Preview = assert(self.instance:requireControl("BreathDim6Preview")),
        BreathLit1 = assert(self.instance:requireControl("BreathLit1")),
        BreathLit1Preview = assert(self.instance:requireControl("BreathLit1Preview")),
        BreathLit2 = assert(self.instance:requireControl("BreathLit2")),
        BreathLit2Preview = assert(self.instance:requireControl("BreathLit2Preview")),
        BreathLit3 = assert(self.instance:requireControl("BreathLit3")),
        BreathLit3Preview = assert(self.instance:requireControl("BreathLit3Preview")),
        BreathLit4 = assert(self.instance:requireControl("BreathLit4")),
        BreathLit4Preview = assert(self.instance:requireControl("BreathLit4Preview")),
        BreathLit5 = assert(self.instance:requireControl("BreathLit5")),
        BreathLit5Preview = assert(self.instance:requireControl("BreathLit5Preview")),
        BreathLit6 = assert(self.instance:requireControl("BreathLit6")),
        BreathLit6Preview = assert(self.instance:requireControl("BreathLit6Preview")),
        Content = assert(self.instance:requireControl("Content")),
        CriticalButton = assert(self.instance:requireControl("CriticalButton")),
        EnemyATKLabel = assert(self.instance:requireControl("EnemyATKLabel")),
        EnemyATKValue = assert(self.instance:requireControl("EnemyATKValue")),
        EnemyBREATHLabel = assert(self.instance:requireControl("EnemyBREATHLabel")),
        EnemyBreathBack = assert(self.instance:requireControl("EnemyBreathBack")),
        EnemyBreathFill = assert(self.instance:requireControl("EnemyBreathFill")),
        EnemyDEFLabel = assert(self.instance:requireControl("EnemyDEFLabel")),
        EnemyDEFValue = assert(self.instance:requireControl("EnemyDEFValue")),
        EnemyDamage = assert(self.instance:requireControl("EnemyDamage")),
        EnemyFATIGUELabel = assert(self.instance:requireControl("EnemyFATIGUELabel")),
        EnemyFATIGUEValue = assert(self.instance:requireControl("EnemyFATIGUEValue")),
        EnemyHPLabel = assert(self.instance:requireControl("EnemyHPLabel")),
        EnemyHPValue = assert(self.instance:requireControl("EnemyHPValue")),
        EnemyName = assert(self.instance:requireControl("EnemyName")),
        EnemyPortrait = assert(self.instance:requireControl("EnemyPortrait")),
        PlayerATKLabel = assert(self.instance:requireControl("PlayerATKLabel")),
        PlayerATKValue = assert(self.instance:requireControl("PlayerATKValue")),
        PlayerBREATHLabel = assert(self.instance:requireControl("PlayerBREATHLabel")),
        PlayerBreathBack = assert(self.instance:requireControl("PlayerBreathBack")),
        PlayerBreathFill = assert(self.instance:requireControl("PlayerBreathFill")),
        PlayerDEFLabel = assert(self.instance:requireControl("PlayerDEFLabel")),
        PlayerDEFValue = assert(self.instance:requireControl("PlayerDEFValue")),
        PlayerDamage = assert(self.instance:requireControl("PlayerDamage")),
        PlayerFATIGUELabel = assert(self.instance:requireControl("PlayerFATIGUELabel")),
        PlayerFATIGUEValue = assert(self.instance:requireControl("PlayerFATIGUEValue")),
        PlayerHPLabel = assert(self.instance:requireControl("PlayerHPLabel")),
        PlayerHPValue = assert(self.instance:requireControl("PlayerHPValue")),
        PlayerName = assert(self.instance:requireControl("PlayerName")),
        PlayerPortrait = assert(self.instance:requireControl("PlayerPortrait")),
        RetreatButton = assert(self.instance:requireControl("RetreatButton")),
        RetreatLabel = assert(self.instance:requireControl("RetreatLabel")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.WindowBattle
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.WindowBattle
    self.assets = assets
end

return class(View, UiView)
