-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowSaveLoad.WindowSaveDetail")
local ChildView2 = require("Source.UI.Parts.WindowSaveLoad.WindowSaveSlot")
local ChildView3 = require("Source.UI.Parts.WindowSaveLoad.WindowSaveTabs")

---@class Source.UI.WindowSaveLoad
local View = {}

View.assetKey = "WindowSaveLoad"
View.designSize = sf.Vector2f.new(416, 320)

function View:init(instance)
    UiView.init(self, instance)
    local controls = { Root = assert(self.instance:requireControl("Root")) }
    ---@cast controls Source.UIBase.GeneratedControls.WindowSaveLoad
    self.controls = controls
    local assets = {
        DetailAsset = self:own(ChildView1.new(assert(self.instance:requireAsset("DetailAsset")))),
        SlotAsset = self:own(ChildView2.new(assert(self.instance:requireAsset("SlotAsset")))),
        TabsAsset = self:own(ChildView3.new(assert(self.instance:requireAsset("TabsAsset"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.WindowSaveLoad
    self.assets = assets
end

return class(View, UiView)
