-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowItem.ItemRow")

---@class Source.UI.WindowItem
local View = {}

View.assetKey = "WindowItem"
View.designSize = sf.Vector2f.new(256, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Description = assert(self.instance:requireControl("Description")),
        ItemList = assert(self.instance:requireControl("ItemList")),
        ItemName = assert(self.instance:requireControl("ItemName")),
        ItemScrollBox = assert(self.instance:requireControl("ItemScrollBox")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.WindowItem
    self.controls = controls
    local assets = {
        ItemPlaceholder1 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder1")))),
        ItemPlaceholder10 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder10")))),
        ItemPlaceholder11 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder11")))),
        ItemPlaceholder12 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder12")))),
        ItemPlaceholder13 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder13")))),
        ItemPlaceholder14 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder14")))),
        ItemPlaceholder15 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder15")))),
        ItemPlaceholder16 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder16")))),
        ItemPlaceholder17 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder17")))),
        ItemPlaceholder18 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder18")))),
        ItemPlaceholder19 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder19")))),
        ItemPlaceholder2 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder2")))),
        ItemPlaceholder20 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder20")))),
        ItemPlaceholder21 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder21")))),
        ItemPlaceholder22 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder22")))),
        ItemPlaceholder23 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder23")))),
        ItemPlaceholder24 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder24")))),
        ItemPlaceholder25 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder25")))),
        ItemPlaceholder26 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder26")))),
        ItemPlaceholder27 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder27")))),
        ItemPlaceholder28 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder28")))),
        ItemPlaceholder29 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder29")))),
        ItemPlaceholder3 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder3")))),
        ItemPlaceholder30 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder30")))),
        ItemPlaceholder4 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder4")))),
        ItemPlaceholder5 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder5")))),
        ItemPlaceholder6 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder6")))),
        ItemPlaceholder7 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder7")))),
        ItemPlaceholder8 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder8")))),
        ItemPlaceholder9 = self:own(ChildView1.new(assert(self.instance:requireAsset("ItemPlaceholder9"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.WindowItem
    self.assets = assets
end

return class(View, UiView)
