-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowEnemyBook.WindowEnemyBookCell")

---@class Source.UI.WindowEnemyBook
local View = {}

View.assetKey = "WindowEnemyBook"
View.designSize = sf.Vector2f.new(352, 352)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        EnemyList = assert(self.instance:requireControl("EnemyList")),
        EnemyScrollBox = assert(self.instance:requireControl("EnemyScrollBox")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.WindowEnemyBook
    self.controls = controls
    local assets = {
        EnemyItem1 = self:own(ChildView1.new(assert(self.instance:requireAsset("EnemyItem1")))),
        EnemyItem2 = self:own(ChildView1.new(assert(self.instance:requireAsset("EnemyItem2")))),
        EnemyItem3 = self:own(ChildView1.new(assert(self.instance:requireAsset("EnemyItem3")))),
        EnemyItem4 = self:own(ChildView1.new(assert(self.instance:requireAsset("EnemyItem4")))),
        EnemyItem5 = self:own(ChildView1.new(assert(self.instance:requireAsset("EnemyItem5"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.WindowEnemyBook
    self.assets = assets
end

return class(View, UiView)
