-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowShop.WindowShopDetail")
local ChildView2 = require("Source.UI.Parts.WindowShop.WindowShopItem")
local ChildView3 = require("Source.UI.Parts.WindowShop.WindowShopTabs")

---@class Source.UI.WindowShop
local View = {}

View.assetKey = "WindowShop"
View.designSize = sf.Vector2f.new(352, 416)

function View:init(instance)
    UiView.init(self, instance)
    local controls = { Root = assert(self.instance:requireControl("Root")) }
    ---@cast controls Source.UIBase.GeneratedControls.WindowShop
    self.controls = controls
    local assets = {
        DetailAsset = self:own(ChildView1.new(assert(self.instance:requireAsset("DetailAsset")))),
        ItemAsset = self:own(ChildView2.new(assert(self.instance:requireAsset("ItemAsset")))),
        TabsAsset = self:own(ChildView3.new(assert(self.instance:requireAsset("TabsAsset"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.WindowShop
    self.assets = assets
end

return class(View, UiView)
