-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowMessage.MessageOptionRow")

---@class Source.UI.WindowMessage
local View = {}

View.assetKey = "WindowMessage"
View.designSize = sf.Vector2f.new(640, 480)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        ConfirmLayer = assert(self.instance:requireControl("ConfirmLayer")),
        Content = assert(self.instance:requireControl("Content")),
        MessageList = assert(self.instance:requireControl("MessageList")),
        MessageText = assert(self.instance:requireControl("MessageText")),
        NameText = assert(self.instance:requireControl("NameText")),
        Panel = assert(self.instance:requireControl("Panel")),
        Root = assert(self.instance:requireControl("Root")),
        SelectionList = assert(self.instance:requireControl("SelectionList")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.WindowMessage
    self.controls = controls
    local assets = {
        SelectionItem1 = self:own(ChildView1.new(assert(self.instance:requireAsset("SelectionItem1")))),
        SelectionItem2 = self:own(ChildView1.new(assert(self.instance:requireAsset("SelectionItem2")))),
        SelectionItem3 = self:own(ChildView1.new(assert(self.instance:requireAsset("SelectionItem3")))),
        SelectionItem4 = self:own(ChildView1.new(assert(self.instance:requireAsset("SelectionItem4"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.WindowMessage
    self.assets = assets
end

return class(View, UiView)
