-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.Shared.CommandRow")

---@class Source.UI.WindowMenu
local View = {}

View.assetKey = "WindowMenu"
View.designSize = sf.Vector2f.new(192, 192)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        MenuList = assert(self.instance:requireControl("MenuList")),
        MenuScrollBox = assert(self.instance:requireControl("MenuScrollBox")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.WindowMenu
    self.controls = controls
    local assets = {
        MenuItem1 = self:own(ChildView1.new(assert(self.instance:requireAsset("MenuItem1")))),
        MenuItem2 = self:own(ChildView1.new(assert(self.instance:requireAsset("MenuItem2")))),
        MenuItem3 = self:own(ChildView1.new(assert(self.instance:requireAsset("MenuItem3")))),
        MenuItem4 = self:own(ChildView1.new(assert(self.instance:requireAsset("MenuItem4")))),
        MenuItem5 = self:own(ChildView1.new(assert(self.instance:requireAsset("MenuItem5"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.WindowMenu
    self.assets = assets
end

return class(View, UiView)
