-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.WindowPlayerName
local View = {}

View.assetKey = "WindowPlayerName"
View.designSize = sf.Vector2f.new(400, 224)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        ConfirmButton = assert(self.instance:requireControl("ConfirmButton")),
        ConfirmLabel = assert(self.instance:requireControl("ConfirmLabel")),
        Content = assert(self.instance:requireControl("Content")),
        Error = assert(self.instance:requireControl("Error")),
        NameInput = assert(self.instance:requireControl("NameInput")),
        Prompt = assert(self.instance:requireControl("Prompt")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.WindowPlayerName
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.WindowPlayerName
    self.assets = assets
end

return class(View, UiView)
