-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.WindowBattle
local View = {}

View.assetKey = "WindowBattle"
View.designSize = sf.Vector2f.new(416, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        AttackSkillButton = assert(self.instance:requireControl("AttackSkillButton")),
        AttackSkillButtonSelected = assert(self.instance:requireControl("AttackSkillButtonSelected")),
        BreathDim = assert(self.instance:requireControl("BreathDim")),
        BreathLit = assert(self.instance:requireControl("BreathLit")),
        Content = assert(self.instance:requireControl("Content")),
        CriticalButton = assert(self.instance:requireControl("CriticalButton")),
        CriticalButtonSelected = assert(self.instance:requireControl("CriticalButtonSelected")),
        DefenseSkillButton = assert(self.instance:requireControl("DefenseSkillButton")),
        DefenseSkillButtonSelected = assert(self.instance:requireControl("DefenseSkillButtonSelected")),
        EnemyATKLabel = assert(self.instance:requireControl("EnemyATKLabel")),
        EnemyATKValue = assert(self.instance:requireControl("EnemyATKValue")),
        EnemyBREATHLabel = assert(self.instance:requireControl("EnemyBREATHLabel")),
        EnemyBreathBar = assert(self.instance:requireControl("EnemyBreathBar")),
        EnemyDEFLabel = assert(self.instance:requireControl("EnemyDEFLabel")),
        EnemyDEFValue = assert(self.instance:requireControl("EnemyDEFValue")),
        EnemyFATIGUELabel = assert(self.instance:requireControl("EnemyFATIGUELabel")),
        EnemyFATIGUEValue = assert(self.instance:requireControl("EnemyFATIGUEValue")),
        EnemyHPLabel = assert(self.instance:requireControl("EnemyHPLabel")),
        EnemyHPValue = assert(self.instance:requireControl("EnemyHPValue")),
        EnemyName = assert(self.instance:requireControl("EnemyName")),
        EnemyPortrait = assert(self.instance:requireControl("EnemyPortrait")),
        PlayerATKLabel = assert(self.instance:requireControl("PlayerATKLabel")),
        PlayerATKValue = assert(self.instance:requireControl("PlayerATKValue")),
        PlayerBREATHLabel = assert(self.instance:requireControl("PlayerBREATHLabel")),
        PlayerBreathBar = assert(self.instance:requireControl("PlayerBreathBar")),
        PlayerDEFLabel = assert(self.instance:requireControl("PlayerDEFLabel")),
        PlayerDEFValue = assert(self.instance:requireControl("PlayerDEFValue")),
        PlayerFATIGUELabel = assert(self.instance:requireControl("PlayerFATIGUELabel")),
        PlayerFATIGUEValue = assert(self.instance:requireControl("PlayerFATIGUEValue")),
        PlayerHPLabel = assert(self.instance:requireControl("PlayerHPLabel")),
        PlayerHPValue = assert(self.instance:requireControl("PlayerHPValue")),
        PlayerName = assert(self.instance:requireControl("PlayerName")),
        PlayerPortrait = assert(self.instance:requireControl("PlayerPortrait")),
        RetreatButton = assert(self.instance:requireControl("RetreatButton")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.WindowBattle
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.WindowBattle
    self.assets = assets
end

return class(View, UiView)
