-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.BattleFloatingText
local View = {}

View.assetKey = "Parts/BattleFloatingText"
View.designSize = sf.Vector2f.new(384, 224)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Damage = assert(self.instance:requireControl("Damage")),
        Healing = assert(self.instance:requireControl("Healing")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.BattleFloatingText
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.BattleFloatingText
    self.assets = assets
end

return class(View, UiView)
