-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Sftp.SessionInfo.HostKey.Type
local enum = {
    Dsa = (2 --[[@as sf.Sftp.SessionInfo.HostKey.Type]]),
    Ecdsa256 = (3 --[[@as sf.Sftp.SessionInfo.HostKey.Type]]),
    Ecdsa384 = (4 --[[@as sf.Sftp.SessionInfo.HostKey.Type]]),
    Ecdsa521 = (5 --[[@as sf.Sftp.SessionInfo.HostKey.Type]]),
    Ed25519 = (6 --[[@as sf.Sftp.SessionInfo.HostKey.Type]]),
    Rsa = (1 --[[@as sf.Sftp.SessionInfo.HostKey.Type]]),
    Unknown = (0 --[[@as sf.Sftp.SessionInfo.HostKey.Type]]),
}

return enum
