-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Internal.UIBase.UiView")

---@class Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
local View = {}

View.assetKey = "Parts/WindowEnemyEncyclopedia/EnemyEncyclopediaSpecialRow"
View.designSize = sf.Vector2f.new(608, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Description = assert(self.instance:requireControl("Description")),
        DescriptionArea = assert(self.instance:requireControl("DescriptionArea")),
        Name = assert(self.instance:requireControl("Name")),
        NameArea = assert(self.instance:requireControl("NameArea")),
        Root = assert(self.instance:requireControl("Root"))
    }
    ---@cast controls Internal.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
    self.controls = controls
    local assets = {}
    ---@cast assets Internal.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
    self.assets = assets
end

return class(View, UiView)
