-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Socket.Status
local enum = {
    Disconnected = (3 --[[@as sf.Socket.Status]]),
    Done = (0 --[[@as sf.Socket.Status]]),
    Error = (4 --[[@as sf.Socket.Status]]),
    NotReady = (1 --[[@as sf.Socket.Status]]),
    Partial = (2 --[[@as sf.Socket.Status]]),
}

return enum
