-- AUTO-GENERATED by Ludork Core bindgen. DO NOT EDIT.
local _METADATA = {
    Animation = {
        bases = { { "Engine", "AnimSprite" } },
        attrs = { "soundEntries", "soundIndex", "playingSounds" },
        soundEntries = {
            type = {
                list = { "Engine", "AnimationSoundEntry" },
            },
        },
        soundIndex = {
            type = "int",
            default = 0,
        },
        playingSounds = {
            type = {
                list = { "GlobalCore", "AnimationPlayingSound" },
            },
        },
        setData = {
            type = "function",
            parameters = { "animationData", animationData = { "Engine", "AnimationData" } },
            ["return"] = {},
        },
        update = {
            type = "function",
            parameters = { "deltaTime", deltaTime = "float" },
            ["return"] = {},
        },
        playSoundsUpToFrame = {
            type = "function",
            parameters = { "frameIndex", frameIndex = "int" },
            ["return"] = {},
        },
        stopSoundsAtFrame = {
            type = "function",
            parameters = { "frameIndex", frameIndex = "int" },
            ["return"] = {},
        },
    },
    AnimationPlayingSound = {
        attrs = { "sound", "endFrame" },
        sound = {
            type = "sf.Sound",
        },
        endFrame = {
            type = "int",
            default = -1,
        },
    },
    Camera = {
        attrs = {},
        setViewport = {
            type = "function",
            parameters = { "inViewport", inViewport = "sf.FloatRect" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getView = {
            type = "function",
            parameters = {},
            ["return"] = {
                "view",
                view = "sf.View",
            },
            Pure = true,
        },
        getViewPosition = {
            type = "function",
            parameters = {},
            ["return"] = {
                "position",
                position = "sf.Vector2f",
            },
            Pure = true,
        },
        setViewPosition = {
            type = "function",
            parameters = { "inPosition", inPosition = "sf.Vector2f" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getViewSize = {
            type = "function",
            parameters = {},
            ["return"] = {
                "size",
                size = "sf.Vector2f",
            },
            Pure = true,
        },
        setViewSize = {
            type = "function",
            parameters = { "inSize", inSize = "sf.Vector2f" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getViewRotation = {
            type = "function",
            parameters = {},
            ["return"] = {
                "rotation",
                rotation = "sf.Angle",
            },
            Pure = true,
        },
        setViewRotation = {
            type = "function",
            parameters = { "inRotation", inRotation = "sf.Angle" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        moveView = {
            type = "function",
            parameters = { "delta", delta = "sf.Vector2f" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        rotateView = {
            type = "function",
            parameters = { "delta", delta = "sf.Angle" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        resumeViewport = {
            type = "function",
            parameters = {},
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getPosition = {
            type = "function",
            parameters = {},
            ["return"] = {
                "position",
                position = "sf.Vector2f",
            },
            Pure = true,
        },
        setPosition = {
            type = "function",
            parameters = { "inPosition", inPosition = "sf.Vector2f" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        move = {
            type = "function",
            parameters = { "delta", delta = "sf.Vector2f" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getRotation = {
            type = "function",
            parameters = {},
            ["return"] = {
                "rotation",
                rotation = "sf.Angle",
            },
            Pure = true,
        },
        setRotation = {
            type = "function",
            parameters = { "inRotation", inRotation = "sf.Angle" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        rotate = {
            type = "function",
            parameters = { "delta", delta = "sf.Angle" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "scale",
                scale = "sf.Vector2f",
            },
            Pure = true,
        },
        setScale = {
            type = "function",
            parameters = { "factors", factors = "sf.Vector2f" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        scale = {
            type = "function",
            parameters = { "delta", delta = "sf.Vector2f" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getParent = {
            type = "function",
            parameters = {},
            ["return"] = {
                "parent",
                parent = { "Engine", "Actor" },
            },
            Pure = true,
        },
        setParent = {
            type = "function",
            parameters = { "actor", actor = { "Engine", "Actor" } },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        setMap = {
            type = "function",
            parameters = { "map", map = { "GlobalCore", "GameMapBase" } },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getMap = {
            type = "function",
            parameters = {},
            ["return"] = {
                "map",
                map = { "GlobalCore", "GameMapBase" },
            },
            Pure = true,
        },
        mapPixelToCoords = {
            type = "function",
            parameters = { "point", point = "sf.Vector2i" },
            ["return"] = {
                "return",
                ["return"] = "sf.Vector2f",
            },
        },
        mapCoordsToPixel = {
            type = "function",
            parameters = { "point", point = "sf.Vector2f" },
            ["return"] = {
                "return",
                ["return"] = "sf.Vector2i",
            },
        },
        getRenderTexture = {
            type = "function",
            parameters = {},
            ["return"] = {
                "renderTexture",
                renderTexture = "sf.RenderTexture",
            },
            Pure = true,
        },
    },
    CommonTipController = {
        attrs = {},
        addTip = {
            type = "function",
            parameters = { "text", text = "string" },
            ["return"] = {},
        },
        onTick = {
            type = "function",
            parameters = { "deltaTime", deltaTime = "float" },
            ["return"] = {},
        },
    },
    FocusGroup = {
        attrs = { "name", "activeOwner" },
        name = {
            type = "string",
        },
        activeOwner = {
            type = { "Engine", "FunctionalBase" },
        },
        addItem = {
            type = "function",
            parameters = { "item", item = { "Engine", "FunctionalBase" } },
            ["return"] = {},
        },
        removeItem = {
            type = "function",
            parameters = { "item", item = { "Engine", "FunctionalBase" } },
            ["return"] = {},
        },
        getItems = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                list = { "Engine", "FunctionalBase" },
            },
            },
        },
        setNeighbor = {
            type = "function",
            parameters = { "direction", "neighbor", "transition", direction = "string", neighbor = { "GlobalCore", "FocusGroup" }, transition = "string" },
            default = { [3] = "directional" },
            ["return"] = {},
        },
        getNeighbor = {
            type = "function",
            parameters = { "direction", direction = "string" },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "FocusNeighbor" },
            },
        },
        canEnter = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        findInitialFocus = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = { "Engine", "FunctionalBase" },
            },
        },
        rememberFocus = {
            type = "function",
            parameters = { "element", element = { "Engine", "FunctionalBase" } },
            ["return"] = {},
        },
        moveWithin = {
            type = "function",
            parameters = { "current", "direction", current = { "Engine", "FunctionalBase" }, direction = "string" },
            ["return"] = {
                "return",
                ["return"] = { "Engine", "FunctionalBase" },
            },
        },
    },
    FocusManager = {
        attrs = {},
        setNavigationEnabled = {
            type = "function",
            parameters = { "enabled", enabled = "bool" },
            ["return"] = {},
        },
        getNavigationEnabled = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        isRoutingKeyboard = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        registerElement = {
            type = "function",
            parameters = { "element", element = { "Engine", "FunctionalBase" } },
            ["return"] = {},
        },
        unregisterElement = {
            type = "function",
            parameters = { "element", element = { "Engine", "FunctionalBase" } },
            ["return"] = {},
        },
        registerFocusGroup = {
            type = "function",
            parameters = { "group", group = { "GlobalCore", "FocusGroup" } },
            ["return"] = {},
        },
        unregisterFocusGroup = {
            type = "function",
            parameters = { "group", group = { "GlobalCore", "FocusGroup" } },
            ["return"] = {},
        },
        getFocus = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = { "Engine", "FunctionalBase" },
            },
        },
        setFocus = {
            type = "function",
            parameters = { "element", element = { "Engine", "FunctionalBase" } },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        clearFocus = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        prepareFrame = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        shouldDispatchKeyboardTo = {
            type = "function",
            parameters = { "element", element = { "Engine", "FunctionalBase" } },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        isFocused = {
            type = "function",
            parameters = { "element", element = { "Engine", "FunctionalBase" } },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        isCursorFocusOwner = {
            type = "function",
            parameters = { "element", element = { "Engine", "FunctionalBase" } },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        requestDirectionalMove = {
            type = "function",
            parameters = { "element", "direction", element = { "Engine", "FunctionalBase" }, direction = "string" },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        moveFocus = {
            type = "function",
            parameters = { "direction", "source", direction = "string", source = { "Engine", "FunctionalBase" } },
            default = {  },
            defaultUnset = { "source" },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        activateGroup = {
            type = "function",
            parameters = { "group", group = { "GlobalCore", "FocusGroup" } },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
    },
    FocusNeighbor = {
        attrs = { "group", "transition" },
        group = {
            type = { "GlobalCore", "FocusGroup" },
        },
        transition = {
            type = "string",
        },
    },
    FogController = {
        attrs = {},
        applyFromMapData = {
            type = "function",
            parameters = { "mapData", mapData = { "GlobalCore", "MapFogSettings" } },
            ["return"] = {},
        },
        clearFog = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        update = {
            type = "function",
            parameters = { "deltaTime", deltaTime = "float" },
            ["return"] = {},
        },
        drawOverlay = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
    },
    MapFogSettings = {
        attrs = { "fog", "fogPower", "fogOx", "fogOy", "fogDistort" },
        fog = {
            type = "string",
        },
        fogPower = {
            type = "float",
            default = 0.0,
        },
        fogOx = {
            type = "float",
            default = 0.0,
        },
        fogOy = {
            type = "float",
            default = 0.0,
        },
        fogDistort = {
            type = "float",
            default = 0.0,
        },
    },
    GameMapBase = {
        attrs = {},
        generateDataFromMap = {
            type = "function",
            parameters = { "size", "materialMap", "smooth", size = "sf.Vector2u", materialMap = {
                list = {
                    list = {
                        union = { "bool", "float" },
                    },
                },
            }, smooth = "bool" },
            ["return"] = {
                "return",
                ["return"] = "sf.Texture",
            },
        },
        findPathExt = {
            type = "function",
            parameters = { "start", "goal", "size", "movingActor", "excludedAnchors", start = "sf.Vector2i", goal = "sf.Vector2i", size = "sf.Vector2u", movingActor = { "Engine", "Actor" }, excludedAnchors = {
                list = "sf.Vector2i",
            } },
            default = { [5] = {} },
            defaultUnset = { "start", "goal", "size", "movingActor" },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "PathResult" },
            },
        },
        getMaterialPropertyMapExt = {
            type = "function",
            parameters = { "width", "height", "propertyName", "invalidValue", width = "int", height = "int", propertyName = "string", invalidValue = {
                union = { "bool", "float" },
            } },
            ["return"] = {
                "return",
                ["return"] = {
                list = {
                    list = {
                        union = { "bool", "float" },
                    },
                },
            },
            },
        },
        rebuildPassabilityCache = {
            type = "function",
            parameters = { "size", size = "sf.Vector2u" },
            ["return"] = {
                "return",
                ["return"] = {
                list = {
                    list = "bool",
                },
            },
            },
        },
        updateActorOccupancy = {
            type = "function",
            parameters = { "actor", actor = { "Engine", "Actor" } },
            ["return"] = {},
        },
        getActorsAt = {
            type = "function",
            parameters = { "x", "y", x = "int", y = "int" },
            ["return"] = {
                "return",
                ["return"] = {
                list = { "Engine", "Actor" },
            },
            },
        },
        getActorsInRange = {
            type = "function",
            parameters = { "x", "y", "radius", x = "int", y = "int", radius = "int" },
            ["return"] = {
                "return",
                ["return"] = {
                list = { "Engine", "Actor" },
            },
            },
        },
        getCollisionAt = {
            type = "function",
            parameters = { "x", "y", "selfActor", x = "int", y = "int", selfActor = { "Engine", "Actor" } },
            ["return"] = {
                "return",
                ["return"] = {
                list = { "Engine", "Actor" },
            },
            },
        },
        getOverlapsAt = {
            type = "function",
            parameters = { "x", "y", "selfActor", x = "int", y = "int", selfActor = { "Engine", "Actor" } },
            ["return"] = {
                "return",
                ["return"] = {
                list = { "Engine", "Actor" },
            },
            },
        },
        setTilemap = {
            type = "function",
            parameters = { "tilemap", tilemap = { "Engine", "Tilemap" } },
            ["return"] = {},
        },
        syncActorsRef = {
            type = "function",
            parameters = { "actors", actors = {
                dict = {
                    list = { "Engine", "Actor" },
                },
            } },
            ["return"] = {},
        },
    },
    PathResult = {
        attrs = { "offsets", "points", "route" },
        offsets = {
            type = {
                list = "sf.Vector2i",
            },
        },
        points = {
            type = {
                list = "sf.Vector2i",
            },
        },
        route = {
            type = {
                list = "sf.Vector2i",
            },
        },
    },
    AbilitySystemComponent = {
        attrs = {},
        getOwner = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "any",
            },
            Pure = true,
        },
        getAttributeSet = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "AttributeSet" },
            },
            Pure = true,
        },
        getNumericAttribute = {
            type = "function",
            parameters = { "name", name = "string" },
            ["return"] = {
                "return",
                ["return"] = {
                union = { "int", "float" },
            },
            },
            Pure = true,
        },
        getNumericAttributeBase = {
            type = "function",
            parameters = { "name", name = "string" },
            ["return"] = {
                "return",
                ["return"] = {
                union = { "int", "float" },
            },
            },
            Pure = true,
        },
        setNumericAttributeBase = {
            type = "function",
            parameters = { "name", "value", name = "string", value = {
                union = { "int", "float" },
            } },
            ["return"] = {},
        },
        setNumericAttributeBases = {
            type = "function",
            parameters = { "values", values = {
                dict = {
                    union = { "int", "float" },
                },
            } },
            ["return"] = {},
        },
        getNumericAttributeBases = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                dict = {
                    union = { "int", "float" },
                },
            },
            },
            Pure = true,
        },
        addAttributeChangeListener = {
            type = "function",
            parameters = { "name", "callback", "params", name = "string", callback = "function", params = "any[]" },
            default = { [3] = {} },
            defaultUnset = { "name", "callback" },
            ["return"] = {},
        },
        setNumericAttributeConstraint = {
            type = "function",
            parameters = { "name", "callback", name = "string", callback = "function" },
            default = {  },
            defaultUnset = { "callback" },
            ["return"] = {},
        },
        giveAbility = {
            type = "function",
            parameters = { "ability", "sourceKey", ability = { "GlobalCore", "GameplayAbility" }, sourceKey = "any" },
            default = {  },
            defaultUnset = { "sourceKey" },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "GameplayAbilitySpec" },
            },
        },
        removeAbilitiesBySource = {
            type = "function",
            parameters = { "sourceKey", sourceKey = "any" },
            ["return"] = {},
        },
        tryActivateAbility = {
            type = "function",
            parameters = { "abilityID", "eventData", abilityID = "string", eventData = { "GlobalCore", "GameplayEventData" } },
            default = {  },
            defaultUnset = { "eventData" },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "GameplayAbilityResult" },
            },
        },
        handleGameplayEvent = {
            type = "function",
            parameters = { "eventData", eventData = { "GlobalCore", "GameplayEventData" } },
            ["return"] = {
                "return",
                ["return"] = {
                list = { "GlobalCore", "GameplayAbilityResult" },
            },
            },
        },
        applyGameplayEffectSpec = {
            type = "function",
            parameters = { "spec", spec = { "GlobalCore", "GameplayEffectSpec" } },
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
        validateGameplayEffectSpec = {
            type = "function",
            parameters = { "spec", spec = { "GlobalCore", "GameplayEffectSpec" } },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        removeActiveGameplayEffect = {
            type = "function",
            parameters = { "handle", "stacks", handle = "int", stacks = "int" },
            default = {  },
            defaultUnset = { "stacks" },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        getActiveEffectStacks = {
            type = "function",
            parameters = { "effectID", effectID = "string" },
            ["return"] = {
                "return",
                ["return"] = "int",
            },
            Pure = true,
        },
        getActiveGameplayEffects = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                list = { "GlobalCore", "ActiveGameplayEffect" },
            },
            },
            Pure = true,
        },
        hasMatchingGameplayTag = {
            type = "function",
            parameters = { "tag", tag = "string" },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        getRevision = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
            Pure = true,
        },
    },
    ActiveGameplayEffect = {
        attrs = { "handle", "spec", "stacks", "applicationOrder", "grantedAbilitySpecs" },
        handle = {
            type = "int",
            default = 0,
        },
        spec = {
            type = { "GlobalCore", "GameplayEffectSpec" },
        },
        stacks = {
            type = "int",
            default = 1,
        },
        applicationOrder = {
            type = "int",
            default = 0,
        },
        grantedAbilitySpecs = {
            type = {
                list = { "GlobalCore", "GameplayAbilitySpec" },
            },
        },
    },
    AttributeSet = {
        attrs = {},
        getAttributeNames = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                list = "string",
            },
            },
            Pure = true,
        },
        getAttributeSchema = {
            type = "function",
            parameters = { "name", name = "string" },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "AttributeSchema" },
            },
            Pure = true,
        },
    },
    AttributeSchema = {
        attrs = { "type", "default" },
        type = {
            type = "any",
        },
        default = {
            type = "any",
        },
    },
    GameplayAbility = {
        attrs = { "id", "priority", "abilityTags", "requiredTags", "blockedTags", "triggerTags" },
        id = {
            type = "string",
        },
        priority = {
            type = "float",
            default = 0.0,
        },
        abilityTags = {
            type = {
                list = "string",
            },
        },
        requiredTags = {
            type = {
                list = "string",
            },
        },
        blockedTags = {
            type = {
                list = "string",
            },
        },
        triggerTags = {
            type = {
                list = "string",
            },
        },
        canActivate = {
            type = "function",
            parameters = { "abilitySystem", "eventData", abilitySystem = { "GlobalCore", "AbilitySystemComponent" }, eventData = { "GlobalCore", "GameplayEventData" } },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "GameplayAbilityResult" },
            },
            Pure = true,
        },
        calculate = {
            type = "function",
            parameters = { "abilitySystem", "eventData", abilitySystem = { "GlobalCore", "AbilitySystemComponent" }, eventData = { "GlobalCore", "GameplayEventData" } },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "GameplayAbilityResult" },
            },
            Pure = true,
        },
        activate = {
            type = "function",
            parameters = { "abilitySystem", "eventData", abilitySystem = { "GlobalCore", "AbilitySystemComponent" }, eventData = { "GlobalCore", "GameplayEventData" } },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "GameplayAbilityResult" },
            },
        },
    },
    GameplayAbilityResult = {
        attrs = { "ok", "code", "data" },
        ok = {
            type = "bool",
            default = false,
        },
        code = {
            type = {
                union = { "string", "int" },
            },
        },
        data = {
            type = "any",
        },
        Success = {
            type = "function",
            parameters = { "code", "data", code = {
                union = { "string", "int" },
            }, data = "any" },
            default = {  },
            defaultUnset = { "code", "data" },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "GameplayAbilityResult" },
            },
            Pure = true,
        },
        Failure = {
            type = "function",
            parameters = { "code", "data", code = {
                union = { "string", "int" },
            }, data = "any" },
            default = {  },
            defaultUnset = { "data" },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "GameplayAbilityResult" },
            },
            Pure = true,
        },
    },
    GameplayAbilitySpec = {
        attrs = { "ability", "sourceKey", "grantOrder" },
        ability = {
            type = { "GlobalCore", "GameplayAbility" },
        },
        sourceKey = {
            type = "any",
        },
        grantOrder = {
            type = "int",
            default = 0,
        },
    },
    GameplayEffect = {
        attrs = { "id", "durationPolicy", "stackingPolicy", "modifiers", "grantedTags", "grantedAbilities", "data" },
        id = {
            type = "string",
        },
        durationPolicy = {
            type = "string",
            default = "Instant",
        },
        stackingPolicy = {
            type = "string",
            default = "None",
        },
        modifiers = {
            type = {
                list = { "GlobalCore", "GameplayModifier" },
            },
        },
        grantedTags = {
            type = {
                list = "string",
            },
        },
        grantedAbilities = {
            type = {
                list = { "GlobalCore", "GameplayAbility" },
            },
        },
        data = {
            type = "any",
        },
    },
    GameplayEffectSpec = {
        attrs = { "effect", "eventData", "stacks", "sourceKey" },
        effect = {
            type = { "GlobalCore", "GameplayEffect" },
        },
        eventData = {
            type = { "GlobalCore", "GameplayEventData" },
        },
        stacks = {
            type = "int",
            default = 1,
        },
        sourceKey = {
            type = "any",
        },
    },
    GameplayEventData = {
        attrs = { "instigator", "target", "eventTag", "payload" },
        instigator = {
            type = "any",
        },
        target = {
            type = "any",
        },
        eventTag = {
            type = "string",
        },
        payload = {
            type = "any",
        },
    },
    GameplayModifier = {
        attrs = { "attribute", "operation", "magnitude", "minimum" },
        attribute = {
            type = "string",
        },
        operation = {
            type = "string",
        },
        magnitude = {
            type = {
                union = { "int", "float", "function" },
            },
        },
        minimum = {
            type = {
                union = { "int", "float" },
            },
        },
    },
    Light = {
        attrs = { "position", "colour", "radius", "intensity" },
        position = {
            type = "sf.Vector2f",
            default = { 0.0, 0.0 },
        },
        colour = {
            type = "sf.Color",
            default = { 255, 255, 255, 255 },
        },
        radius = {
            type = "float",
            default = 256.0,
        },
        intensity = {
            type = "float",
            default = 1.0,
        },
        asDict = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                dict = {
                    union = {
                        {
                            list = "float",
                        },
                        {
                            list = "int",
                        },
                        "float",
                        "int",
                    },
                },
            },
            },
        },
        fromDict = {
            type = "function",
            parameters = { "data", data = {
                dict = {
                    union = {
                        {
                            list = "float",
                        },
                        {
                            list = "int",
                        },
                        "float",
                        "int",
                    },
                },
            } },
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "Light" },
            },
        },
    },
    AudioManager = {
        attrs = {},
        loadSound = {
            type = "function",
            parameters = { "filePath", filePath = "string" },
            ["return"] = {
                "return",
                ["return"] = "sf.SoundBuffer",
            },
        },
        playSound = {
            type = "function",
            parameters = { "filePath", "filter", "parent", filePath = "string", filter = { "Engine", "SoundFilter" }, parent = "sf.Transformable" },
            default = {  },
            defaultUnset = { "filter", "parent" },
            ["return"] = {
                "return",
                ["return"] = "sf.Sound",
            },
        },
        setSoundParent = {
            type = "function",
            parameters = { "sound", "parent", sound = "sf.Sound", parent = "sf.Transformable" },
            ["return"] = {},
        },
        playVoice = {
            type = "function",
            parameters = { "filePath", "filter", "refActor", "minDistance", filePath = "string", filter = { "Engine", "SoundFilter" }, refActor = "sf.Transformable", minDistance = "float" },
            default = { [4] = 64.0 },
            defaultUnset = { "filter", "refActor" },
            ["return"] = {
                "return",
                ["return"] = "sf.Sound",
            },
        },
        setVoiceRefActor = {
            type = "function",
            parameters = { "voice", "refActor", "minDistance", voice = "sf.Sound", refActor = "sf.Transformable", minDistance = "float" },
            default = { [3] = 64.0 },
            ["return"] = {},
        },
        playMusic = {
            type = "function",
            parameters = { "musicType", "filePath", "filter", musicType = "string", filePath = "string", filter = { "Engine", "MusicFilter" } },
            default = {  },
            defaultUnset = { "filter" },
            ["return"] = {
                "return",
                ["return"] = "sf.Music",
            },
        },
        stopSound = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        stopVoice = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        stopMusic = {
            type = "function",
            parameters = { "musicType", musicType = "string" },
            ["return"] = {},
        },
        applySoundVolumes = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        applyVoiceVolumes = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        applyMusicVolumes = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        updateAllSoundPositions = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        updateAllVoicePositions = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        setSoundFilter = {
            type = "function",
            parameters = { "sound", "filter", sound = "sf.Sound", filter = { "Engine", "SoundFilter" } },
            ["return"] = {},
        },
        setVoiceFilter = {
            type = "function",
            parameters = { "voice", "filter", voice = "sf.Sound", filter = { "Engine", "SoundFilter" } },
            ["return"] = {},
        },
        setMusicFilter = {
            type = "function",
            parameters = { "music", "filter", music = "sf.Music", filter = { "Engine", "MusicFilter" } },
            ["return"] = {},
        },
        getMemory = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
    },
    FontManager = {
        attrs = {},
        load = {
            type = "function",
            parameters = { "filePath", filePath = "string" },
            ["return"] = {
                "return",
                ["return"] = "sf.Font",
            },
        },
        getFont = {
            type = "function",
            parameters = { "fontName", fontName = "string" },
            ["return"] = {
                "return",
                ["return"] = "sf.Font",
            },
        },
        getFontFilename = {
            type = "function",
            parameters = { "fontName", fontName = "string" },
            ["return"] = {
                "return",
                ["return"] = "string",
            },
        },
        getFontList = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                list = "string",
            },
            },
        },
        getFontFilenameList = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                list = "string",
            },
            },
        },
        hasFont = {
            type = "function",
            parameters = { "fontName", fontName = "string" },
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        getMemory = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
    },
    ShaderManager = {
        attrs = {},
        load = {
            type = "function",
            parameters = { "shaderPath", "shaderType", shaderPath = "string", shaderType = "int" },
            default = {  },
            defaultUnset = { "shaderType" },
            ["return"] = {
                "return",
                ["return"] = "sf.Shader",
            },
        },
        loadFull = {
            type = "function",
            parameters = { "vertPath", "fragPath", vertPath = "string", fragPath = "string" },
            ["return"] = {
                "return",
                ["return"] = "sf.Shader",
            },
        },
        loadFullShaderWithGeo = {
            type = "function",
            parameters = { "vertPath", "geoPath", "fragPath", vertPath = "string", geoPath = "string", fragPath = "string" },
            ["return"] = {
                "return",
                ["return"] = "sf.Shader",
            },
        },
        getMemory = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
    },
    TextureManager = {
        attrs = {},
        load = {
            type = "function",
            parameters = { "filePath", "sRGB", "area", "smooth", filePath = "string", sRGB = "bool", area = "sf.IntRect", smooth = "bool" },
            default = { [2] = false, [4] = false },
            defaultUnset = { "area" },
            ["return"] = {
                "return",
                ["return"] = "sf.Texture",
            },
        },
        getMemory = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
    },
    TimeManager = {
        attrs = {},
        getCurrentTime = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "sf.Time",
            },
        },
        getDeltaTime = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "sf.Time",
            },
        },
        getSpeed = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setSpeed = {
            type = "function",
            parameters = { "speed", speed = "float" },
            ["return"] = {},
        },
    },
    TimerEntry = {
        attrs = { "time", "task", "params", "blocking" },
        time = {
            type = "float",
        },
        task = {
            type = "function",
        },
        params = {
            type = {
                list = "any",
            },
        },
        blocking = {
            type = "bool",
        },
        isReady = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        isCancelled = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        cancel = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
    },
    MapPanoramaSettings = {
        attrs = { "panorama" },
        panorama = {
            type = "string",
        },
    },
    PanoramaController = {
        attrs = {},
        applyFromMapData = {
            type = "function",
            parameters = { "mapData", mapData = { "GlobalCore", "MapPanoramaSettings" } },
            ["return"] = {},
        },
        clear = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        isActive = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
    },
    SceneBase = {
        attrs = {},
        getUIManager = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "UIManager" },
            },
            Pure = true,
        },
        addTimer = {
            type = "function",
            parameters = { "interval", "task", "params", "blocking", interval = "float", task = "function", params = "any[]", blocking = "bool" },
            default = { [3] = {}, [4] = false },
            defaultUnset = { "interval", "task" },
            ["return"] = {
                "return",
                ["return"] = "function",
            },
            Latent = true,
            LatentStates = { "TimeUp", TimeUp = true },
        },
        isInputBlocked = {
            type = "function",
            parameters = {},
            ["return"] = {
                "blocked",
                blocked = "bool",
            },
            Pure = true,
        },
        addAnim = {
            type = "function",
            parameters = { "anim", anim = { "GlobalCore", "Animation" } },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getAnims = {
            type = "function",
            parameters = {},
            ["return"] = {
                "anims",
                anims = {
                list = { "GlobalCore", "Animation" },
            },
            },
            Pure = true,
        },
        removeAnim = {
            type = "function",
            parameters = { "anim", anim = { "GlobalCore", "Animation" } },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        clearAnims = {
            type = "function",
            parameters = {},
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        addCommonTip = {
            type = "function",
            parameters = { "text", text = "string" },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        onEnter = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        onQuit = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        onCreate = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        onInput = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        onTick = {
            type = "function",
            parameters = { "deltaTime", deltaTime = "float" },
            ["return"] = {},
        },
        onLateTick = {
            type = "function",
            parameters = { "deltaTime", deltaTime = "float" },
            ["return"] = {},
        },
        onFixedTick = {
            type = "function",
            parameters = { "fixedDelta", fixedDelta = "float" },
            ["return"] = {},
        },
        onDestroy = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
    },
    System = {
        attrs = {},
        init = {
            type = "function",
            parameters = { "data", "dataFilePath", data = "ConfigParser", dataFilePath = "string" },
            ["return"] = {},
        },
        getScript = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "string",
            },
        },
        setScript = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        saveScript = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        getLanguage = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "string",
            },
        },
        setLanguage = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        saveLanguage = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        getScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        getConfiguredScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        getMaximumWindowedScale = {
            type = "function",
            parameters = { "gameSize", gameSize = "sf.Vector2u" },
            ["return"] = {
                "return",
                ["return"] = "float",
            },
            Pure = true,
        },
        setScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        applyScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getMaximumRenderScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setMaximumRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveMaximumRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getLightingRenderScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setLightingRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveLightingRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        isDisplayScaleConfigurable = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        getFrameRate = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
        setFrameRate = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        saveFrameRate = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        getAntiAliasingLevel = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
        setAntiAliasingLevel = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        saveAntiAliasingLevel = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        getVerticalSync = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setVerticalSync = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveVerticalSync = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getMusicOn = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setMusicOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveMusicOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getSoundOn = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setSoundOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveSoundOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getVoiceOn = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setVoiceOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveVoiceOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getMusicVolume = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setMusicVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveMusicVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getSoundVolume = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setSoundVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveSoundVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getVoiceVolume = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setVoiceVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveVoiceVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        isDebugMode = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        getGameSize = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "sf.Vector2u",
            },
            Pure = true,
        },
        setInputMethodDisabled = {
            type = "function",
            parameters = { "disabled", disabled = "bool" },
            ["return"] = {},
        },
        setWindowMapView = {
            type = "function",
            parameters = { "rect", rect = "sf.IntRect" },
            ["return"] = {},
        },
        setWindowDefaultView = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        getCanvas = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "sf.RenderTexture",
            },
            Pure = true,
        },
        setWeather = {
            type = "function",
            parameters = { "weatherType", "power", "maxCount", weatherType = "int", power = "float", maxCount = "int" },
            ["return"] = {},
        },
        clearWeather = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        clearFog = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        applyFogFromMapData = {
            type = "function",
            parameters = { "mapData", mapData = { "GlobalCore", "MapFogSettings" } },
            ["return"] = {},
        },
        clearPanorama = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        applyPanoramaFromMapData = {
            type = "function",
            parameters = { "mapData", mapData = { "GlobalCore", "MapPanoramaSettings" } },
            ["return"] = {},
        },
        draw = {
            type = "function",
            parameters = { "drawable", "shader", drawable = "sf.Drawable", shader = "sf.Shader" },
            default = {  },
            defaultUnset = { "shader" },
            ["return"] = {},
        },
        addGraphicsShader = {
            type = "function",
            parameters = { "shader", "uniforms", shader = "sf.Shader", uniforms = {
                dict = {
                    union = {
                        "float",
                        "int",
                        "bool",
                        "sf.Vector2f",
                        "sf.Vector3f",
                        "sf.Glsl.Vec4",
                        "sf.Vector2i",
                        "sf.Vector3i",
                        "sf.Glsl.Ivec4",
                        "sf.Color",
                        "sf.Texture",
                        {
                            list = "float",
                        },
                        {
                            list = "sf.Vector2f",
                        },
                        {
                            list = "sf.Vector3f",
                        },
                        {
                            list = "sf.Glsl.Vec4",
                        },
                    },
                },
            } },
            default = {  },
            defaultUnset = { "uniforms" },
            ["return"] = {},
        },
        removeGraphicsShader = {
            type = "function",
            parameters = { "shader", shader = "sf.Shader" },
            ["return"] = {},
        },
        removeAllGraphicsShaders = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        removeGraphicsShaderAt = {
            type = "function",
            parameters = { "index", index = "int" },
            ["return"] = {},
        },
        flashScreen = {
            type = "function",
            parameters = { "color", "duration", color = "sf.Color", duration = "float" },
            default = { [2] = 0.5 },
            defaultUnset = { "color" },
            ["return"] = {},
        },
        stopFlash = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        isFlashing = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        changeScreenTone = {
            type = "function",
            parameters = { "red", "green", "blue", "gray", "duration", red = "float", green = "float", blue = "float", gray = "float", duration = "float" },
            default = { [1] = 0.0, [2] = 0.0, [3] = 0.0, [4] = 0.0, [5] = 0.0 },
            ["return"] = {},
        },
        clearScreenTone = {
            type = "function",
            parameters = { "duration", duration = "float" },
            default = { [1] = 0.0 },
            ["return"] = {},
        },
        stopScreenTone = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        isScreenToneActive = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        isScreenToneTransitionComplete = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        startShake = {
            type = "function",
            parameters = { "power", "speed", "duration", power = "float", speed = "float", duration = "float" },
            default = { [1] = 4.0, [2] = 10.0, [3] = 0.5 },
            ["return"] = {},
        },
        stopShake = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        isShaking = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        setTransition = {
            type = "function",
            parameters = { "transitionResource", "transitionTime", transitionResource = "sf.Texture", transitionTime = "float" },
            default = { [2] = 1.0 },
            defaultUnset = { "transitionResource" },
            ["return"] = {},
        },
        freezeTransitionBackground = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        isTransitionBackgroundFrozen = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        isTransitionBackgroundFreezePending = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        cancelTransitionBackgroundFreeze = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        requestTransition = {
            type = "function",
            parameters = { "transitionName", "transitionTime", transitionName = "string", transitionTime = "float" },
            default = { [2] = 1.0 },
            defaultUnset = { "transitionName" },
            ["return"] = {},
        },
        cancelPendingTransition = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        isTransitionPending = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        isInTransition = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
            Pure = true,
        },
        getScene = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "SceneRuntime",
            },
            Pure = true,
        },
        requireScene = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "SceneRuntime",
            },
            Pure = true,
        },
        getSceneList = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = {
                list = "SceneRuntime",
            },
            },
            Pure = true,
        },
        setScene = {
            type = "function",
            parameters = { "scene", scene = "SceneRuntime" },
            ["return"] = {},
        },
        pushScene = {
            type = "function",
            parameters = { "scene", scene = "SceneRuntime" },
            ["return"] = {},
        },
        popScene = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        exit = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
    },
    SystemConfigBase = {
        attrs = {},
        init = {
            type = "function",
            parameters = { "data", "dataFilePath", data = "ConfigParser", dataFilePath = "string" },
            ["return"] = {},
        },
        getScript = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "string",
            },
        },
        setScript = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        saveScript = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        getLanguage = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "string",
            },
        },
        setLanguage = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        saveLanguage = {
            type = "function",
            parameters = { "value", value = "string" },
            ["return"] = {},
        },
        getScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        getConfiguredScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        applyScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getMaximumRenderScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setMaximumRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveMaximumRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getLightingRenderScale = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setLightingRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveLightingRenderScale = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getFrameRate = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
        setFrameRate = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        saveFrameRate = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        getAntiAliasingLevel = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
        },
        setAntiAliasingLevel = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        saveAntiAliasingLevel = {
            type = "function",
            parameters = { "value", value = "int" },
            ["return"] = {},
        },
        getVerticalSync = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setVerticalSync = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveVerticalSync = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getMusicOn = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setMusicOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveMusicOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getSoundOn = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setSoundOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveSoundOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getVoiceOn = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "bool",
            },
        },
        setVoiceOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        saveVoiceOn = {
            type = "function",
            parameters = { "value", value = "bool" },
            ["return"] = {},
        },
        getMusicVolume = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setMusicVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveMusicVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getSoundVolume = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setSoundVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveSoundVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        getVoiceVolume = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "float",
            },
        },
        setVoiceVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
        saveVoiceVolume = {
            type = "function",
            parameters = { "value", value = "float" },
            ["return"] = {},
        },
    },
    UIManager = {
        attrs = {},
        getFocusManager = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = { "GlobalCore", "FocusManager" },
            },
            Pure = true,
        },
        setFocusNavigationEnabled = {
            type = "function",
            parameters = { "enabled", enabled = "bool" },
            ["return"] = {},
        },
        registerFocusGroup = {
            type = "function",
            parameters = { "group", group = { "GlobalCore", "FocusGroup" } },
            ["return"] = {},
        },
        loadUI = {
            type = "function",
            parameters = { "ui", ui = { "Engine", "ControlBase" } },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
        getUIs = {
            type = "function",
            parameters = {},
            ["return"] = {
                "uis",
                uis = {
                list = { "Engine", "ControlBase" },
            },
            },
            Pure = true,
        },
        removeUI = {
            type = "function",
            parameters = { "ui", ui = { "Engine", "ControlBase" } },
            ["return"] = {},
            ExecSplit = { "default", default = "nil" },
        },
    },
    WeatherController = {
        attrs = {},
        setWeather = {
            type = "function",
            parameters = { "weatherType", "power", "maxCount", weatherType = "int", power = "float", maxCount = "int" },
            ["return"] = {},
        },
        clearWeather = {
            type = "function",
            parameters = {},
            ["return"] = {},
        },
        update = {
            type = "function",
            parameters = { "deltaTime", deltaTime = "float" },
            ["return"] = {},
        },
        drawShaderOverlay = {
            type = "function",
            parameters = { "camera", camera = { "GlobalCore", "Camera" } },
            ["return"] = {},
        },
        getWeatherType = {
            type = "function",
            parameters = {},
            ["return"] = {
                "return",
                ["return"] = "int",
            },
            Pure = true,
        },
    },
    WorldStreamingStats = {
        attrs = { "Unloaded", "Reading", "Prepared", "Active", "Dormant", "queued", "cacheBytes" },
        Unloaded = {
            type = "int",
            default = 0,
        },
        Reading = {
            type = "int",
            default = 0,
        },
        Prepared = {
            type = "int",
            default = 0,
        },
        Active = {
            type = "int",
            default = 0,
        },
        Dormant = {
            type = "int",
            default = 0,
        },
        queued = {
            type = "int",
            default = 0,
        },
        cacheBytes = {
            type = "int",
            default = 0,
        },
    },
}

return _METADATA
