-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Ftp.TransferMode
local enum = {
    Ascii = (1 --[[@as sf.Ftp.TransferMode]]),
    Binary = (0 --[[@as sf.Ftp.TransferMode]]),
    Ebcdic = (2 --[[@as sf.Ftp.TransferMode]]),
}

return enum
