-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowShop.WindowShopTabs

---@class Source.UIBase.GeneratedControls.Parts.WindowShop.WindowShopTabs
---@field Content     Engine.Canvas
---@field Root        Engine.Canvas
---@field Tabs        Engine.TabView
---@field WindowFrame Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopTabs

---@class Source.UI.Parts.WindowShop.WindowShopTabs: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowShop.WindowShopTabs
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopTabs
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowShop.WindowShopTabs
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
