-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Parts.WindowShop.WindowShopItem

---@class Source.UIBase.GeneratedControls.Parts.WindowShop.WindowShopItem
---@field Content       Engine.Canvas
---@field ItemList      Engine.ListView
---@field ItemScrollBox Engine.ScrollBox
---@field Root          Engine.Canvas
---@field WindowFrame   Engine.Window

---@class Source.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopItem
---@field ShopItemPlaceholder1  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder10 Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder11 Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder12 Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder13 Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder14 Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder2  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder3  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder4  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder5  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder6  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder7  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder8  Source.UI.Parts.WindowShop.WindowShopCell
---@field ShopItemPlaceholder9  Source.UI.Parts.WindowShop.WindowShopCell

---@class Source.UI.Parts.WindowShop.WindowShopItem: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Parts.WindowShop.WindowShopItem
---@field assets   Source.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopItem
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Parts.WindowShop.WindowShopItem
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
