-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.Shared.CommandRow

---@class Internal.UIBase.GeneratedControls.Parts.Shared.CommandRow
---@field Label Engine.FunctionalPlainText
---@field Root  Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.Shared.CommandRow

---@class Internal.UI.Parts.Shared.CommandRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.Shared.CommandRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.Shared.CommandRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.Shared.CommandRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
