-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.Shared.WindowChrome

---@class Internal.UIBase.GeneratedControls.Parts.Shared.WindowChrome
---@field HintBar      Engine.GamepadHintBar
---@field ReturnButton Engine.Button
---@field Root         Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.Shared.WindowChrome

---@class Internal.UI.Parts.Shared.WindowChrome: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.Shared.WindowChrome
---@field assets   Internal.UIBase.GeneratedAssets.Parts.Shared.WindowChrome
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.Shared.WindowChrome
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
