-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand

---@class Internal.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field CommandList      Engine.ListView
---@field CommandScrollBox Engine.ScrollBox
---@field Content          Engine.Canvas
---@field Root             Engine.Canvas
---@field WindowFrame      Engine.Window

---@class Internal.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field MapPlaceholder1 Internal.UI.Parts.Shared.CommandRow
---@field MapPlaceholder2 Internal.UI.Parts.Shared.CommandRow
---@field MapPlaceholder3 Internal.UI.Parts.Shared.CommandRow
---@field MapPlaceholder4 Internal.UI.Parts.Shared.CommandRow
---@field MapPlaceholder5 Internal.UI.Parts.Shared.CommandRow
---@field MapPlaceholder6 Internal.UI.Parts.Shared.CommandRow
---@field MapPlaceholder7 Internal.UI.Parts.Shared.CommandRow
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapCommand
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapCommand
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
