-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapPreview

---@class Internal.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapPreview
---@field PreviewContent       Engine.Canvas
---@field PreviewImage         Engine.Image
---@field PreviewWindowFrame   Engine.Window
---@field Root                 Engine.Canvas
---@field TelepointContent     Engine.Canvas
---@field TelepointList        Engine.ListView
---@field TelepointScrollBox   Engine.ScrollBox
---@field TelepointWindowFrame Engine.Window

---@class Internal.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapPreview
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapPreview: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowFloorTeleporter.WindowFloorMapPreview
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowFloorTeleporter.WindowFloorMapPreview
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowFloorTeleporter.WindowFloorMapPreview
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
