-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowMessage.MessageOptionRow
local View = {}

View.assetKey = "Parts/WindowMessage/MessageOptionRow"
View.designSize = sf.Vector2f.new(480, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = { Root = assert(self.instance:requireControl("Root")) }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowMessage.MessageOptionRow
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowMessage.MessageOptionRow
    self.assets = assets
end

return class(View, UiView)
