-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowEnemyBook.WindowEnemyBookCell
local View = {}

View.assetKey = "Parts/WindowEnemyBook/WindowEnemyBookCell"
View.designSize = sf.Vector2f.new(320, 64)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        ATKLabel = assert(self.instance:requireControl("ATKLabel")),
        ATKValue = assert(self.instance:requireControl("ATKValue")),
        DEFLabel = assert(self.instance:requireControl("DEFLabel")),
        DEFValue = assert(self.instance:requireControl("DEFValue")),
        DamageLabel = assert(self.instance:requireControl("DamageLabel")),
        DamageValue = assert(self.instance:requireControl("DamageValue")),
        EXPLabel = assert(self.instance:requireControl("EXPLabel")),
        EXPValue = assert(self.instance:requireControl("EXPValue")),
        EnemyIcon = assert(self.instance:requireControl("EnemyIcon")),
        GOLDLabel = assert(self.instance:requireControl("GOLDLabel")),
        GOLDValue = assert(self.instance:requireControl("GOLDValue")),
        HPLabel = assert(self.instance:requireControl("HPLabel")),
        HPValue = assert(self.instance:requireControl("HPValue")),
        Name = assert(self.instance:requireControl("Name")),
        Root = assert(self.instance:requireControl("Root")),
        SpecialIcon1 = assert(self.instance:requireControl("SpecialIcon1")),
        SpecialIcon2 = assert(self.instance:requireControl("SpecialIcon2")),
        SpecialIcon3 = assert(self.instance:requireControl("SpecialIcon3")),
        SpecialText1 = assert(self.instance:requireControl("SpecialText1")),
        SpecialText2 = assert(self.instance:requireControl("SpecialText2")),
        SpecialText3 = assert(self.instance:requireControl("SpecialText3"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowEnemyBook.WindowEnemyBookCell
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowEnemyBook.WindowEnemyBookCell
    self.assets = assets
end

return class(View, UiView)
