-- AUTO-GENERATED by Ludork Game Variable Manager. DO NOT EDIT.

return {
    ["DoorGate17"] = 0,
    ["DoorGate18"] = 0,
    ["DoorGate7"] = 0,
    ["MTExample"] = 0,
    ["ShopPrice"] = 20,
    ["ShopPrice2"] = 50,
    ["bravorshow"] = false,
    ["floor25Phase"] = 0,
    ["fly"] = false,
    ["mbook"] = false,
    ["net1"] = false,
    ["princesspart"] = true,
    ["sdoor"] = false,
    ["sdoortmt1_b"] = 0,
    ["thief9"] = false,
    ["thief9door"] = 0,
}
