-- AUTO-GENERATED by Ludork Game Variable Manager. DO NOT EDIT.

return {
    ["DoorGate17"] = 0,
    ["DoorGate18"] = 0,
    ["DoorGate7"] = 0,
    ["MTExample"] = 0,
    ["ShopPrice"] = 20,
    ["fly"] = false,
    ["mbook"] = false,
    ["net1"] = false,
    ["sdoor"] = false,
    ["thief9"] = false,
    ["thief9door"] = 0,
}
