-- AUTO-GENERATED by Ludork Game Variable Manager. DO NOT EDIT.

local _METADATA = {
    GameVariables = {
        attrs = {
            "DoorGate17",
            "DoorGate18",
            "DoorGate7",
            "MTExample",
            "ShopPrice",
            "fly",
            "mbook",
            "net1",
            "sdoor",
            "thief9",
            "thief9door",
        },
        ["DoorGate17"] = {
            type = "int",
        },
        ["DoorGate18"] = {
            type = "int",
        },
        ["DoorGate7"] = {
            type = "int",
        },
        ["MTExample"] = {
            type = "int",
        },
        ["ShopPrice"] = {
            type = "int",
        },
        ["fly"] = {
            type = "bool",
        },
        ["mbook"] = {
            type = "bool",
        },
        ["net1"] = {
            type = "bool",
        },
        ["sdoor"] = {
            type = "bool",
        },
        ["thief9"] = {
            type = "bool",
        },
        ["thief9door"] = {
            type = "int",
        },
    },
}

return _METADATA
