-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.ConfigWindow

---@class Source.UIBase.GeneratedControls.ConfigWindow
---@field AudioList           Engine.ListView
---@field Content             Engine.Canvas
---@field GraphicsList        Engine.ListView
---@field LanguageList        Engine.ListView
---@field Root                Engine.Canvas
---@field SettingsContent     Engine.Canvas
---@field SettingsScrollBox   Engine.ScrollBox
---@field SettingsWindowFrame Engine.Window
---@field TabView             Engine.TabView
---@field WindowFrame         Engine.Window

---@class Source.UIBase.GeneratedAssets.ConfigWindow
---@field AudioItem1    Source.UI.Parts.ConfigWindow.ConfigCheckBoxRow
---@field AudioItem2    Source.UI.Parts.ConfigWindow.ConfigSliderRow
---@field AudioItem3    Source.UI.Parts.ConfigWindow.ConfigCheckBoxRow
---@field AudioItem4    Source.UI.Parts.ConfigWindow.ConfigSliderRow
---@field AudioItem5    Source.UI.Parts.ConfigWindow.ConfigCheckBoxRow
---@field AudioItem6    Source.UI.Parts.ConfigWindow.ConfigSliderRow
---@field GraphicsItem1 Source.UI.Parts.ConfigWindow.ConfigSettingRow
---@field GraphicsItem2 Source.UI.Parts.ConfigWindow.ConfigSettingRow
---@field GraphicsItem3 Source.UI.Parts.ConfigWindow.ConfigSettingRow
---@field GraphicsItem4 Source.UI.Parts.ConfigWindow.ConfigSettingRow
---@field GraphicsItem5 Source.UI.Parts.ConfigWindow.ConfigSettingRow
---@field GraphicsItem6 Source.UI.Parts.ConfigWindow.ConfigCheckBoxRow
---@field GraphicsItem7 Source.UI.Parts.ConfigWindow.ConfigSettingRow
---@field LanguageItem1 Source.UI.Parts.ConfigWindow.ConfigSettingRow

---@class Source.UI.ConfigWindow: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.ConfigWindow
---@field assets   Source.UIBase.GeneratedAssets.ConfigWindow
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.ConfigWindow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
