-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.GameOver

---@class Source.UIBase.GeneratedControls.GameOver
---@field Background Engine.SolidRect
---@field Message    Engine.PlainText
---@field Root       Engine.Canvas

---@class Source.UIBase.GeneratedAssets.GameOver

---@class Source.UI.GameOver: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.GameOver
---@field assets   Source.UIBase.GeneratedAssets.GameOver
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.GameOver
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
