-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Init

---@class Source.UIBase.GeneratedControls.Init
---@field Background  Engine.Image
---@field ProgressBar Engine.ProgressBar
---@field Root        Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Init

---@class Source.UI.Init: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Init
---@field assets   Source.UIBase.GeneratedAssets.Init
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Init
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
