-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.ParticleShowcase

---@class Source.UIBase.GeneratedControls.ParticleShowcase
---@field ResidentAura Engine.EmitterView
---@field Root         Engine.Canvas
---@field Smoke        Engine.EmitterView
---@field Sparks       Engine.EmitterView
---@field UiSparkle    Engine.EmitterView

---@class Source.UIBase.GeneratedAssets.ParticleShowcase

---@class Source.UI.ParticleShowcase: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.ParticleShowcase
---@field assets   Source.UIBase.GeneratedAssets.ParticleShowcase
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.ParticleShowcase
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
