-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.RegionTitle

---@class Source.UIBase.GeneratedControls.RegionTitle
---@field RegionTitle Engine.PlainText
---@field Root        Engine.Canvas

---@class Source.UIBase.GeneratedAssets.RegionTitle

---@class Source.UI.RegionTitle: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.RegionTitle
---@field assets   Source.UIBase.GeneratedAssets.RegionTitle
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.RegionTitle
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
