-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.Title

---@class Source.UIBase.GeneratedControls.Title
---@field Background         Engine.Image
---@field CommandContent     Engine.Canvas
---@field CommandList        Engine.ListView
---@field CommandPanel       Engine.Canvas
---@field CommandScrollBox   Engine.ScrollBox
---@field CommandWindowFrame Engine.Window
---@field Root               Engine.Canvas

---@class Source.UIBase.GeneratedAssets.Title
---@field TitleCommand1 Source.UI.Parts.Shared.CommandRow
---@field TitleCommand2 Source.UI.Parts.Shared.CommandRow
---@field TitleCommand3 Source.UI.Parts.Shared.CommandRow
---@field TitleCommand4 Source.UI.Parts.Shared.CommandRow

---@class Source.UI.Title: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.Title
---@field assets   Source.UIBase.GeneratedAssets.Title
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.Title
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
