-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.WindowBattle

---@class Source.UIBase.GeneratedControls.WindowBattle
---@field BreathDim1         Engine.Canvas
---@field BreathDim1Preview  Engine.Image
---@field BreathDim2         Engine.Canvas
---@field BreathDim2Preview  Engine.Image
---@field BreathDim3         Engine.Canvas
---@field BreathDim3Preview  Engine.Image
---@field BreathDim4         Engine.Canvas
---@field BreathDim4Preview  Engine.Image
---@field BreathDim5         Engine.Canvas
---@field BreathDim5Preview  Engine.Image
---@field BreathDim6         Engine.Canvas
---@field BreathDim6Preview  Engine.Image
---@field BreathLit1         Engine.Canvas
---@field BreathLit1Preview  Engine.Image
---@field BreathLit2         Engine.Canvas
---@field BreathLit2Preview  Engine.Image
---@field BreathLit3         Engine.Canvas
---@field BreathLit3Preview  Engine.Image
---@field BreathLit4         Engine.Canvas
---@field BreathLit4Preview  Engine.Image
---@field BreathLit5         Engine.Canvas
---@field BreathLit5Preview  Engine.Image
---@field BreathLit6         Engine.Canvas
---@field BreathLit6Preview  Engine.Image
---@field Content            Engine.Canvas
---@field CriticalButton     Engine.Button
---@field EnemyATKLabel      Engine.PlainText
---@field EnemyATKValue      Engine.PlainText
---@field EnemyBREATHLabel   Engine.PlainText
---@field EnemyBreathBack    Engine.Image
---@field EnemyBreathFill    Engine.Image
---@field EnemyDEFLabel      Engine.PlainText
---@field EnemyDEFValue      Engine.PlainText
---@field EnemyFATIGUELabel  Engine.PlainText
---@field EnemyFATIGUEValue  Engine.PlainText
---@field EnemyHPLabel       Engine.PlainText
---@field EnemyHPValue       Engine.PlainText
---@field EnemyName          Engine.PlainText
---@field EnemyPortrait      Engine.CharacterView
---@field PlayerATKLabel     Engine.PlainText
---@field PlayerATKValue     Engine.PlainText
---@field PlayerBREATHLabel  Engine.PlainText
---@field PlayerBreathBack   Engine.Image
---@field PlayerBreathFill   Engine.Image
---@field PlayerDEFLabel     Engine.PlainText
---@field PlayerDEFValue     Engine.PlainText
---@field PlayerFATIGUELabel Engine.PlainText
---@field PlayerFATIGUEValue Engine.PlainText
---@field PlayerHPLabel      Engine.PlainText
---@field PlayerHPValue      Engine.PlainText
---@field PlayerName         Engine.PlainText
---@field PlayerPortrait     Engine.CharacterView
---@field RetreatButton      Engine.Button
---@field RetreatLabel       Engine.PlainText
---@field Root               Engine.Canvas
---@field WindowFrame        Engine.Window

---@class Source.UIBase.GeneratedAssets.WindowBattle

---@class Source.UI.WindowBattle: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.WindowBattle
---@field assets   Source.UIBase.GeneratedAssets.WindowBattle
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.WindowBattle
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
