-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.WindowEnemyEncyclopedia

---@class Source.UIBase.GeneratedControls.WindowEnemyEncyclopedia
---@field Content          Engine.Canvas
---@field Description      Engine.PlainText
---@field InfoLayer        Engine.ListView
---@field Name             Engine.FunctionalPlainText
---@field Portrait         Engine.CharacterView
---@field Root             Engine.Canvas
---@field SpecialList      Engine.ListView
---@field SpecialScrollBox Engine.ScrollBox
---@field WindowFrame      Engine.Window

---@class Source.UIBase.GeneratedAssets.WindowEnemyEncyclopedia
---@field InfoItem1    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem2    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem3    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem4    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem5    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem6    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem7    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field InfoItem8    Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field SpecialItem1 Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field SpecialItem2 Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field SpecialItem3 Source.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow

---@class Source.UI.WindowEnemyEncyclopedia: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.WindowEnemyEncyclopedia
---@field assets   Source.UIBase.GeneratedAssets.WindowEnemyEncyclopedia
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.WindowEnemyEncyclopedia
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
