-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.WindowMessage

---@class Source.UIBase.GeneratedControls.WindowMessage
---@field ConfirmLayer  Engine.FunctionalImage
---@field Content       Engine.Canvas
---@field MessageList   Engine.ListView
---@field MessageText   Engine.RichText
---@field NameText      Engine.PlainText
---@field Panel         Engine.Canvas
---@field Root          Engine.Canvas
---@field SelectionList Engine.ListView
---@field WindowFrame   Engine.Window

---@class Source.UIBase.GeneratedAssets.WindowMessage
---@field SelectionItem1 Source.UI.Parts.WindowMessage.MessageOptionRow
---@field SelectionItem2 Source.UI.Parts.WindowMessage.MessageOptionRow
---@field SelectionItem3 Source.UI.Parts.WindowMessage.MessageOptionRow
---@field SelectionItem4 Source.UI.Parts.WindowMessage.MessageOptionRow

---@class Source.UI.WindowMessage: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.WindowMessage
---@field assets   Source.UIBase.GeneratedAssets.WindowMessage
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.WindowMessage
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
