-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.WindowShop

---@class Source.UIBase.GeneratedControls.WindowShop
---@field Root Engine.Canvas

---@class Source.UIBase.GeneratedAssets.WindowShop
---@field DetailAsset Source.UI.Parts.WindowShop.WindowShopDetail
---@field ItemAsset   Source.UI.Parts.WindowShop.WindowShopItem
---@field TabsAsset   Source.UI.Parts.WindowShop.WindowShopTabs

---@class Source.UI.WindowShop: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.WindowShop
---@field assets   Source.UIBase.GeneratedAssets.WindowShop
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.WindowShop
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
