-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.WindowSaveLoad

---@class Source.UIBase.GeneratedControls.WindowSaveLoad
---@field Root Engine.Canvas

---@class Source.UIBase.GeneratedAssets.WindowSaveLoad
---@field DetailAsset Source.UI.Parts.WindowSaveLoad.WindowSaveDetail
---@field SlotAsset   Source.UI.Parts.WindowSaveLoad.WindowSaveSlot
---@field TabsAsset   Source.UI.Parts.WindowSaveLoad.WindowSaveTabs

---@class Source.UI.WindowSaveLoad: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.WindowSaveLoad
---@field assets   Source.UIBase.GeneratedAssets.WindowSaveLoad
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.WindowSaveLoad
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
