-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.WindowMenu

---@class Source.UIBase.GeneratedControls.WindowMenu
---@field Content       Engine.Canvas
---@field MenuList      Engine.ListView
---@field MenuScrollBox Engine.ScrollBox
---@field Root          Engine.Canvas
---@field WindowFrame   Engine.Window

---@class Source.UIBase.GeneratedAssets.WindowMenu
---@field MenuItem1 Source.UI.Parts.Shared.CommandRow
---@field MenuItem2 Source.UI.Parts.Shared.CommandRow
---@field MenuItem3 Source.UI.Parts.Shared.CommandRow
---@field MenuItem4 Source.UI.Parts.Shared.CommandRow
---@field MenuItem5 Source.UI.Parts.Shared.CommandRow

---@class Source.UI.WindowMenu: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.WindowMenu
---@field assets   Source.UIBase.GeneratedAssets.WindowMenu
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.WindowMenu
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
