-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.UI.WindowAttrShop

---@class Source.UIBase.GeneratedControls.WindowAttrShop
---@field AbilityList      Engine.ListView
---@field AbilityScrollBox Engine.ScrollBox
---@field Avatar           Engine.FunctionalImage
---@field Content          Engine.Canvas
---@field Description      Engine.FunctionalPlainText
---@field Price            Engine.FunctionalPlainText
---@field Root             Engine.Canvas
---@field ShopName         Engine.FunctionalPlainText
---@field WindowFrame      Engine.Window

---@class Source.UIBase.GeneratedAssets.WindowAttrShop
---@field AbilityItem1 Source.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem2 Source.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem3 Source.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem4 Source.UI.Parts.WindowAttrShop.AttrShopRow
---@field AbilityItem5 Source.UI.Parts.WindowAttrShop.AttrShopRow

---@class Source.UI.WindowAttrShop: Source.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Source.UIBase.GeneratedControls.WindowAttrShop
---@field assets   Source.UIBase.GeneratedAssets.WindowAttrShop
---@field new      fun(instance?: Engine.AssetInstance): Source.UI.WindowAttrShop
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
