-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.GlobalCore.WeatherType

---@class Enums.GlobalCore.WeatherType
---@field NONE GlobalCore.WeatherType
---@field RAIN GlobalCore.WeatherType
---@field SNOW GlobalCore.WeatherType
---@field STORM GlobalCore.WeatherType
---@type Enums.GlobalCore.WeatherType
local enum = {}

return enum
