-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.GlobalCore.WorldRegionState

---@class Enums.GlobalCore.WorldRegionState
---@field Active GlobalCore.WorldRegionState
---@field Dormant GlobalCore.WorldRegionState
---@field Prepared GlobalCore.WorldRegionState
---@field Reading GlobalCore.WorldRegionState
---@field Unloaded GlobalCore.WorldRegionState
---@type Enums.GlobalCore.WorldRegionState
local enum = {}

return enum
