-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@meta Enums.GlobalCore.WorldRegionDemand

---@class Enums.GlobalCore.WorldRegionDemand
---@field Active GlobalCore.WorldRegionDemand
---@field None GlobalCore.WorldRegionDemand
---@field Prepared GlobalCore.WorldRegionDemand
---@type Enums.GlobalCore.WorldRegionDemand
local enum = {}

return enum
