-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair

---@class Internal.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field Label     Engine.PlainText
---@field LabelArea Engine.Canvas
---@field Root      Engine.Canvas
---@field Value     Engine.PlainText
---@field ValueArea Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair

---@class Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaInfoPair
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
