-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow

---@class Internal.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field Description     Engine.PlainText
---@field DescriptionArea Engine.Canvas
---@field Name            Engine.PlainText
---@field NameArea        Engine.Canvas
---@field Root            Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow

---@class Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowEnemyEncyclopedia.EnemyEncyclopediaSpecialRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
