-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowSaveLoad.WindowSaveTabs

---@class Internal.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveTabs
---@field Content     Engine.Canvas
---@field Root        Engine.Canvas
---@field Tabs        Engine.TabView
---@field WindowFrame Engine.Window

---@class Internal.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveTabs
---@field WindowChrome    Internal.UI.Parts.Shared.WindowChrome
---@field WindowPauseMark Internal.UI.Parts.Shared.WindowPauseMark

---@class Internal.UI.Parts.WindowSaveLoad.WindowSaveTabs: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveTabs
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveTabs
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowSaveLoad.WindowSaveTabs
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
