-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Internal.UI.Parts.WindowSaveLoad.WindowSaveSlotRow

---@class Internal.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveSlotRow
---@field Label Engine.PlainText
---@field Root  Engine.Canvas

---@class Internal.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveSlotRow

---@class Internal.UI.Parts.WindowSaveLoad.WindowSaveSlotRow: Internal.UIBase.UiView
---@field root     Engine.Canvas
---@field controls Internal.UIBase.GeneratedControls.Parts.WindowSaveLoad.WindowSaveSlotRow
---@field assets   Internal.UIBase.GeneratedAssets.Parts.WindowSaveLoad.WindowSaveSlotRow
---@field new      fun(instance?: Engine.AssetInstance): Internal.UI.Parts.WindowSaveLoad.WindowSaveSlotRow
local View = {}

---@param instance Engine.AssetInstance | nil
function View:init(instance) end

return View
