-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowEquip.EquipSlotRow")

---@class Source.UI.Parts.WindowEquip.WindowEquipSlot
local View = {}

View.assetKey = "Parts/WindowEquip/WindowEquipSlot"
View.designSize = sf.Vector2f.new(192, 160)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        SlotList = assert(self.instance:requireControl("SlotList")),
        SlotScrollBox = assert(self.instance:requireControl("SlotScrollBox")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipSlot
    self.controls = controls
    local assets = {
        SlotPlaceholder1 = self:own(ChildView1.new(assert(self.instance:requireAsset("SlotPlaceholder1")))),
        SlotPlaceholder2 = self:own(ChildView1.new(assert(self.instance:requireAsset("SlotPlaceholder2")))),
        SlotPlaceholder3 = self:own(ChildView1.new(assert(self.instance:requireAsset("SlotPlaceholder3")))),
        SlotPlaceholder4 = self:own(ChildView1.new(assert(self.instance:requireAsset("SlotPlaceholder4"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipSlot
    self.assets = assets
end

return class(View, UiView)
