-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowEquip.WindowEquipStatus")

---@class Source.UI.Parts.WindowEquip.WindowEquipStatusPane
local View = {}

View.assetKey = "Parts/WindowEquip/WindowEquipStatusPane"
View.designSize = sf.Vector2f.new(256, 352)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowEquip.WindowEquipStatusPane
    self.controls = controls
    local assets = { StatusAsset = self:own(ChildView1.new(assert(self.instance:requireAsset("StatusAsset")))) }
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowEquip.WindowEquipStatusPane
    self.assets = assets
end

return class(View, UiView)
