-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.CoordinateType
local enum = {
    Normalized = (0 --[[@as sf.CoordinateType]]),
    Pixels = (1 --[[@as sf.CoordinateType]]),
}

return enum
