-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.PrimitiveType
local enum = {
    LineStrip = (2 --[[@as sf.PrimitiveType]]),
    Lines = (1 --[[@as sf.PrimitiveType]]),
    Points = (0 --[[@as sf.PrimitiveType]]),
    TriangleFan = (5 --[[@as sf.PrimitiveType]]),
    TriangleStrip = (4 --[[@as sf.PrimitiveType]]),
    Triangles = (3 --[[@as sf.PrimitiveType]]),
}

return enum
