-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.StencilComparison
local enum = {
    Always = (7 --[[@as sf.StencilComparison]]),
    Equal = (5 --[[@as sf.StencilComparison]]),
    Greater = (3 --[[@as sf.StencilComparison]]),
    GreaterEqual = (4 --[[@as sf.StencilComparison]]),
    Less = (1 --[[@as sf.StencilComparison]]),
    LessEqual = (2 --[[@as sf.StencilComparison]]),
    Never = (0 --[[@as sf.StencilComparison]]),
    NotEqual = (6 --[[@as sf.StencilComparison]]),
}

return enum
