-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.StencilUpdateOperation
local enum = {
    Decrement = (4 --[[@as sf.StencilUpdateOperation]]),
    Increment = (3 --[[@as sf.StencilUpdateOperation]]),
    Invert = (5 --[[@as sf.StencilUpdateOperation]]),
    Keep = (0 --[[@as sf.StencilUpdateOperation]]),
    Replace = (2 --[[@as sf.StencilUpdateOperation]]),
    Zero = (1 --[[@as sf.StencilUpdateOperation]]),
}

return enum
