-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Mouse.Button
local enum = {
    Extra1 = (3 --[[@as sf.Mouse.Button]]),
    Extra2 = (4 --[[@as sf.Mouse.Button]]),
    Left = (0 --[[@as sf.Mouse.Button]]),
    Middle = (2 --[[@as sf.Mouse.Button]]),
    Right = (1 --[[@as sf.Mouse.Button]]),
}

return enum
