-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT.
---@class Enums.sf.Mouse.Wheel
local enum = {
    Horizontal = (1 --[[@as sf.Mouse.Wheel]]),
    Vertical = (0 --[[@as sf.Mouse.Wheel]]),
}

return enum
