-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")

---@class Source.UI.Parts.WindowShop.WindowShopCell
local View = {}

View.assetKey = "Parts/WindowShop/WindowShopCell"
View.designSize = sf.Vector2f.new(144, 32)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Icon = assert(self.instance:requireControl("Icon")),
        Root = assert(self.instance:requireControl("Root")),
        ValueText = assert(self.instance:requireControl("ValueText"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowShop.WindowShopCell
    self.controls = controls
    local assets = {}
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopCell
    self.assets = assets
end

return class(View, UiView)
