-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.WindowShop.WindowShopCell")

---@class Source.UI.Parts.WindowShop.WindowShopItem
local View = {}

View.assetKey = "Parts/WindowShop/WindowShopItem"
View.designSize = sf.Vector2f.new(352, 256)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        ItemList = assert(self.instance:requireControl("ItemList")),
        ItemScrollBox = assert(self.instance:requireControl("ItemScrollBox")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowShop.WindowShopItem
    self.controls = controls
    local assets = {
        ShopItemPlaceholder1 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder1")))),
        ShopItemPlaceholder10 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder10")))),
        ShopItemPlaceholder11 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder11")))),
        ShopItemPlaceholder12 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder12")))),
        ShopItemPlaceholder13 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder13")))),
        ShopItemPlaceholder14 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder14")))),
        ShopItemPlaceholder2 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder2")))),
        ShopItemPlaceholder3 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder3")))),
        ShopItemPlaceholder4 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder4")))),
        ShopItemPlaceholder5 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder5")))),
        ShopItemPlaceholder6 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder6")))),
        ShopItemPlaceholder7 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder7")))),
        ShopItemPlaceholder8 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder8")))),
        ShopItemPlaceholder9 = self:own(ChildView1.new(assert(self.instance:requireAsset("ShopItemPlaceholder9"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopItem
    self.assets = assets
end

return class(View, UiView)
