-- Generated by ScriptTools ui-assets generate. Do not edit.
local UiView = require("Source.UIBase.UiView")
local ChildView1 = require("Source.UI.Parts.Shared.WindowChrome")
local ChildView2 = require("Source.UI.Parts.Shared.WindowPauseMark")

---@class Source.UI.Parts.WindowShop.WindowShopDetail
local View = {}

View.assetKey = "Parts/WindowShop/WindowShopDetail"
View.designSize = sf.Vector2f.new(352, 96)

function View:init(instance)
    UiView.init(self, instance)
    local controls = {
        Content = assert(self.instance:requireControl("Content")),
        Description = assert(self.instance:requireControl("Description")),
        DescriptionArea = assert(self.instance:requireControl("DescriptionArea")),
        ItemName = assert(self.instance:requireControl("ItemName")),
        Price = assert(self.instance:requireControl("Price")),
        PriceLabel = assert(self.instance:requireControl("PriceLabel")),
        Root = assert(self.instance:requireControl("Root")),
        WindowFrame = assert(self.instance:requireControl("WindowFrame"))
    }
    ---@cast controls Source.UIBase.GeneratedControls.Parts.WindowShop.WindowShopDetail
    self.controls = controls
    local assets = {
        WindowChrome = self:own(ChildView1.new(assert(self.instance:requireAsset("WindowChrome")))),
        WindowPauseMark = self:own(ChildView2.new(assert(self.instance:requireAsset("WindowPauseMark"))))
    }
    ---@cast assets Source.UIBase.GeneratedAssets.Parts.WindowShop.WindowShopDetail
    self.assets = assets
end

return class(View, UiView)
